### ISSUE TITLE
Armor Spawn Rate

### ISSUE THREAD

**Issue by Baalith** [mekanism/Mekanism#1881]
I noticed, that the chance that mobs have armor equipped seems to be a bit too high.
I set the rate (D:MobArmorSpawnRate=0.01) to 0.01 in the config but I see no difference to the default.
Maybe it's worth to revise the code for this. :)

**Comment by EzerArch** [comment]
Not a bug report, it's a question about how MobArmorSpawnRate affects the game.

Does MobArmorSpawnRate make the game spawn more/less armored mobs in general (Mek + vanilla armor) or more/less mobs with Mekanism armor (but keeping vanilla rate)?

I lowed the value intending to spawn less mobs armored with Mek items, but it seems to be affecting the vanilla-armored mob spawn rate too. I'd like to lower only Mek-related armored mobs, because it kind of defeats the need of mining ores to craft armor since you can just harvest mobs for drops.

**Comment by DarthDestructus** [comment]
I use a very old version of the mod. I want to also limit the amount of times I encounter a mob with Mekanism armor on. Could I please see how you guys are embedding the config code needed for this task?

**Comment by EzerArch** [comment]
@DarthDestructus:
```
general {
        D:MobArmorSpawnRate=0.005
    }
```
Full cfg: https://gist.github.com/EzerArch/5ea7d8b45691f9f9e494c24652a17fa5
