### ISSUE TITLE
Gas-Burning generator shows a wrong burn rate for Ethylene

### ISSUE THREAD

**Issue by Poulpynou** [mekanism/Mekanism#5047]
Hello!
The Gas-Burning generator, only when filled with ethylene, shows a wrong maximal burn rate of 28 (mB/t) while it's in reality only 0,7 mB/t.

To reproduce :
Put 2 Gas-Burning generator connected to 1 energy cube each. Prevent the energy production before the "start" of the trial with the redstone condition. Fill one with Hydrogen (it burns at 100 mB/t) and the other one with Ethylene. Lauch the 2 generator, and stop them about 5 seconds later. The amount of mB of Hydrogene /100 consumed on the left is equal to the number of tick. Divide the number of mB of Etylene consummed with the number of tick to get the burn rate : 0,7 mB/t instead of 28 mB/t

**Forge:** 1.12.2-14.23.3.2655
**Mekanism:** 1.12.2-9.4.8.343

**Comment by aidancbrady** [comment]
Hi! Understand this is a very old issue :)

Different gases actually have different 'burn times' which represent how many ticks a single mB will burn for. Ethylene has a burn time of 40 ticks, which means it takes 2 seconds to burn through 1 mB of Ethylene when running at 1 mB/s. However, the Gas Burning Generator will scale the gas burn rate automatically based on how much it is receiving.

What you see as the 'Burn Rate' is actually how many total gas burn ticks are being processed each tick. The number is correct, but it is confusing. I've adjusted the 'Burn Rate' to present the amount (in mB) of gas burned rather than the burn ticks. This fixes this issue.
