### ISSUE TITLE
[1.12.2] [Bug] Logistics Pipes Pipes cause Mekanism's Dynamic Tanks to void their inventory

### ISSUE THREAD

**Issue by TheonlyTazz** [mekanism/Mekanism#5250]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism Tanks lose their content when near Logistics Pipes pipes and chunks gets unloaded and reloaded.

If Anymore Information is needed, feel free to ask

#### Steps to reproduce:
To reproduce:
- Create 2 mekanism dynamic tank. Fill one with liquid
- Hook up supplier and provider to either tank
- Unload chunks and reload them (by switching dimensions for example)
- Mekanism Tanks are both empty

#### Version (make sure you are on the latest version before reporting):

Forge Version: 
1.12.2 Forge-14.23.5.2782

Mekanism Version:
1.12.2-9.4.13.349

Logistics Pipes Version:
0.10.1.109

https://github.com/RS485/LogisticsPipes/issues/1198

**Comment by thiakil** [comment]
if you remove just the LP blocks, do the tanks maintain their contents?

**Comment by TheonlyTazz** [comment]
i havent tested this anymore because the packdevelopers moved away from Logistic pipes, but no. the tanks actually lost their data and thus their content

**Comment by Ommina** [comment]
For what it is worth, I've just had a dynamic tank repeatedly lose its contents, and I haven't used Logistic Pipes since 1.7.10.

Forge 2811

Originally with Mekanism-1.12.2-9.4.13.349.  Updated to 9.7.1.371 and the problem persisted.

Tank is 3x3, five tall.  Two valves.  One in each of the centre of top and bottom layers.  Tank did not cross chunk boundaries.  There are multiple tanks, separated by one block, if that kind of thing is important.  Fairly standard design of "dynamic tank frame, with glass faces".

**Comment by aidancbrady** [comment]
#5799 is tracking Dynamic Tank inventory loss issues. This specific interaction issue involves a now-unsupported MC build- if this specific issue recurs we will re-open.
