### ISSUE TITLE
How to empty chemical crystalizer?

### ISSUE THREAD

**Issue by Cosmology2727** [mekanism/Mekanism#5279]
Got a glitch in my system where my chemical crystalizer has less than 200 of a clean slurry in it, so it's stopped up my whole system of x5 ore production (not sure how it happened in the first place, lol, probably breaking some pipe mid production). Anyways, now I have a useless chemical crystalizer, because I can't figure out how to empty it! Is there any way to get that garbage out of there?

EDIT: Just happened again, this time I definitely didn't mess with the pressurized tubes. I now have ONE clean tin slurry in my chemical crystalizer, and it's stopped up the whole process, and now I need to make another one... at this rate I'll have a crystalizer for each type of ore, lol. Any help would be greatly appreciated.

**Comment by Jaari** [comment]
Have you tried using the [Gauge Dropper](https://wiki.aidancbrady.com/wiki/Gauge_Dropper) yet?

**Comment by thiakil** [comment]
Gauge dropper is the usual way. Did it work?

**Comment by pupnewfster** [comment]
Closing this as it is part of #5821

**Comment by msawatzky75** [comment]
on the 1.15.2-9.9.17.409 the Gauge Dropper did not work.

**Comment by tcsousa99** [comment]
I'm having the same problem as @msawatzky75, it should have a "dump" button like the chemical infuser.

**Comment by pupnewfster** [comment]
Yes it is known the gauge dropper does not work, commenting that you are having the same issue does *nothing* to help get it fixed sooner, if anything it slows things down as I am now having to write this response rather than work on fixing it. This issue was closed because it is part of #5821 with the fact that the gauge dropper does not properly work yet in the 1.15 branch.
