### ISSUE TITLE
Mekanism Error(s) with IC2 and Buildcraft

### ISSUE THREAD

**Issue by MonstahGames** [mekanism/Mekanism#5309]
#### Issue description:
Errors randomly get thrown in console by multiple mods, though i'm assuming this issue is
Mekanism related because i'm only running Mekanism cables through my base (and wind generators)

#### Steps to reproduce:
I'm not quite sure, this issue randomly started happening. Though i'm noticing my machines dont seem to have power, yet the cables are all showing green

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2768
**Mekanism:** 1.12.2-9.6.2.354
**Sponge:** 1.12.2-2768-7.1.5

https://pastebin.com/547JRDLw

**Comment by thiakil** [comment]
Hmm this looks a lot like you've got what I call 'yo-yo chunkloading', usually caused by one or more mods not checking if a chunk is loaded and so it continually gets loaded on an interaction, but as it's not player loaded, unloads quickly thereafter.

So this means its not very easy to nail this down. It would be appreciated if you could try the following:

- Test without sponge and see if the issue remains (it changes a fair amount of things internally)
- Try to reproduce with a minimum mod set and minimum in-world setup

This helps us narrow the problem down & with a small world setup you could send it to me for dissection (I can run it in the dev environment with debugger attached). I can't do this with a large modset, and a large world size is a lot of redundant data to sent over the internet.
