### ISSUE TITLE
Gas burning generator doesn't produce any extra power?

### ISSUE THREAD

**Issue by Testo0987** [mekanism/Mekanism#5441]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I was using the gas burning generator to produce power, which received hydrogen from an electrolytic separator but the separator used up all the power the gas burning generator produced, so it would be effectively useless.

#### Steps to reproduce:
1. Put gas burning generator down
2. Feed hydrogen from electrolytic separator into it
3. Use power from generator to power separator, and observe no extra power being produced.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.2 2808** 
**Mekanism: 1.12.2-1.2.0** 
**Other relevant version: Minecraft 1.12.2** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
yes, this is intended

**Comment by HalJordan** [comment]
The problem is that the system operates at a complete loss. There's no generation whatsoever, and it can't be fixed in configs since the separator's energy usage is tied to the energy found in hydrogen. It makes the gas burning generator utterly useless. The only way to get enough hydrogen to keep the generator running is to use multiple separators, or put 2 speed upgrades in the separator. 1 and you still don't produce enough, but with 2, the separator uses every rf/t that the generator produces and you break perfectly even on hydrogen generation. On top of that, energy upgrades don't appear to effect the separator at all. It uses the same 640 rf/t whether you have 0 energy upgrades in it, or 8.

I fully understand that balance needs to be in place. It's renewable energy, and much like the wind turbine that fluctuates or the solar generators that only work during the day, you don't want the gas burners to be OP. However, at this point they operate at a LOSS of energy. There's no reason to create them for power. Only to power the separator for your ore processing. Beyond that, don't bother. The gas burning generators are 100% broken in the current state.

**Comment by thiakil** [comment]
You're meant to use wind or solar to power the separator, especially if you're only burning hydrogen

**Comment by pupnewfster** [comment]
Burn ethene or some other mod's resource in the gas burning generator? Hydrogen is not the only gas that they accept, and it is intended that you don't gain infinite power with it using hydrogen.

**Comment by UpsetMan** [comment]
If you really are supposed to use some other form of energy generation to power the electrolyte separator, then what is even the point of having the gas-burning setup at all? The amount of energy the electrolyte separator is equal to the energy made by the gas-burning generator, so you might as well just not even bother with either of those and just pump whatever energy you were planning to use to power the electrolyte separator right into your base. Cant believe I wasted so much time making this thing just to find out it's totally useless...

**Comment by Silfryi** [comment]
The use of hydrogen in the GBG exists to allow for the recovery of a significant percentage of energy spent to produce oxygen. The _actual_ use of the GBG for power is meant to be through ethylene, which does have a power-positive loop, but also requires organic matter input for the extra energy provided. Hydrogen here is actually _more_ efficient than IRL as it's a perfect energy carrier, while IRL you'd have something like a 30% efficiency on the separator and a 60% efficiency on hydrogen -> power max.
