### ISSUE TITLE
Digital miner loading problem

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#5526]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hello, so i've been messing around with the digital miner radius configs (even though it says to leave it at the default), and i set it to 128. Everything works fine including performance, but i'm getting a problem with the loading. 
I afked in another dimension that the digital miner was not in, and everything was working fine since i had the chunk loading upgrade in the miner. After i got back, items seemed to stop coming in. I had got a large number of items, but not what i expected.
When i got to the miner, it says it had finished. However, when i hit reset and started it again, it says there were more ore. This kept happening over and over again.

What i think is happening is that since the default config radius for the digital miner is 32, the chunk loading upgrade won't work for higher. That explains why it worked for a little bit, but would stop working after i left the area. It had mined all the ores in 32 block radius, and since it wasn't chunk loading anymore, it thought it was finished.

#### Steps to reproduce:
1. Set the configs of the digital miner radius to 64 (or above)
2. Give it the chunk loading upgrade
3. Leave the area and afk for a while
4. Come back to see that no extra items are coming in
5. Go to the digital miner and see it had stopped
6. Reset it and start again, and see it says there are more ores to be mined, even though it supposedly finished.

#### Version (make sure you are on the latest version before reporting):
**Forge:*v2825* 
Mekanism:*1.12.2-9.7.8.379* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
The miner does refresh its chunkloaded chunks when the radius changes, it is based on the radius configured per-miner.

You'll need to check your log/config for limits on chunkloading - Forge itself has some default per-mod limits

**Comment by charliegc4** [comment]
I have the same issue, although I have not changed the radius. Mine is set to the default max at 32.

Every time I exit the game and come back, or  go to the Nether, the miner has stopped regardless that it has the anchor upgrade.

**Comment by thiakil** [comment]
Have you tried any other chunkloaders to see if there are problems there?
What version of mekanism are you using?
are you playing on a server?
what are the chunkloading configs on the server if so?

**Comment by charliegc4** [comment]
I tried with ChickenChunks 2.4.2.74, both with and without the anchor upgrade.

Using Mekanism-1.12.2-9.8.1.383

Not on a server, this is single player, not even connected to the Internet.

Sometimes it works, sometimes not. I can save a game and come back tomorrow, and it will resume running. Sometimes it won't. I setup two miners side-by-side in the same chunk, and when I came back from an excursion, one had stopped, one hadn't.

I setup a miner in the Nether with an anchor upgrade, and a ChickeChunk chunk loader nearby, and when I come back later it is not running. If I set it up with a Quantum Entangloporter so the mined items can be sent back to the Overworld, mostly it works. Sometimes it doesn't.

Just completely unreliable, which is a pity because it is such an amazing machine.

**Comment by thiakil** [comment]
The only reasons that would happen then is that something is telling it it can't mine those blocks, or something is forcibly unloading the chunks despite the loaders.

**Comment by charliegc4** [comment]
So here is an interesting development.

I am a big fan of EnderIO conduits, mostly because you can bundle them and hide them in a facade. But they have their issues like for some reason they occasionally don't work.

So, with exact same mods and settings I started a new game in which I did not place any EnderIO conduits. Instead I used a logistical transporters and universal power cables and the anchor upgrade.

So far, starting a new game, loading a saved game, going to the nether and back, or going on long excursions, the miner has not stopped working.;-)
