### ISSUE TITLE
Logistical transporter acts like full block

### ISSUE THREAD

**Issue by CraftalotReloaded** [mekanism/Mekanism#5530]
Even though the hitbox ain't a full block redstone etc can be placed on logistical transporters.
**Forge: 1.12.2 - 14.23.5.2836
**Mekanism: Mekanism-1.12.2-9.7.8.379
![2019-06-21_02 20 03](https://user-images.githubusercontent.com/39203645/59889249-cf797b00-93cb-11e9-96b8-c1d04a255b02.png)

**Comment by pupnewfster** [comment]
Looked at this a bit and the issue is that we do not override `Block#getBlockFaceShape(IBlockAccess, IBlockState, BlockPos, EnumFacing)`. I am not quite sure how BlockFaceShape works (making this return UNDEFINED) for BlockTransmitter does fix the issue though I am not sure if it should be returning a different value from that enum. @thiakil do you have any idea about how BlockFaceShape works? We also should probably implement this in more of our blocks when we are doing so (given glowpanels are currently also bugged similarly, and potentially other things (such as placing torches on the side of gas tanks).

**Comment by thiakil** [comment]
`UNDEFINED` looks fine, Cauldron returns that for the bottom side
