### ISSUE TITLE
Mekanism auto sort not working 100%

### ISSUE THREAD

**Issue by Testo0987** [mekanism/Mekanism#5531]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The mekanism auto-sort sometimes does not work 100% of the way. Example:
https://youtu.be/SyLc3sxUWuU

Edit: Sorry for the lag in the video, the actual game isn't like that. It's my recording software's problem i believe.

#### Steps to reproduce:
1. Get an elite factory
2. Put a bunch of items in
3. Observe some items getting bunched up

#### Version (make sure you are on the latest version before reporting):
**Forge:*v2825* 
**Mekanism:*1.12.2-9.7.8* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Testo0987** [comment]
Ok, when i try to put items inside because the slots are empty, the slots immediately get items inside of them. I think this is a graphical issue, and there are actually items in the empty slots but it's not updating the GUI.

**Comment by pupnewfster** [comment]
This is not a bug, it is a quality of life feature of 9.7.x that auto sort does not sort into slots where the output cannot stack with what is currently in that output slot. This makes it so that it actually has a chance of processing all of the resources rather than putting some into slots that it cannot continue processing in as the output of that slot has not been emptied yet.
