### ISSUE TITLE
Infinite power (Mod interaction)

### ISSUE THREAD

**Issue by Beserkerlel** [mekanism/Mekanism#5554]
(Posting in randomthings as well, don't know what mod would be at fault)

#### Issue description:
Universal cables in conjunction with spectre blocks can produce infinite rf with no source.

#### Steps to reproduce:
1. Any source of power into a mekanism universal cable connected to Spectre Energy Injector
2. Fill up cable and injector to max rf
3. Place any spectre coil and it transfers free rf at it's max transfer rate

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9-7-8.379
**Other relevant version:** RandomThings 4.2.7.1
** All The Mods 3 Remix 1.3.2 SP & MP

[gist/pastebin/etc link here]
GIF of example in single player, first found in server:
https://puu.sh/DPdI8/51836273ed.gif

**Comment by pupnewfster** [comment]
From the looks of it my guess is that is a bug in their mod, as if I understand what is going on from the gif the two points are connected by their mod. Seems almost like they do not support simulating energy transfer so when our cable is trying to see how much power it can send, they probably just think it actually sent it.

**Comment by pupnewfster** [comment]
Looked briefly at their code and my suspicion was correct, it seems they do not use the simulate boolean at all: https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/handler/spectrecoils/SpectreCoilHandler.java#L49 and just always add the energy anyways.

Closing this as this isn't a Mekanism bug and in fact probably happens with the majority of energy cables when connected in the same way to random things energy transfer stuff. You probably should open an issue on their tracker referencing this and the fact they should be obeying the simulate method (or at least not have any energy get added when simulate is true so that it fails more gracefully).
