### ISSUE TITLE
Personal Chest Dupe Bug

### ISSUE THREAD

**Issue by Focamacho** [mekanism/Mekanism#5557]
#### Issue description:
You can duplicate items using two personal chests.

#### Steps to reproduce:
_1._ Put 2 personal chests in the hotbar.
_2._ Open the first, put some items inside, and close.
_3._ Now u need to be fast(or have some lag). Open & drop the personal chest, and instantly change your hand to the other personal chest in the hotbar.
_4._ It's all. See the video for more info.
Video: https://www.youtube.com/watch?v=qlaD_9TIa08

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2836
**Mekanism:** 9.7.9.380

**Comment by pupnewfster** [comment]
Out of curiosity is this on a server or in single player? (Mainly asking so that I can try to reproduce it in the same environment type when it potentially may not happen in the other one)

**Comment by Focamacho** [comment]
Server, because it's easier to do with some lag. You can reproduce it in singleplayer too, but it's a lot harder.

**Comment by pupnewfster** [comment]
Haven't tried to replicate this yet or make a fix, but I believe what will fix it is instead of us passing the hand that is opening the chest between the server and client, if we also pass the slot ID that would fix it being able to have any doubt about what chest is really being opened. (More just putting this here as a reminder for when I get a chance to look at it more).

Also adding this to the 9.8.0 milestone as even if I don't end up replicating it (or even trying to replicate it), I probably will make the change I mentioned above which *should* fix it.

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours. I rewrote how the GUI gets opened for the Personal chest so this *should* be fixed as of this release, but if it isn't feel free to reopen/comment here and I can look into it more.

**Comment by Focamacho** [comment]
Hi, maybe I'm a little late but I decided to test the bug again today, and it keeps happening.
I could replicate the bug in singleplayer using this little macro:
![image](https://user-images.githubusercontent.com/48870573/64488928-01101e80-d224-11e9-9d59-d0e4df757247.png)

**Comment by PvPsFinest** [comment]
What did you use to test the macro?

**Comment by thiakil** [comment]
@Focamacho Can you please confirm which version of Mekanism you tested that with?

**Comment by Focamacho** [comment]
Latest version of Mekanism (1.12.2-9.8.3.390)
