### ISSUE TITLE
I am not experienced with this stuff can someone help?

### ISSUE THREAD

**Issue by BeastCrack** [mekanism/Mekanism#5563]
[crash-2019-07-11_15.08.20-server (1).txt](https://github.com/mekanism/Mekanism/files/3383609/crash-2019-07-11_15.08.20-server.1.txt)

**Comment by pupnewfster** [comment]
Please do not delete the format it is there for a reason, so that we can view things like the version of mekanism quicker. From what I can tell with your crashlog you are using version 9.7.0, this bug got fixed quite a while ago. The current latest version of Mekanism is 9.7.9, updating to it should fix your crash.

**Comment by BeastCrack** [comment]
Oh i am sorry but still thanks for the suggestion.
