### ISSUE TITLE
Mob can spawn in the induction matrix + Wrong capacity displays

### ISSUE THREAD

**Issue by Dams678** [mekanism/Mekanism#5602]
Some mobs spawn on my induction matrix and i have some ultimate induction cell in but the capacity is toggled to 2.14GRF/2.14GRF

![2019-08-07_01 35 58](https://user-images.githubusercontent.com/53841616/62584372-81093880-b8b4-11e9-8be3-166a220eb8c1.png)
![2019-08-07_01 41 04](https://user-images.githubusercontent.com/53841616/62584375-84042900-b8b4-11e9-9d54-c674dc491564.png)

**Forge: 14.23.5.2838** 
**Mekanism: 1.12.2-9.8.1.383** 
**Other relevant version:**

**Comment by rickyhoho** [comment]
same problem

**Comment by rickyhoho** [comment]
same version

**Comment by rickyhoho** [comment]
@thiakil

**Comment by pupnewfster** [comment]
The wrong capacity displays will be fixed in 9.8.2 by this commit https://github.com/mekanism/Mekanism/commit/b1ba9fd431301effceaa51e02b5624a211d908b4

In terms of mobs spawning inside the induction matrix, looking at the code I believe this is due to mobs being able to spawn on top of induction cells/providers. I will look into this some with thiakil and discuss what is the best way of solving this issue.

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2794015). What we ended up going with at least for now is making it so mobs can never spawn on induction cells/providers.
