### ISSUE TITLE
[Galacticraft integration] Wind Generators should not generate power in GC dimensions

### ISSUE THREAD

**Issue by database64128** [mekanism/Mekanism#5628]
**Describe the the feature you'd like**
Currently wind generators work in Galacticraft dimensions like space stations, generating as much electricity as they do in the overworld.

Please consider making the wind generator work according to the planet/moon/dimension's wind strength. Or simply change it to not generate any electricity when placed in a Galacticraft dimension.

**Comment by thiakil** [comment]
You can blacklist them in the config

**Comment by ToserBan** [comment]
Please dont switch them off in ALL GC dimensions, because in real life, there are many planets and even moons in our solar systems with an atmosphere and strong winds. I use mekanism and GC in my modpack and think these mods are working very well together. Ok, at space stations and little moons these wind generators are not very logical, but in my opinion, that "problem" should not be a priority of the mekanism development.

**Comment by thiakil** [comment]
Indeed, we have some GC compat (e.g. Solar I think). Adding wind gen compat is possible, but as you say not a huge priority given they can be manually disabled

**Comment by aidancbrady** [comment]
Marking this as closed given Galacticraft has yet to updated to 1.15. In the meantime, very easy to disable through the config.
