### ISSUE TITLE
Smelting factory silent

### ISSUE THREAD

**Issue by doctor-something5000** [mekanism/Mekanism#5632]
Hello to the devs of mekanism.
I would like to complain about the Basic/Adv/Elite smelting factory being silent. This is not the case as before installing any tier (Enegized smelter) to it, it produces sounds. This disapoints me a lot since I pretty much is a fan of industrial sounds and noises. I never ever have used the muffler upgrade even once. So please look into this problem and fix it. Thanks in advance.

**Comment by term2112** [comment]
I have also had this happen to me too when I have a lot of other machines, My jetpack is also silent

**Comment by doctor-something5000** [comment]
@term2112
Well your case is different as your case might be because as too many machines are running your speakers cannot do 
multi-sounding. Whereas my case here is that the smelting factory is being silent even when being used  alone.

**Comment by term2112** [comment]
I have tested it by itself, it still produces no sound for some reason

**Comment by pupnewfster** [comment]
After attempting to reproduce this and having issues, I managed to reproduce it. I believe factories do not start their sound for some reason if upgraded (from a machine that is working with sound) they will stop playing sound until replaced. I will try to track it down so that a fix can be included in 9.8.2

**Comment by doctor-something5000** [comment]
Thanks
