### ISSUE TITLE
Solar/Advanced Solar Generators Producing Less Power in the Desert

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5638]
I would think that these would be producing more power in a biome that sees a lot of sun, I am having an issue where its only producing 180j rather than the 280j that im used too.

**Comment by pupnewfster** [comment]
The way solar panels calculate efficiency changed at the beginning of this year (9.7.0) to more closely mirror real life. The issue with the efficiency in deserts being lower is not due to the lots of sun but due to the fact solar panels perform poorly in hot environments.

This article seems to have some information on the subject of heat on solar panels in the real world: https://www.civicsolar.com/article/how-does-heat-affect-solar-panel-efficiencies (Note I did not look too closely to see how much detail the article goes into)

**Comment by term2112** [comment]
I didnt know that about solar panal and I am an electronics major. Thanks for the help
