### ISSUE TITLE
Nether Portal Broken

### ISSUE THREAD

**Issue by Flactine** [mekanism/Mekanism#5679]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Nether Portal turn into "Missing Texture" Purple and Black, and when pass the portal, the portal is extinguished.
This bug only accured when Mekanism activied. If not install Mekanism, won't has this bug.

#### Steps to reproduce:
1.Use obsidian to make a portal, and ignite it.
![2019-11-15_22 26 05](https://user-images.githubusercontent.com/13342427/68950950-28710200-07f8-11ea-9435-fd41f4a60abb.png)

2.Passed this Portal and get into the nether, the portal is extinguished.
![2019-11-15_22 26 21](https://user-images.githubusercontent.com/13342427/68951017-46d6fd80-07f8-11ea-9001-0abcf0537cf6.png)
 
3. Ignite it again.
![2019-11-15_22 26 26](https://user-images.githubusercontent.com/13342427/68951066-548c8300-07f8-11ea-8d84-85aff0d8e274.png)

4.Back to the overworld, the portal is extinguished again.
![2019-11-15_22 26 36](https://user-images.githubusercontent.com/13342427/68951139-6d953400-07f8-11ea-9a6c-486046810e32.png)

5.Ignite the portal again, and get in, it generated another obsidian door, next the first door.
![2019-11-15_22 22 56](https://user-images.githubusercontent.com/13342427/68951209-91f11080-07f8-11ea-83ff-8f88ecc1caee.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.2.389
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash report
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Please post your complete mod list

**Comment by pupnewfster** [comment]
I believe this was probably some weird mod interaction, but I am going ahead and closing this as in 1.15 we now use a forge hook for adding refined obsidian blocks as valid nether portal frames, rather than using a registry replacement, which should be a lot more cross mod compatible.

**Comment by runescapejon** [comment]
I am having this exact issue and it seem It's from Mekanism and LiteLoader being together.. causing the missing nether portal

**Comment by runescapejon** [comment]
Will there be a fix for 1.12.2 or it's unsupported for that version?

**Comment by pupnewfster** [comment]
It is unlikely that 1.12 will receive an update as we are focusing on 1.15. Additionally, as forge no longer supports 1.12, even if we wanted to we would not be able to include the same hook in forge to not require doing a registry replacement.

**Comment by no-boot-device** [comment]
Is there any work around?

**Comment by Templarfreak** [comment]
This is a pretty catastrophic bug for 1.12.2 Mekanism, but for anyone willing to do some technical digging and fix it for themselves:

 using this branch, https://github.com/mekanism/Mekanism/tree/1.12

and commenting out `registry.register(BlockBasic.BlockPortalOverride.instance);` in main->java->mekanism->common->MekanismBlocks.java @ line 89 and then recompiling the mod and using that seems to fix most of the problems. I also commented out the overridden `neighborChanged` method of the `BlockBasic` class but I'm not 100% certain if that's necessary, I think mostly the registered `BlockPortalOverride` is what causes most of the problems.

This removes the ability to use the Refined Obsidian block as a component for making Nether Portals but in my opinion that's an acceptable trade-off to fix nether portals for Mekanism in 1.12.2. 1.12.2 is still a pretty widely-supported version of Modded Minecraft and some mods that I'm pretty fond of also became discontinued @ ~1.12.2 (such as Tough As Nails), it would be a shame for the latest supported 1.12.2 version of Mekanism to just not be apart of 1.12.2 modpacks because of this bug. I get that supporting multiple different versions of Minecraft, especially ones that are officially unsupported by Forge, is a big pain in the ass so hopefully this can help some people help themselves without having to bother Mekanism devs to patch this.

**Comment by no-boot-device** [comment]
Apologies for lateness, but if anyone else is having this issue and does not wish to build the edit themselves, here's a version with the changes suggested by @Templarfreak implemented. Do note that this does remove the ability to use Refined Obsidian for Nether Portals, which I have never done.

https://mega.nz/file/zPZB0QwD#WcPOyFc15LJD7iR31QHjwysAGXcOUisTDHQWmnEpySk
I will not be providing support for this, unfortunately. I have only tested `Mekanism-1.12.2-9.8.3.homebaked.jar`, but here's a screenshot of a LiteLoader mod (Mine Little Pony) running, Mekanism Energy Cells, and a Nether Portal at the same time.

![A Mine Little Pony avatar, a nether portal, and 4 Mekanism blocks.](https://user-images.githubusercontent.com/15254673/96550021-ec4ee880-1275-11eb-836e-eda3c6efb7a2.png)

**Comment by no-boot-device** [comment]
### Update: I've discovered that Extra Foam For Liteloader by asie also patches this issue, completely negating the need to disable Refined Obsidian portals and not possibly requiring that you use a compiled version from some random user on GitHub.
https://www.curseforge.com/minecraft/mc-mods/extra-foam-for-liteloader

Probably use that instead.
