### ISSUE TITLE
I found a bug in Mekanism version 9.8.3.390 in 1.12.X

### ISSUE THREAD

**Issue by wangyang0368** [mekanism/Mekanism#5701]
When I play the Mekanism 1.12.X 9.8.3.390 in minecraft 1.12.2, I found a bug in it. Everytime I try to go to the Nether through the portal, it will take me to the Nether with a NEW PORTAL, and the new portal has no portal blocks, instant there are air blocks or even error blocks.

**Comment by pupnewfster** [comment]
Closing this as in the 1.15 version we use a forge hook for allowing refined obsidian blocks to be used as a nether portal frame instead of doing a registry replacement, so this means that if something like this were to occur in 1.15 and not just be something due to the registry replacements done in 1.12, that it is likely to be a vanilla bug.
