### ISSUE TITLE
Message in chat

### ISSUE THREAD

**Issue by Dimentive** [mekanism/Mekanism#5707]
I removed the industrial diamond recipe with CraftTweaker, and I’m getting this message in the chat every time I enter a world.

WARNING: No Mekanism Enrichment Chamber recipe found for input: '<ic2:dust:5>' and output: '<ic2:crafting:19>'. Command ignored!

Strangely, I removed this recipe a long time ago, and I didn’t start getting this message until today.
****
**Versions**
Mekanism: 9.8.2.389
MC: 1.12.2
Forge: 14.23.5.2847

**Comment by pupnewfster** [comment]
If you changed your mods/something changed your oredict order for some reason, it could be that recipe never is being added anymore because a different recipe is being added for the output/input. But this message basically means that you have a CrT line trying to remove a recipe that is not found. If you remove the line (that isn't actually even doing anything as told by the message), then it will go away. Though I would also check the enrichment chamber recipes to see if some other recipe appeared that you do not actually want.
