### ISSUE TITLE
Coal Chunks mod clashing with the Mekanism

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5739]
#### Issue description:
Adding Coal Chunks mod with the Mekanism crashes the game on the startup.

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.35
**Mekanism: 9.9.1.392
**Other relevant version: coalchunks-1.15.1-1.2.1.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/C5PUXszB

**Comment by pupnewfster** [comment]
After installing Coal Chunks it seems the crash just has to do with Coal Chunks and not at all with Mekanism. The latest.log shows https://gist.github.com/pupnewfster/d13ba9fc86e071c1a008cde048e2e1d0 Unfortunately due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 forge doesn't stop on the first "fatal" error it comes across and crash logs for crashes during startup often point at the wrong thing. So the crash probably should be reported to their mod.
