### ISSUE TITLE
Powder redstone going wrong place

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5751]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you do shift+click on powder redstone to put into a machine it's always going to the energy place instead of object place.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1
**Other relevant version:** MC 1.15.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
The issue seems to be that a few things (mainly factories), are adding their energy slot before the other slots. So I probably will end up needing to move the slot to after that, which may mess up loading inventories of factories, but I am not going to mess with it until 9.9.3 when I am looking into #5743 as while fixing that I may come up with a better solution for persisting inventories. Maybe by saving the slot by type.
