### ISSUE TITLE
Quantum Entagloporter Dupe MC v.1.15.1

### ISSUE THREAD

**Issue by Millificent** [mekanism/Mekanism#5761]
#### Issue description:
Possible to place infinite entangloporters.
Identified in a server environment and happens in SSP.

#### Steps to reproduce:
1. Place new entangloporter
2. Set a frequency
3. Set to private
4. Break with any tool
5. Place the one you've grabbed
6. Keep placing with same inv slot and infinite entangloporters will be placed

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** Mekanism-1.15.1-9.9.1.392.jar
**Other relevant version:** 

Some nice pictures to show and tell
https://i.imgur.com/U1vvZ7V.gifv
https://i.imgur.com/2x1qgVp.png

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Testing in my dev branch of 9.9.2 I am not able to reproduce this, but I did change a few things about how quantum entangloporters have their data set, so I am going to hold off at looking more into this until 9.9.3; because once I release 9.9.2 (there are still a couple things I need to look into/fix first), if it ends up fixing it for you then I won't have to attempt to reproduce it.

**Comment by Millificent** [comment]
Thanks for responding so fast. We will update as soon as it appears - and let you know if the issues remains.  =]

**Comment by pupnewfster** [comment]
Ah forgot to mention yesterday when I had done so, but 9.9.2 is released, so whenever convenient or if you are playing a mod pack and are first going to wait for it to update, you can see if it is fixed or not.
