### ISSUE TITLE
Bins

### ISSUE THREAD

**Issue by closeshot** [mekanism/Mekanism#5762]
When using the configurator on a bin with items inside as a wrench the items get voided once the bin is placed back down. This is for minecraft version 1.15.1

**Comment by pupnewfster** [comment]
In the future please do not just delete the issue format as it does have helpful information for us. Given I believe this has to do with #5735 in that currently Mekanism is using a "hacky" way of handling keeping contents for drops, which the wrench does not see, though is fixed in this commit https://github.com/mekanism/Mekanism/commit/9c635d7cb5ae185e358ed4ad22e3b25ade7dfe2e and when 9.9.2 gets released will be fixed as well. (Which if it had already been released deleting the issue format would have led to further confusion due to the fact I wouldn't know if you are on a version before or after the fix was released)

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
