### ISSUE TITLE
Tanks don't emit light

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5765]
#### Issue description:
A tank with a light-emitting fluid (like Lava) in it doesn't emit light

#### Steps to reproduce:
1. Place down tank
2. Put lava in it
3. It's dark :(

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
This will be fixed in 9.9.4 as the needed forge patch has been merged in. I did while testing find #5800 but if you find any other issues with blocks not rendering light as they should in 9.9.4+ do make another issue for them (you can probably just combine them into one issue). For example I am unsure if mechanical pipes etc give light off as I haven't bothered to check and am not going to by 9.9.4

**Comment by pupnewfster** [comment]
Closing as 9.9.4 is now released.
