### ISSUE TITLE
Digital miner information

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5777]
**Describe the the feature you'd like**
Due to various changes in 1.14/1.15, it would be nice to introduce players to changes regardless tags and how to use them instead of ore dictionary entries. New tab in JEI explaining on how to use and properly configure all settings seems the best idea on how to do that.

Additionally some validation in the gui to use proper syntax while typing would be nice as well.

**Describe alternatives you've considered**
[Project Intelligence](https://github.com/brandon3055/PI-Docs/) would be nice alternative to JEI, but that's not yet updated for 1.15.

**Additional context**
Example screenshot of additional tab: 
![59081954-5b60b280-88b6-11e9-9ae9-14f3d67ff461](https://user-images.githubusercontent.com/4502802/72457133-d6c80200-37bd-11ea-9e8d-5f846997a4e2.png)

**Comment by pupnewfster** [comment]
I do agree with at least the fact that we can (and probably should), add validation to the extent of only allow valid characters for resource locations (plus `*`) into the text box, either auto lower casing capital characters or just refusing to enter them.

The JEI thing should be simple enough due to the fact I believe JEI has an "info" tab type. (Though maybe it makes more sense to just amend the description the digital miner shows when hovering the item and pressing the key combination.) Either way, the hardest/most annoying part to do probably would be actually coming up with the text to describe/explain it.

**Comment by aidancbrady** [comment]
The Dictionary has been updated to show the tag for any item or block analyzed. We've been discussing adding in-game wiki support in #5684.
