### ISSUE TITLE
electrolytic separator, gas generator, energy storage.

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5790]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The electrolytic separator has a weird power usage using upgrades, for example, a stock separator uses 400j/t and produces the same amount in hydrogen that the gas generator is burning. If all 8 energy upgrades are installed, the energy usage is reduced to 40j/t while the gas production stays the same. (energy is produced) Things start to get wacky once speed upgrades are added, once 4 upgrades are installed, the energy produced in hydrogen and used by the seperator are around the same. and then gets really inefficient with all 8 upgrades. I know that hydrogen is supposed to be more of a hydrogen storage rather than a producer.

#### Steps to reproduce:
1. connect the seperator to a creative power cube,
2. connect the gas generator to an empty creative power cube
3. connect the hydrogen gas side to the gas generator
4. Install the 8 energy upgrades
5. the energy used, produced values are out of whack

Ratios with 8 energy upgrades:
0 speed: 40j-400j, 1000% efficiancy 360j produced
1 speed: 142j-800j, 563% efficiancy 658j produced
2 speed: 506j-1600j, 316% efficiancy 1094j produced
3 speed: 1.8kj-
4 speed: 6.4kj-6.4kj, 100% efficiancy, all energy equals out
5 speed+: inefficient

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism: 9.9.3** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by term2112** [comment]
Another thing I have noticed is that with normal machines, the energy used doesn't really make much sense either. for example a stock energized smelter draws about 50j of power to smelt one item at a time. Its factory counterpart however only uses 10j for the same job.

other things to note:
-Max energy upgrades, divide power usage by 10x, this I believe should be nerfed a little bit

-Max speed upgrades, multiply power usage by 100x, I believe that the power used should be in 
 proportion to the speed gain.

**Comment by pupnewfster** [comment]
Thank you for the detailed issue report, and I will try to take a look at some of this stuff/fix it when I get the chance. The factory thing is fixed in this commit https://github.com/mekanism/Mekanism/commit/73bd8b1b649e49e544e2f7e0925093af8ca822d1 I had initially just added a TODO, but never went in and fixed it.

I believe that what may be going on with the electrolytic separator (though I will need to look more into it to see if this is the case), is that in 1.12 speed upgrades only adjusted one stat in it, while I believe they may be adjusting more stats currently and thus making them very inefficient.

When it comes to rates of upgrades I do agree they potentially should be adjusted some, so I will discuss this with some other people on the team, though I disagree that speed upgrades should directly correlate the energy increase to the speed gain, as it should cost at least slightly more (not sure on how much more), due to various causes, be it imperfections at running your machine at a faster rate and not being able to perfectly handle that much power or that it is the cost for having things be fast and simple rather than just having to wait less time as long as you can provide the same total power.

**Comment by pupnewfster** [comment]
So I looked into it some, in regards to the 10x and 100x things for energy/power there is a config option `maxUpgradeMultiplier` which is at the root of some math for them.

In regards to the energy usage rates for the electrolytic separator I was correct at my suspicion of what was throwing it off, but it turns out that currently in 9.9.3 the separator can just work without any power.. so not quite sure how you got your usage numbers, but either way the fact that it operates for free and shows massively incorrect usage numbers will be fixed in the next version.

**Comment by pupnewfster** [comment]
Closing as 9.9.4 is now released.
