### ISSUE TITLE
Crash with Digital miner

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5792]
## Issue description:
Crashed with digital miner. I was breaking trees with treecapitator. From the crashlog what might be breaking is the falling snow from [Snow Real Magic?](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)

Server seems fine

#### Steps to reproduce:
1. Set up digital miner
2. break tree causing snow to fall
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.41
**Mekanism:** Mekanism-1.15.1-9.9.3.394.jar
Pack: [Randomly Added Mods 0.1.1](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/Darkere/cf900c02480e325069b437389a5266eb

**Comment by pupnewfster** [comment]
I will look at this more later, but am mainly writing down my thoughts from looking briefly at it so that I remember.

I think this may have to do with when things like the miner (or other single block multiblocks aka things that use bounding blocks), go across `ChunkRenderCache`s (so probably also only on a server). Looking at `ChunkRenderCache#getBlockState` it does not seem to be all that safe of a call if the position is not in the range of blocks the cache is for.

**Comment by pupnewfster** [comment]
Made a small patch to "fix" this, so if it still happens in 9.9.5+ once 9.9.5 gets released let me know.

**Comment by pupnewfster** [comment]
Closing as 9.9.5 is now approved and on curseforge. Once again if you run into this again, do comment and I will reopen it, though I believe it shouldn't happen anymore
