### ISSUE TITLE
Upgrades vanished from machines after mod updates

### ISSUE THREAD

**Issue by oly2o6** [mekanism/Mekanism#5798]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
after updating forge and mekanism when loading the server back up everyone's upgrades disappeared from their machines (speed/gas/energy/anchor) 

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge-30.0.42 (updated from 36)
**Mekanism:** current: Mekanism-1.15.1-9.9.3.394 (updated from 392)
**Other relevant version:** minecraft 1.15.1

did not know if there is an actual issue here or not but i thought i would report it anyways incase its important and if not you can just close it

**Comment by pupnewfster** [comment]
This is one of the reasons why Mekanism is still in alpha and we include a warning that various things may disappear. I also try to be helpful and put in the commit message if I know that there is some issue that will likely occur so that it appears in the changelog. For 9.9.2 one of the commit messages included this: `WARNING: this likely will end up voiding some contents that are stored in machines/blocks that are picked up and some that are in machines/blocks that are placed. Especially for things like side configuration, and stored upgrades, I believe item inventories will be fine but various internal tanks will be wiped.` so it is a known and expected thing, but thanks for reporting it just in case.
