### ISSUE TITLE
Forge renamed ModConfigEvent.ConfigReloading

### ISSUE THREAD

**Issue by ppoozl** [mekanism/Mekanism#5804]
Cleanup fml packages removing old deprecated classes related to GUIs/Configs and fix HoverChecker (#6437)
		
		Fixed ModListWidget name to avoid confusion and collision.
		Delete CheckBox, as vanilla has it's own CheckBox now which looks much better
		Rename ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading

**Comment by pupnewfster** [comment]
Not sure what this issue is about? If it has to do with the crash on versions of 1.15.1 greater than 30.0.48, then update to 9.9.4 for 1.15.2 or if you insist on using 1.15.1, use 9.9.3 on 30.0.47.

**Comment by ppoozl** [comment]
sorry. I guess no new versions for 1.15.1?

**Comment by pupnewfster** [comment]
I don't have time to be supporting multiple versions of MC for Mekanism at once, ***ESPECIALLY*** multiple when they are of the same overall version of MC and are just minor versions, and forge doesn't even have an RB for that version of MC yet. I gave you your options, if you insist on using 1.15.1 instead of 1.15.2, then you can use an old version of Mekanism on a slightly out dated version of forge.
