### ISSUE TITLE
No way of making obsidian dust

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5805]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. insert obsidian in crusher or enrichment chamber
2. obsidian cannot be inserted
3. dust cannot be made

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.0.0** 
**Mekanism: 9.9.4** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by term2112** [comment]
I guess the only thing to do now is to wait for curse-forge approval. If I knew how to code java a little bit better, I wouldn't mind helping out. I know more c++ and arduino type stuff though.

**Comment by term2112** [comment]
what exactly is the difference between an alpha and a beta version of something too? Isn't beta the version where there are little to no game breaking bugs and a few minor bugs?

**Comment by pupnewfster** [comment]
First off I am working on other things currently and do plan on releasing an update later today, but that comes before any curseforge approval as it hasn't been pushed to curseforge yet. Secondly part of the reason Mekanism is still in alpha is due to the fact we are doing relatively large internal refactors/rewrites still and don't want to have to worry about backwards compatibility from one version to the next: https://github.com/mekanism/Mekanism#alpha-status

**Comment by pupnewfster** [comment]
Closing as 9.9.5 is now approved and on curseforge.
