### ISSUE TITLE
Cant craft the matchines 

### ISSUE THREAD

**Issue by HunterGinni** [mekanism/Mekanism#5809]
Guys i cant craft i just added the mod to the game 

I got the new resource like tin copper etc

But when i put them in the crafting tabble to craft the heat generator it dont work
NOTE :- No recipe show up in crafting table
I put the item after watching on the net
I cant craft anything

Help me!!

Game version : 1.15.1
Forge is latest i guess

**Comment by pupnewfster** [comment]
1. What version of Mekanism are you on.
2. You can't possibly be on the latest version of forge if you are on 1.15.1, because the newest (I believe three) versions of 1.15.1 forge don't work with any *released* Mekanism build, as I did not bother to release an update for them given I just updated directly to 1.15.2, so you would just be crashing on launch.
3. Do you have Mekanism Generators installed?
4. I would recommend installing JEI as it is rather helpful for figuring out recipes if you are having a hard time.

**Comment by HunterGinni** [comment]
> 1. What version of Mekanism are you on.
> 2. You can't possibly be on the latest version of forge if you are on 1.15.1, because the newest (I believe three) versions of 1.15.1 forge don't work with any _released_ Mekanism build, as I did not bother to release an update for them given I just updated directly to 1.15.2, so you would just be crashing on launch.
> 3. Do you have Mekanism Generators installed?
> 4. I would recommend installing JEI as it is rather helpful for figuring out recipes if you are having a hard time.

..
My forge is 30.0.36
Game working fine 
Can harvest all new ores and smelt them to ingots

Created a new world for this
 No crash or error

Just cant seem to craft the new recipes like heat generator for beginning

**Comment by Amcro** [comment]
@HunterGinni you're not on the latest forge and your guessing was wrong, to get help with your issue you'll need to be specific next time. As of the "can't craft" it's not issue, you probably didn't install mod called "Mekanism Generators" which has heat generator in it. Giving your mod list would be helpful and giving more information is required to find what is wrong. Since you are obviously not well informed about modded minecraft i'd suggest you to play modpacks on the twitch launcher since then you won't have to bother with issues with mods.

**Comment by HunterGinni** [comment]
> @HunterGinni you're not on the latest forge and your guessing was wrong, to get help with your issue you'll need to be specific next time. As of the "can't craft" it's not issue, you probably didn't install mod called "Mekanism Generators" which has heat generator in it. Giving your mod list would be helpful and giving more information is required to find what is wrong. Since you are obviously not well informed about modded minecraft i'd suggest you to play modpacks on the twitch launcher since then you won't have to bother with issues with mods.

..

Added the  Mekanism generators 

Working fine

Thx for helping
