### ISSUE TITLE
Allow disabling paxels

### ISSUE THREAD

**Issue by MarioSMB** [mekanism/Mekanism#5850]
For balance reasons (traditional servers that don't wish to provide all-in-one tools), it would be nice to be able to disable paxels from the configuration file.

**Comment by pupnewfster** [comment]
If you really want them disabled you can just disable their recipes, which will effectively disable paxels themselves.

**Comment by MarioSMB** [comment]
With all due respect, this is a valid issue and an oversight in the Mekanism configuration files.  
Most mods (including this one) provide the option to disable certain blocks and items that one may deem unbalanced or undesirable, without requiring the user to obtain and learn how to use third party scripting tools.  
This has been done for most machines in the mod, but not for the items for some reason.

I realise this issue's title is only for the paxels as they are the first items i've encountered in the mod that provide functionality from other standard mods (the AIOTs from Actually Additions - which you are able to disable in their configuration file), but it's clear now this option would be very useful if applied to every item in the mod.  

Please consider re-opening this issue with a more general use case in mind, as this would certainly benefit many users of the mod.

**Comment by pupnewfster** [comment]
1. The developers of forge are strictly against having config options dynamically change if things get registered. Lex's stance is very strong on the matter that if you want things disabled you disable their recipes that is the same way you do it in Vanilla (especially for 1.14+ with data packs)
2. We aren't really working on 1.12 anymore and in 1.15 we have removed the option to disable various machines via the config as well as it was too much of a pain to manage/maintain. Additionally in 1.15, we fully have support for data packs so you don't need a third party tool to be able to disable any recipes (you just need vanilla Minecraft to be able to), so that part of the request is moot.
3. Alternatively if you really don't want to install CrT in 1.12 to disable paxels you could set their durability in the config to say 1 so they are next to useless to actually use given they will break basically instantly.
