### ISSUE TITLE
Machine processing progress doesn't reset when items are removed

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5872]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
As described in title

#### Steps to reproduce:
1. Place & power a machine, put a processable item in the input slot
2. When the item is removed, the progress bar will not reset

**Comment by winsrp** [comment]
this actually also happens when you put something in a machine and watch progress for a sec, (so progress bar moves a little bit), then you exit gui and let machine finish working, when you come back it will display the same info as when you left the machine an it was working, this doesn't happens of you enter the machine before it has finished processing, the same issue seems to happen on values for liquids and energy. Seems like an update on progress and values is needed when entering the GUI of a machine when it is not working.

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge. Both the main bug (and the container sync bug have been fixed)
