### ISSUE TITLE
[1.12.2] Mekanism performance

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5880]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism causes hight load in my server

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2847
**Mekanism:** 9.8.3.390
**Other relevant version:** spongeforge-1.12.2-2838-7.1.9

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://sparkprofiler.github.io/#aPfDvQ512i

**Comment by bigenergy** [comment]
![image](https://user-images.githubusercontent.com/17977139/74649545-d93cc380-5190-11ea-9d6f-c879e3bbd425.png)

**Comment by pupnewfster** [comment]
Is this reproduceable in 1.15. As I have done a fair bit more related to performance on the 1.15 branch. Also 2.73% is not all that high compared to the total 22.7% for TEs given basically all our machines run through that method that is showing 2.73%

**Comment by aidancbrady** [comment]
Agree with @pupnewfster - this really isn’t significant load relatively. Regardless, we’ve made some major performance improvements in our 1.15 changes, I’d recommend upgrading when you can.

**Comment by bigenergy** [comment]
https://sparkprofiler.github.io/#g0GU9bHadz

@pupnewfster @aidancbrady This can take as much as 4 and 6 percent, it all depends on the load of players on the server.

Upgrading to 1.15 is great, but it doesn't make much sense as long as there is no sponge on 1.15.
Version 1.12.2 will remain in LTS (like 1.7.10).

**Comment by pupnewfster** [comment]
It is all well and good you want to keep playing 1.12, but we do not have the time or man power to support multiple versions at once. And actually technically 1.12.2 is not in LTS, it is 1.14 that is https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/ but even so it is harder to develop for than to develop for 1.15. Also it is not our problem that sponge is taking forever to update, given we are a *forge* mod not a *sponge* plugin, and I also have some doubts that part of the problem isn't being *caused* by sponge due to all the redirects the spark profile log seems to show before getting to our part of the code.
