### ISSUE TITLE
[1.12.2] Server crash - java.lang.NullPointerException: Ticking block entity 	at mekanism.common.content.transporter.TransitRequest.buildInventoryMap

### ISSUE THREAD

**Issue by ProsperCraft** [mekanism/Mekanism#5892]
#### Issue description:
Server crashed when player connected a mek pipe to 4 futurecraft machines.

#### Steps to reproduce:

> ]  B'rain De'quantus: i can try to reproduce it in singleplayer, was trying to automate a centrifuge, so placed a pipe between 4 machines to connect to a chest behind.
> [10:56 PM]  B'rain De'quantus: and was setting push/pull/ignire settings hwen it died

#### Version (make sure you are on the latest version before reporting):
**Forge:** Mohist-2b0299e-server
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:**  Modpack - TownCraft 1 Release branch - https://www.curseforge.com/minecraft/modpacks/towncraft

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/ProsperCraft/03ac1449f35dbd89f29e1da86ef90382

**Comment by braingkk** [comment]
happened specifically when I cycled past "pull" status on the research-Energy Module

tested in singleplayer and crashed there as well

**Comment by pupnewfster** [comment]
No idea what might be causing it and we are not actively developing for 1.12 anymore, but what mod is the research energy module for. I can probably take a brief look and see if I can at least see what is causing it.

**Comment by ProsperCraft** [comment]
Futurepack mod

**Comment by pupnewfster** [comment]
I would recommend reporting it to them, given I am pretty sure it is on their end as the line that is crashing with a null pointer is [this](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/content/transporter/TransitRequest.java#L57). And finder from the stack trace is initialized, so the only thing on that line that could be null is the item stack. And in 1.12 ItemStacks are supposed to be nonnull, which would imply future pack is not properly implementing their item handler capability.

Unfortunately because they seem to be closed source (only having their API open source), I cannot really look to confirm if this is in fact the issue.

Going ahead and closing this though as there is nothing on our end that should/could be causing it where the crash occurs and we aren't actively developing for 1.12 anymore anyways.
