### ISSUE TITLE
[1.15.2-9.9.10] Cardboard box blacklist

### ISSUE THREAD

**Issue by Quu1337** [mekanism/Mekanism#5899]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Cardboard box should come with some kind of default blacklist.
Being able to pick up Refined Storage Security Manager is bit bad.
Also LOCKED personal chests and machines can be picked by other players.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.14
**Mekanism:** 9.9.10
**Other relevant version:** All The Mods 5

**Comment by Yoosk** [comment]
It does come with blacklist in `BoxBlacklist.txt` file though.

**Comment by pupnewfster** [comment]
Firstly, BoxBlacklist.txt does not exist in 1.15.2 anymore. There is now a config option to blacklist by mod, and a block tag `mekanism/cardboard_blacklist`. Due to how tags work I would say the modpack developer should be disabling things like the refined storage security manager. (Or refined storage themselves could just include things they don't think should be picked up in our tag, which would only make it do anything when both mods are loaded).

I am going to leave this open for the time being however, as it probably does make sense for us to deny picking up our own locked machines.

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge. I fixed being able to pick up our own locked blocks, but after discussing it with aidan, we both agreed with my initial statement, that cross mod interaction of what blocks should not be picked up should be handled either by:
- The mod who believes their blocks should not be picked up
- The pack dev who put both mods in the same modpack.
