### ISSUE TITLE
Solar Neutron Activator Texture Giltch

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5902]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:Solar Neutron Activator's part of panel texture is rotated 180°:
![2020-02-25_14 01 43](https://user-images.githubusercontent.com/20492252/75221176-23025b00-57dc-11ea-98bf-26d0ee622cc4.png)

#### Steps to reproduce:
Place a Solar Neutron Activator, and check its top texture.
#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.1.14** 
**Mekanism:1.15.2-9.9.10.402** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge. Turns out there were two issues, the first of which I had noticed and already had fixed for 9.9.11, being the fact it was using the wrong render layer (the white bar in the middle is not supposed to be there), and secondly the texture of the top. Thanks for reporting it given no idea how I did not initially see it, when noticing the other issue.
