### ISSUE TITLE
Missing mod files in in twitch launcher or curseforge site

### ISSUE THREAD

**Issue by Greytusks** [mekanism/Mekanism#5905]
#### Issue description:
Missing mod files in in twitch launcher when looking for the mod, or broken download links when trying to install or download from curseforge.
MekanismAdditions-1.15.2-9.9.11.403.jar

#### Steps to reproduce:
1. Got to the mod's page on curseforge, hit the download button (or the twitch install button).
2. You should be at https://www.curseforge.com/minecraft/mc-mods/mekanism-additions/download
3. Notice  'This www.curseforge.com page can’t be found'

Alternatively, search for the mod in the curse launcher (1.15.2 version) and notice you can't find it. 

#### Version (make sure you are on the latest version before reporting):
**Forge: N/A
**Mekanism: MekanismAdditions-1.15.2-9.9.11.403.ja

**Other relevant version:** 
Just wanted to report the broken links, you can safely close this 'bug' once the upload is fixed.

**Comment by pupnewfster** [comment]
We don't control how the curse site displays things. When I hit download on the site it properly takes me to this link https://www.curseforge.com/minecraft/mc-mods/mekanism-additions/download/2888671

Additionally I believe the reason the twitch app does not show the additions module, is due to the fact it has only had alpha builds so the twitch app still considers the project as "experimental"
