### ISSUE TITLE
[1.15.2] Loading an old World with bio reactors leads to bio fuel as ticking entitiy

### ISSUE THREAD

**Issue by DietmarKrause** [mekanism/Mekanism#5952]
I am playing all the mods 5 pack and in latest version loading a world with 3 bio reactors an bio fuel in it leads to crash with bio fuel as ticking entity. Breaking the 3 reactors  (in older version everything is fine) changes nothing. Perhaps related crasholg: https://pastebin.com/xxakUeDh I can provide addition crashlogs if necessary

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-5/issues/35

**Comment by pupnewfster** [comment]
Can you provide your latest log as it seems something is screwed up with your registries overall.

**Comment by DietmarKrause** [comment]
here you are: https://pastebin.com/uBnPjjKD

**Comment by pupnewfster** [comment]
Downgrade mekanism, empty your factories, and then upgrade it again. In the changelog for one of the versions I did mention that it is highly recommended to empty a few specific machines before updating. This is part of the reason Mekanism is still in alpha so that we *can* make *breaking* changes when needed.

**Comment by DietmarKrause** [comment]
thank you for your help. it workes. Now i can load my world
