### ISSUE TITLE
[1.15.2-9.9.15.407] Hydrogen in Jetpack resets when upgrading to Armored Jetpack

### ISSUE THREAD

**Issue by shortybsd** [mekanism/Mekanism#5965]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Upgrading your normal Jetpack into an Armored Jetpack voids all hydrogen in it. Not for sure if this was intentional as the Cubes, Machines and so forth all retain their energy/gas/fluid.

#### Steps to reproduce:
1. Craft a Jetpack.
2. Fill Jetpack.
3. Upgrade Jetpack into an Armored Jetpack.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.18
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** N/A

**Comment by pupnewfster** [comment]
There is actually a few things at play here, firstly there is #5743 which is still not fully reimplemented (currently only doesn't properly transfer stored items). Though it turns out that when I rewrote the gas API I unintentionally ended up breaking the gas transferring in recipes. After looking a bit more at it, I think it will be a bit of a pain to fix/might make more sense to try and rewrite the recipe upgrade system (again), before it gets too out of hand/messy. So I am going to close this issue effectively merging/tracking it with #5743
