### ISSUE TITLE
Crash wit

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5989]
### Issue description: 
Crash due to robit with invalid UUID.

#### Steps to reproduce:
1. ??? 
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.27
**Mekanism:** 9.9.16

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/Darkere/1dfb0fa254194705a36949415e9ebd29

**Comment by pupnewfster** [comment]
#5970 not a bug, just something that is due to us not guaranteeing data compat from one alpha to the next even though we do our best to minimize it/mention known things in the commits, so they appear in the changelog. This case didn't show in the changelog because it was not one I realized would happen, but is only possible via upgrading a world from one alpha to newer alphas due to a change we made in some data we store.

**Comment by Darkere** [comment]
Ah weird I seem to have overlooked that one when searching. Ty was hoping that was the issue. 

We just removed it with NBT explorer.
