### ISSUE TITLE
A pre-programmed filter like the Crafing Formula

### ISSUE THREAD

**Issue by Lavan** [mekanism/Mekanism#5990]
**Describe the the feature you'd like**
As the Formulaic Assemblicator has its Crafting Formula, it would be nice if the Logistical Sorter could have something similar where you add filters using filter lists of some kind.

The same goes for the Digital Miner where it would be great if it was possible to add/remove filters easily.

**Describe alternatives you've considered**
There are no real alternatives to simplify this task. The only alternative I've found for the Digital Miner is to have multiple DMs and select the one with the filter you want right now.

**Additional context**

**Comment by pupnewfster** [comment]
Unless you mean for a new world (which I am assuming you don't due to the example of the crafting formula), you can use a configuration card on a miner to copy its configuration (I believe this includes filters), and then use it on another miner to paste the settings. (This at least removes the need for having multiple miners for different settings). I believe this also should work for the logistical sorter though I have never tried it on the sorter so I am not sure if it does.

**Comment by aidancbrady** [comment]
The Configuration Card works on the DM, Logistical Sorter, and any other machine that maintains some kind of configuration. I think this solves the issue you mention.
