### ISSUE TITLE
Oredictionificator and ordinary storage blocks

### ISSUE THREAD

**Issue by HowardRoark2016** [mekanism/Mekanism#6052]
I'm playing with All The Mods 5 (which is up to version 1.15 as of this moment) which is using Mekanism-1.15.2-9.9.18.410. I know that the Oredictionificator, by design, does not recognize block entries and for good reason (ex - glass might be converted to stained glass). However, I wonder if it is possible in a future update to only allow common ore blocks such as copper and tin. This mod pack has two kinds of tin blocks, three kinds of copper blocks, two kinds of silver blocks, and two kinds of zinc. It's just straight up ore for ore and nothing to exploit from converting those blocks. It would just help to keep things neater within a storage and crafting system (such as Refined Storage). Please consider allowing this, perhaps through a user-defined per-block config setting.

**Comment by pupnewfster** [comment]
There are plans to improve it as well as add a config, this is the default list currently: https://github.com/mekanism/Mekanism/blob/1.15x/src/main/java/mekanism/common/tile/TileEntityOredictionificator.java#L53 of prefixes that it supports. The plan is to eventually open that up to a config so that modpack creators can allow for a more diverse set of tags.
