### ISSUE TITLE
[1.15.2] Builds 411/412 Repeatable crash when combined with JAOPCA and Silent's Gems

### ISSUE THREAD

**Issue by elowanut** [mekanism/Mekanism#6063]
Getting a repeatable crash with the latest two builds of Mekanism (411 and 412) when combined with two other mods, JAOPCA and Silent's Gems. It is a "Registry object not present" error.

**Steps to reproduce:**
1. Load Minecraft with the latest version of Forge (forge-1.15.2-31.1.44), and load the following mods:

Mekanism-1.15.2-9.9.20.412
JAOPCA-1.15.2-3.2.0.8
SilentGems-1.15.2-3.5.1+84
SilentLib-1.15.2-4.6.0+48

These are all the latest versions of the mods.

2. Forge will begin loading everything, but then crashes back to launcher (log attached at end).

Removing any individual mod will stop the crash. Importantly, _reverting back to Mekanism-1.15.2-9.9.18.410 allows the game to start normally_.

A brief search indicates that this has also been submitted to the JAOPCA issue tracker here: [Issue #152](https://github.com/TheLMiffy1111/JAOPCA/issues/152)

**Versions:**
**Forge:** forge-1.15.2-31.1.44
**Mekanism:** Mekanism-1.15.2-9.9.20.412 (also does this on 411, but NOT 410)
**Other relevant version:** JAOPCA-1.15.2-3.2.0.8, SilentGems-1.15.2-3.5.1+84, SilentLib-1.15.2-4.6.0+48

**Crash log here:** [Gist link](https://gist.github.com/elowanut/8e8b6bcb3a4602ee7cc9aa9384729227)

**Comment by pupnewfster** [comment]
We did do some minor changes to gas object construction in 9.9.19, so it is likely we just broke backwards compat of our API given we are still in alpha for the express purpose of being able to do so. My guess is that this broke compat for JAOPCA so they need to update to fix it. On a side note that crash log does not actually provide any useful information due to: <https://github.com/MinecraftForge/MinecraftForge/issues/6374>
