### ISSUE TITLE
Faulty recipes | JEI Bug

### ISSUE THREAD

**Issue by PyroFlareX** [mekanism/Mekanism#6082]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Metallugic infuser in jei doesn't support Uses of redstone or any infusing material.

Reinforced Glass recipe is incorrect, should be 1 steel 4 glass for 4, not 4 steel 1 glass for 4.

#### Steps to reproduce:
1.Look at JEI recipe
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 44
**Mekanism:** 413
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Splitting the JEI part of this issue (which is not a bug, and more of a feature request) into a separate issue: #6091

**Comment by pupnewfster** [comment]
Turns out I didn't need to split the issue, but what is done is done. Given assuming by reinforced glass you mean structural glass, I just booted up a 1.12 instance and it is 4 steel + 1 glass to 4 structural glass, so the recipe is correct, my guess is that you are potentially thinking about the recipe from some other mod (hence why calling it "reinforced glass")
