### ISSUE TITLE
Crash... for no apperent reason

### ISSUE THREAD

**Issue by FrostStormRage** [mekanism/Mekanism#6087]
So crash due to an unknown reason, modpack that contain only mekanism mod. Maybe caused by latest version of forge, maybe not. No idea. The crash itself happens in a wierd way. So the minecraft starts up like normal, mods loaded, everything is fine. Upon creation of world, the modpack crashes. The crash occurs before world are initialized, settings for world is such:

Cheats: ON
Large Biomes
Bonus chest: ON
Structures: ON
Creative mode

Minecraft: 1.12.2
Mekanism:  1.12.2-9.8.3.390
Generator: 1.12.2-9.8.3.390
Tools: 1.12.2-9.8.3.390 

Here's crash
[crash-2020-04-21_17.16.20-server.txt](https://github.com/mekanism/Mekanism/files/4510894/crash-2020-04-21_17.16.20-server.txt)

**Comment by pupnewfster** [comment]
The format is there for a reason, what version are you on, and what leads you to believe it has anything to do with Mekanism?

**Comment by pupnewfster** [comment]
Can you please provide the crash log, (preferably on gist/pastebin or some other paste site).  I think you meant to upload it when you said "Here's crash" but forgot to actually do so.

**Comment by FrostStormRage** [comment]
1. Check the comment again! 
2. Re-open it!
3. Can i provide the crash!? Yee, if github allows to write it properly!!

**Comment by pupnewfster** [comment]
It seems the bounds set on the config option were not properly done so it doesn't enforce it. (Given we are no longer developing for 1.12 the config enforcing valid values will not be fixed). You should be able to fix this crash by changing `SaltVeinSize` in your mekanism config to at least `1`, if you are trying to disable salt from spawning you should instead set `SaltPerChunk` to `0` rather than setting the max vein size to be `0`.

**Comment by FrostStormRage** [comment]
ok, Ty!
