### ISSUE TITLE
"No key" for Mystical Agricultural

### ISSUE THREAD

**Issue by Sarge2318** [mekanism/Mekanism#6095]
The digital miner is leaving "Mystical Agricultural" ores in the ground. I tried several ways to find them then I came across someone saying use the "Dictionary" to find the tag. That is when I noticed there was not a tag for them.
![Mekanism missing feature](https://user-images.githubusercontent.com/63324439/80181654-dca65e00-85ca-11ea-965b-65389f18fdae.png)

1. Use the Dictionary on Mystical Agriculture blocks.

Forge: 31.1.47
Mekanism: 1.15.2-9.10.0.413
All the Mods 5: 1.18b

**Comment by Yoosk** [comment]
1. It's not up to mekanism to add ore dictionary entries (tags) for other mods.
2. You can add them alone using crafttweaker or kubejs or datapack.
3. You can ask Mystical Agriculture dev to add them.
4. You can use modid field in digital miner to mine all ores from that mod: `mystical*`
5. ATM modpack dev could/should add those instead of you, so post this issue on their git.

**Comment by pupnewfster** [comment]
It isn't our problem that the mystical agriculture devs don't bother adding tags for their ores, that is on them.

**Comment by Sarge2318** [comment]
> 1. It's not up to mekanism to add ore dictionary entries (tags) for other mods.
> 2. You can add them alone using crafttweaker or kubejs or datapack.
> 3. You can ask Mystical Agriculture dev to add them.
> 4. You can use modid field in digital miner to mine all ores from that mod: `mystical*`
> 5. ATM modpack dev could/should add those instead of you, so post this issue on their git.

Thank you for that informative reply. I will post this issue on their git. If no reply, I will try to add myself. I appreciate you helping me with the possible options.
