### ISSUE TITLE
[1.15.2] Max Vein Size for Ores

### ISSUE THREAD

**Issue by TheUntamed** [mekanism/Mekanism#6125]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In the configs the max value for the size of an ore vein is 65536. Which makes sense (16^3) but minecraft generation seems to work differently. With a size of 500 the underground already looks like this:
![Screenshot_65](https://user-images.githubusercontent.com/48363903/80870816-236e1500-8ca9-11ea-8c93-46a05781e9a7.jpg)

With a value around 700 or more the game already crashes due to an out of bound exception.

#### Steps to reproduce:
1. Set the amount of veins per chunk to 1
2. Set the size of a vein to a high number
3. Create a world

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.63** 
**Mekanism: 9.10.1.414** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/Ek2B3g9q

**Comment by aidancbrady** [comment]
Bro why do you want copper vein sizes of 700 in the first place

(We will look into changing the bounds but still I don’t think this is more config abuse than an issue 😂)

**Comment by pupnewfster** [comment]
I am going to go ahead and say this is a bug in vanilla and how it generates ores. My guess is this may even technically be possible in vanilla with things like iron ore generation, as it seems like it might crash if the ore reaches across more than one region file, which just becomes more likely with larger values. 

Also in regards to the max values for some of the config values, I went with values that made rough sense as max values though never tested the extremes as they were more meant as values that won't cause it to straight up crash due to the math. (The crash here is due to trying to actually generate the world partitions rather than crashing trying to parse the generation numbers)

**Comment by TheUntamed** [comment]
I just figured it out and wanted to let you know :)

I actually were tinkering around with stone variants like diorite, granite and andesite which are generated just like ores. I tried to completely replace the normal stone on certain y levels. So I set a min and max height and counted the amount of blocks between them. But minecraft said "no".
