### ISSUE TITLE
Cables disconnect after rejoining server

### ISSUE THREAD

**Issue by Swiftcreepa** [mekanism/Mekanism#6131]
Issue description:
Hey, So I've noticed that whenever our server restarts and takes us to the hub ( Sponge Forge ) it always disconnects the cables when others and I reconnect. This doesn't happen when we go through the multiplayer menu and connect directly to the server. We do not have Mekanism on the hub server but we do have it on the modded server. We also have Mek. Generators and Tools as well on the server.

Steps to reproduce:
1. Server Restarts > Forced into Hub Server
2. Rejoin main server > Cables disconnected
3. Have to replace all the cables. 

Forge: 8.0.99.99 ** 
Mekanism-1.12.2-9.7.9.380** 
MekanismGenerators-1.12.2-9.7.9.380
MekanismTools-1.12.2-9.7.9.380

**Comment by pupnewfster** [comment]
Going to go ahead and assume it has something to do with how sponge is redirecting causing it to not properly invalidate data. Though as sponge doesn't exist for 1.15 yet and the way that connections between pipes get rendered has changed in 1.15 I am going to go ahead and close this.

**Comment by Swiftcreepa** [comment]
Its on 1.12.2

**Comment by pupnewfster** [comment]
Which is why I gave you the information of: "Going to go ahead and assume it has something to do with how sponge is redirecting causing it to not properly invalidate data". Most likely the client the disconnect event is never being fired so the client is not aware it is no longer connected to the server and is unable to properly clear the various caches it has.

We are no longer actively developing Mekanism for 1.12, as we would rather spend our time working on developing Mekanism V10 now that the 1.15 version of Mekanism V9 is very stable and has a much cleaner codebase than the 1.12 version. However, even if we were still working on Mekanism 1.12 assuming my suspicions about the problem are correct, we wouldn't be able to fix this issue anyways as I find it highly likely that it is due to how sponge is redirecting.

**Comment by Swiftcreepa** [comment]
Alright, thanks for the responses. Considering that Mekanism is a staple mod for almost all packs with servers, I will take it into consideration to use another mod due to this issue. Thank you!
