### ISSUE TITLE
Basic Fluid Tank object not Present

### ISSUE THREAD

**Issue by Klouver0X** [mekanism/Mekanism#6140]
java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

[crash Log]
https://paste.ee/p/wgCat#section0

**Comment by Yoosk** [comment]
Any issues about `java.lang.NullPointerException: Registry Object not present` are due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 and forge not crashing on the first fatal error it comes across. So we need to look at the `latest.log` as the crash report does not properly point to what the issue is.

Also, playing modpack with 100 mods and only 3gb ram allocated might not be good idea.
