### ISSUE TITLE
i cant fix this can anyone help

### ISSUE THREAD

**Issue by dragnes5** [mekanism/Mekanism#6141]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
#### Steps to reproduce:
1.open the game
2.wait for initializing
3.game about to open then crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.71
**Mekanism:** 1.15.2-9.10.2.415

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest log](https://pastebin.com/gijEFBea)

**Comment by pupnewfster** [comment]
This has nothing to do with Mekanism and is just showing us in the crash log due to https://github.com/MinecraftForge/MinecraftForge/issues/6374. My best guess is that due to the many errors in your log with nightconfig (the library forge uses for configs something is screwed up).
```
com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
```
No idea how to fix it the only suggestion I have is to try removing optifine and hope for the best. If that doesn't work maybe assigning more ram if you are barely assigning any will help.

**Comment by dragnes5** [comment]
ok thanks
