### ISSUE TITLE
1.6.2 All factory types not working

### ISSUE THREAD

**Issue by pixel4802** [mekanism/Mekanism#6171]
The factories worked normally until today when all types of factories suddenly just stopped working.

![factory](https://user-images.githubusercontent.com/65568666/82258813-d0f45000-995a-11ea-93aa-05c87b153b3f.png)

**Comment by pupnewfster** [comment]
No idea what things to suggest as 1.6.4 is a very old version, and I am not even remotely familliar with the code due to only having joined the dev team last year. I also am not sure what you mean by "stopped" working but unless something worked very differently back in 1.6.4 none of those inputs are valid recipes in the combiner. I believe you need 8 of one type of dust to combine with the stored cobblestone to create a gold ore.
