### ISSUE TITLE
What exactly is bioethanol?

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6196]
I recently noticed a couple new items in the newest dev version of the mod, I am not sure if this is supposed to be a liquid replacement for bio-fuel in the bio generator? How will bio-fuel be converted into bio-ethanol?
![image](https://user-images.githubusercontent.com/41069911/83264628-5a432800-a18e-11ea-911e-1e7fdc82979a.png)

**Comment by pupnewfster** [comment]
Basically bio-fuel in the bio generator has always been converted to a pseudo fluid internally, and supported bioethanol from othe rmods as a liquid pumped into the bio generator. While reworking various internal systems it ended up adding our own fluid rather than just pretending there was a fluid, cut down drastically both on rendering and handling code we had to maintain.

**Comment by term2112** [comment]
ok, thank you

**Comment by TurnrDev** [comment]
I've noticed some mods use the forge fluidTag biofuel and some use the tag bioethanol, which does this use?
