### ISSUE TITLE
[1.12.2] Description: Ticking entity  java.lang.IllegalArgumentException: Invalid UUID string

### ISSUE THREAD

**Issue by MusicMaestro123** [mekanism/Mekanism#6198]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Open world
2. Place down Robit
3. Experience crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** Minecraft 1.12.2

**Comment by pupnewfster** [comment]
We are no longer developing for 1.12, but my best guess is that something corrupted the NBT of the robit you were holding and put an invalid uuid string in that portion of the NBT. No idea what though.

**Comment by StargateMC** [comment]
May I ask why @pupnewfster @aidancbrady ? Shouldn't mod authors be at least doing critical bugfixes to the versions that still retain the majority of mods and players?

![image](https://user-images.githubusercontent.com/9921203/83868442-36737980-a76e-11ea-8134-54bc8862830e.png)

You've probably got good reasons, I'm curious.

**Comment by MusicMaestro123** [comment]
I agree with @StargateMC on this one.

**Comment by pupnewfster** [comment]
The main part of it has to do with that we are doing this in our free time (and for free), and would much rather spend time working on developing Mekanism V10, than trying to backport things to an almost three year old minecraft version. Lots of the bug fixes/performance improvements we have made in 1.15 have been due to ***entirely*** rewriting the internals of the majority of systems in Mekanism which would take hundreds (if not thousands) of hours to backport, and it is just not worth the effort to us to spend the time doing so. Mekanism is MIT licensed it isn't like there is anything stopping some other person from forking it and spending their free time to try and bug fix the 1.12 version if they wanted to.

**Comment by StargateMC** [comment]
Fair enough @pupnewfster Thanks :) Will fork and add fixes as I need them.

**Comment by DarkEyeDragon** [comment]
If you want backwards bugfixes you can always do so yourself :) I get its frustrating (im playing on 1.7.10 modpacks rn) but it makes perfect sense not to support older versions. Maybe if it wouldnt affect the core of mekanism and there were like 20 lines to change between versions, sure. But sadly thats not the case. Forge got a few major rewrites over the years, and so did mekanism. Its just not feasable to do so.

**Comment by BraveCaperCat2** [comment]
The main modding versions of minecraft (as of 2023) are:

1. 1.12.2 (Used the most, without high memory usage and the best modding community - most mods are Here)
2. 1.7.10 (Same reasons as 1.12.2, but less mods, less memory usage, and i think better mods)
3. 1.16.5 (Later version introducing many more features than the above have, higher memory usage, more supported by mojang)
4. 1.18.2 (Same reasons as 1.16.5, but more intensive)
5. Latest (Latest release version, usually popularized for modding by it's new features.)
All the modding versions above are subject to change (but not for a while)
