### ISSUE TITLE
[1.15.2] Vanilla Bees Stuck On Advanced Solar Generators

### ISSUE THREAD

**Issue by ALEXTHENINJA007** [mekanism/Mekanism#6200]
#### Issue description:
Vanilla Minecraft Bees getting stuck in the Advanced Solar Generators. [https://imgur.com/a/mUmy366](https://imgur.com/a/mUmy366)

- I believe its the collision caused by the support beams of the solar panels coming from the central spire being the primary issue however they don't appear to navigate through the entire thing very effectively 

- Specifically witnessed for the solar evaporation plant placement, I'm also confident it should affects outstanding Advanced Solar Generators.

- To be fair this is more vanilla issue then Mekanism, however they may never make/have a need for bees to overcome this problem in Vanilla.

#### Steps to reproduce:
1. Build Solar Evaporation plant.
2. Have bees nearby or just spawn a bunch in/around the advanced solar generators.
3. Watch as there passive movement algorithm gets them stuck. 
3.5 Easily confirmed when night; this when bee behavior dictates they return to the nearest hive.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge_server.1.15.2-31.2.0
**Mekanism:** 1.15.2-9.10.6.419

**Comment by pupnewfster** [comment]
I may look into this more at some point, though I suspect you are right that it is a vanilla issue. Our bounding blocks use a flag to not have the shape get fully cached; after a brief look I believe the only vanilla blocks that use this flag are shulker blocks.

**Comment by Vaelzan** [comment]
It ah, isn't just bees. This one scared me a bit! (stuck there)

https://cdn.discordapp.com/attachments/552234021023776813/718346777513820190/unknown.png

I might do some testing later to see if it indeed impacts every mob that happens to move into one.

**Comment by desht** [comment]
Just noticed this and might be able to offer some advice, since I hit something similar in PneumaticCraft not long ago.  If your blocks don't have a full block shape (specifically, if `Block.isOpaque(shape)` returns true for your block's collision shape), but the block has an entity-blocking collision box, then entities will get very confused when trying to pathfind around your blocks - they think they can path through, but just get stuck forever.

Solution is to make sure that `Block#allowsMovement()` is properly overridden for any such blocks.  A simple implementation would just be to return `false` for any block which has a non-empty collision box.

**Comment by pupnewfster** [comment]
Thanks for that desht, they still sometimes bug out, but they now behave *a lot* better and rarely get stuck now,
