### ISSUE TITLE
Cardbox only one use?

### ISSUE THREAD

**Issue by cyberpunkbln** [mekanism/Mekanism#6201]
Hi,

is it possible to make the cardboxes only one useable, or can i tweak this with an datapack?

thx

**Comment by pupnewfster** [comment]
It is not currently possible to do so no, you potentially could make a feature request over [here](https://github.com/mekanism/Mekanism-Feature-Requests/issues), though please make it more detailed than just a one liner and explain the benefits of it/why you would want it. Do also note that a feature like that probably would end up being somewhat low priority to implementing (though maybe it would get implemented just due to if memory serves it should be relatively easy to add in an interception point for it to only be used once.)
