### ISSUE TITLE
mekanism power conduit isues

### ISSUE THREAD

**Issue by oraunarahlas** [mekanism/Mekanism#6256]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
My guess is that one of the other mods you have installed is doing something weird and either causing things to not load correctly or for the networks to not receive any ticks. For now I am going ahead and closing this as I don't believe it is something on our end, and if it is it likely got fixed in the rewrite of transmitters I did for V10 (which is being released for 1.16 on the 10th)
