### ISSUE TITLE
Meka-Tool Teleporation Sound

### ISSUE THREAD

**Issue by ChloeDawn** [mekanism/Mekanism#6305]
Teleporation using the meka-tool is eerily silent. A sound effect would definitely be an improvement to the immersion, I feel.

**Comment by pupnewfster** [comment]
From glancing at the code I believe what actually is happening is there is a sound (it uses the enderman teleport sound), but either it is not played to the player or it is played at the source of the teleport causing the player (who just teleported away) to not hear it due to being out of range of the sound.
