### ISSUE TITLE
Cardboard box

### ISSUE THREAD

**Issue by Massiewd** [mekanism/Mekanism#6331]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Cardboard box deletes Refined Storage Drives

#### Steps to reproduce:
1.Cardboard on drive 
2.Break 
3.Place
4. Watch Resources go away

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Refined Storage**
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
What version is this for?

**Comment by Massiewd** [comment]
15.2

**Comment by pupnewfster** [comment]
Not sure then what is going on, best bet is to just add refined storage's blocks to our cardboard blacklist tag as 1.15 is no longer being developed. I will talk with some people before 10.0.2 to see about if there is a common blacklist tag that can be decided on for forge so that other mods are more likely to be willing to add to it natively.
