### ISSUE TITLE
What's a fission reactor?

### ISSUE THREAD

**Issue by PeppaPig123456** [mekanism/Mekanism#6348]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Make a fission reactor.
2.Tell us how to make a fission reactor.
3.make a wiki or youtube video on how to make a fission reactor.
4.Help us make a fission reactor.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.62 and 32.0.69 
**Mekanism:** 9 and 10
**Other relevant version:** minecraft version 1.16.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by PeppaPig123456** [comment]
HI

**Comment by minecrafterseppe** [comment]
https://www.youtube.com/watch?v=jQRVqs4TUEU&t=468s

**Comment by ToMe25** [comment]
A few things about this:
1. "Mekanism: 9 and 10" i highly doubt that it applies to mekanism 9, because the fission reactor is new in mekanism 10.
2. There is no tutorial yet because its very new.
3. Try to build one in a creative test world, so you learn how to build it, there you can use `/mek build fission` and it will build you a max size(18x18x18) one, you can build it way smaller tho. The smallest you can build it is 3x4x3 blocks big.
4. I don't think this is the place to ask for documentation.
5. If the creative world thing doesn't help, here the description how to build it: you build a cube out of reactor glass or fission reactor casings, and replace the edges with fission reactor casings, then you put columns of Fuel Rod Assemblies with a Control Rod Assmebly ontop into it.

**Comment by thiakil** [comment]
> I don't think this is the place to ask for documentation.

It's fine, not everyone has Discord

But yes, as stated the video is probably your best bet at the moment
