### ISSUE TITLE
SPS disconnecting power when connecting more ports

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6351]
#### Issue description:
A sps sometimes doesn't accept power from all ports with supercharged coils.
I built one, and after leaving the world and loading it back up one of the ports doesn't accept energy anymore, at also visually has no lightning anymore, but its not just visual, also the processing speed is slowed down.
This seems to only happen when all ports are supplied with alot of energy.
Here before placing an energy source the coil on the left has a lightning and transfers energy
![2020-07-18_19 20 59](https://user-images.githubusercontent.com/38815969/87858254-ea028880-c92c-11ea-875c-1fcc3e7c6bd8.png)
here after placing it it does neither
![2020-07-18_19 21 02](https://user-images.githubusercontent.com/38815969/87858274-08688400-c92d-11ea-996f-2faf0c85335d.png)

#### Steps to reproduce:
1. Build an sps with a port and a supercharged coil on all four sides, and two ports without for polonium in and antimatter out on the top.
2. leave the world
3. load back into the world
4. see some coils(i had sometimes one and sometimes two) no longer working
5. play around with placing and breaking creative energy cubes next to the ports and notice strange behavior.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.67
**Mekanism:** 7e131d9
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
After looking into this more I don't believe it is actually a bug, and just has to do with how much energy the creative energy cubes can supply causing it so that three ports are able to fully convert the entire SPS input buffer, making it when it loads again having any extra buffers not be needed to run due to there being no input to convert.

**Comment by ToMe25** [comment]
I don't think thats the reason for this, because some times all four work with creative energy cubes, and sometimes only two do.

**Comment by pupnewfster** [comment]
After looking into this more it seems that I was correct, and the bug actually is that it allows inserting/using more energy than it can actually use to processes in one tick, as two ports supplied by creative energy cubes is enough to fully convert the stored buffer in one tick.

With Default configs:
- Each port can store/supply `1,000,000,000 J`
- SPS Input tank (not configurable) stores `2,000 mB`
- Energy per mB input `1,000,000 J`

This means that each port, when supplied infinite energy by the creative cube, can help process `1,000 mB` per tick. That means with two ports you can process `2,000 mB` per tick (the input buffer that the SPS can support). The "bug" is that there is no check that stops you from adding (or making it use) ***more*** energy than it actually needs. So if you "rebuild/replace" the port then the order things are ticking can cause it so that you have more ports adding their energy to the thing before it actually attempts to process it.

**Comment by pupnewfster** [comment]
This is now fixed in dev, turns out I was wrong about how the SPS is *meant* to "use" energy
