### ISSUE TITLE
SPS not starting

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6352]
#### Issue description:
The first sps in a world(maybe after restarting the game works too, idk) doesn't start as soon as it has power and polonium.
![2020-07-18_19 41 27](https://user-images.githubusercontent.com/38815969/87858549-eff96900-c92e-11ea-9b1f-af26ecc961fe.png)

#### Steps to reproduce:
1. Create a new world
2. build an sps(or do `/mek build sps` and add ports)
3. fill it with polonium
4. give it power
5. see it not starting by itself, only after leaving the world, and loading it again.(or sometimes when breaking a block of it and placing it again, but this isn't reliable)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.67
**Mekanism:** 7e131d9
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by ToMe25** [comment]
There seem to be multiple ways to cause this, but the only one i could reliable reproduce until now is placing the Supercharged coils after everything else, and then leaving the sps with tp or spectator mode.
This is not the only way to get this issue tho.

**Comment by pupnewfster** [comment]
Going to mark this as fixed as I did some improvements so that multiblocks revalidate a bit better when their internals are changed. There are still some edge cases where things don't properly update when the internals are modified while the multiblock is formed, but it isn't really a supported way of interacting with our multiblocks (though it is something I will look into further at some point). At least now if people accidentally place blocks inside of a thermal evaporation tower it will unform as that is the case that is important for us to support as it isn't a closed box and is more likely someone may do so.
