### ISSUE TITLE
Digital Miner conflict with Reskillable mod

### ISSUE THREAD

**Issue by therealfakemoot** [mekanism/Mekanism#6365]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
https://www.curseforge.com/minecraft/mc-mods/reskillable

I'm using the RLCraft modpack in conjunction with Mekanism. Reskillable gates certain blocks/items behind skill levels. Iron can't be mined until you have mining level 4 or what have you.

The issue arises because of the "fake player" the digital miner uses to execute its duties. This fake player has zero levels in anything, so the miner can only mine zero-skill blocks ( coal, Mekanism ores that aren't touched by reskillable, etc ). I have confirmed that the miner CAN mine osmium/copper, so the miner works.

#### Steps to reproduce:
1. Install Reskillable and Mekanism
2. Open a new creative world.
3. Place down an Iron Ore Block and make sure that the Reskillable mod will stop you from breaking it in Survival mode.
4. Place a Digital Miner, configure it to mine `oreIron`, set the radius and height min/max to their maximum values.
5. Start Digital Miner.
6. Observe that the oreIron isn't being mined. The machine will tally up the ore total, pause for several moments and then move into a Stopped state.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 8.8.99.99
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:** Minecraft version 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This isn't a bug. If you don't want Reskillable to prevent fake players from breaking blocks/interacting with them then disable applying it to fake players in the Reskillable config. I do have plans for trying to create a system to allow for our fake player to provide information on which player it is acting on behalf of (as we have that information due to our block security system). This will not make it into 1.12, and I am not sure yet which end the integration will be on (Mekanism or Epos).

**Comment by therealfakemoot** [comment]
Perfect, that's exactly the answer I was hoping for. Thank you for your prompt response. I'll look at the Reskillable configurations.
