### ISSUE TITLE
[Question] :  And Some concerns.

### ISSUE THREAD

**Issue by SirTwsted** [mekanism/Mekanism#6396]
Are Heat Generators suppose to chew up 64-Charcoal really fast when using the Metallurgic Infuser,
in the beginning of a world of the game.?   - Is this intended to do this like that.?
Because holy crap!,  Its going through coal ridiculously fast, just using 1 machine trying to progress the beginning. 

Also, is it possible that you can create something called - "Hell Coal" or "Hot Coal".
that comes from the nether since the nether is super hot,
that the nether coal can be used everywhere in game that Doubles of what regular coal does.?
obviously players would have to mine it from the nether.  And it could also be used as fuel source in your machines.

Im using MC-v1.16.1 with latest Forge on PC.

Thanks :)

**Comment by KrAzYGEEK32** [comment]
Yes, I think that is heat generator's intended behaviour. although they are mainly used for passive power generation through lava, if a heat gen has lava in its adjacent block, it passively produces 5fe/t and it's incremental for each adjacent side of lava, and nets to a total of 30fe/t when surrounded on 5 sides

**Comment by SirTwsted** [comment]
aaah ok, now that I did not know.  Thank you for that info.  its very appreciated. thanks :)

**Comment by pupnewfster** [comment]
We are not going to be adding a new type of coal as there is no real reason to do so and there are plenty of other mods that do so (though I am unsure if they are updated to 1.16 or not). In regards to the energy usage the heat generator is good for some passive generation, and also it primarily uses lava as a fuel, it can convert solid fuels based on the "burn time" of them and the "burn time" of a bucket of lava. This means that you need 12.5 charcoal for every 1,000 mB lava that gets created (which is used up pretty quickly), and also because it has an internal tank for this lava I believe it can store the entire stack of charcoal inside of itself as lava which may be part of the confusion about how fast it is "chewing" it up.
