### ISSUE TITLE
Advanced Solar Generator generates less power in deserts

### ISSUE THREAD

**Issue by DogTheBoss** [mekanism/Mekanism#6402]
#### Issue description:
According to the wiki, the Advanced Solar Generator should generate more power when in a desert, but it generates less.

#### Steps to reproduce:
1. Place an Advanced Solar Generator in a desert
2. Place another Advanced Solar Generator in a biome such as a forest at the same y-level as the other
3. Notice that the power output is lower for the desert generator

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.85
**Mekanism:** 10.0.3 (newer version patch notes do not mention this issue, so I am assuming it is not fixed)
**Other relevant version:** Minecraft 1.16.1

**Comment by pupnewfster** [comment]
This isn't a bug exactly, and is more so that the wiki is out of date. In late 1.12 we changed the logic of how solar generators generate power to more closely match real life (heat is bad for super conductors) https://github.com/mekanism/Mekanism/blob/1.16.x/src/generators/java/mekanism/generators/common/tile/TileEntitySolarGenerator.java#L60-L68
