### ISSUE TITLE
[1.16] Wrong item transport based on color coding

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#6419]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Logical transporters take color coded items to the wrong destination

#### Steps to reproduce:
1. See image below, chest on bottom has items, logistical transporter end set to blue on the left chest, logistical transported set to default (none) on the right chest
2. Logistical sorter set to *ingot* and color blue
3. Input iron ingot on bottom chest, items are set correctly by the logistical sorter to blue, but, the items go to the wrong chest.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.16.1-32.0.90-installer
**Mekanism:1.16...431

![image](https://user-images.githubusercontent.com/13665046/89213505-6e3a4a00-d582-11ea-96c5-9c6cf49989a4.png)

**Comment by pupnewfster** [comment]
This isn't really a bug, color isn't "prioritized" so they are both perfectly valid destinations (as no color is valid for colored items) and it just so happens the order the paths get checked to find the "shortest/cheapest" path has the one that is not colored go first. Your best options (in no particular order) would be to:
- Use a restrictive transporter on the path that you don't want colored stuff to take so that it has a lot "longer" of a score so is only taken if a match isn't found
- Make the path to the uncolored chest longer
- Color the path to the other chest and then have your sorter have a default color and auto mode on so it just outputs everything with the color unless it is outputting it with a filter.

**Comment by winsrp** [comment]
will give it a try, thanks for the input.
