### ISSUE TITLE
Textures missing/bugged (magenta + black squares)

### ISSUE THREAD

**Issue by Shimor1** [mekanism/Mekanism#6511]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
A lot of textures are missing/bugged, I tried reinstalling Forge, Makanism + Addons

EDIT : The textures are also bugged when placed on the ground

#### Steps to reproduce:
1. Install the lastest Forge and Mekanism Update for 1.16.1

#### Version:
**Forge:** 32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Other relevant version:** 1.16.1 Minecraft
![2020-08-28_14 14 37](https://user-images.githubusercontent.com/70377962/91560109-8f037e80-e939-11ea-9a54-79bc80b34550.png)

**Comment by Robball14** [comment]
So:
1) Before writing a report, check if someone else didn't report the same thing
2) delete optifine, it's the cause

**Comment by piousminion** [comment]
This is not an Optifine issue. This is Mekanism using unsupported rendering.  Don't just pass the buck.
https://github.com/sp614x/optifine/issues/457#issuecomment-304700367

However, a workaround is to install OptiForge [Curse Link](https://www.curseforge.com/minecraft/mc-mods/optiforge)
No more issues with that installed.

**Comment by ToMe25** [comment]
> This is not an Optifine issue. This is Mekanism using unsupported rendering. Don't just pass the buck.

I can't say for sure, but considering since 1.15+ alot of mods have issues like this with optifine, and not just because they do stupid unsupported stuff i would say: yes it probably is a optifine issue.
Also the bug report is way too old to be relevant, minecrafts rendering system got almost completely rewritten since then.
From what i have heard, the problem is that optifine isn't supporting one of forges model systems, thus causing problems with all mods using it, even if the other mod isn't doing anything wrong.

**Comment by pupnewfster** [comment]
This is an optifine issue, the thing you linked is from 2017 and doesn't even exist in Mekanism anymore... Optifine is causing custom model loaders to be registered after model loaders start loading.

**Comment by Shimor1** [comment]
> So:
> 
> 1. Before writing a report, check if someone else didn't report the same thing
> 2. delete optifine, it's the cause

1. I did check and found nothing.
2. Ty for being so precise, I managed to do it myself
