### ISSUE TITLE
Cardbox bug with refined storage

### ISSUE THREAD

**Issue by DyzKira** [mekanism/Mekanism#6514]
When I put the cardbox on a refinedstorage diskdrive my hard drives disappeared.
Mekanism version: Mekanism-1.15.2-9.10.9.422

**Comment by BentoGambin** [comment]
lol happened to me too (a few minutes ago) :( i will try to add the drives to the JEI bookmark on a backup and re-add them back to the current world)

**Comment by pupnewfster** [comment]
No idea why the refined storage diskdrive doesn't write its inventory to NBT when writing its tile, I recommend just adding the refined storage disk drive to one of the cardboard box blacklist tags.

**Comment by BentoGambin** [comment]
@DyzKira  It worked. If you move everything to a single disks, bookmark that disk on JEI on a backup (provided you have one), then copy the refinedstorage_disks.dat under the world/data/ to the recent save, then use cheat mode to grab the disk, it WILL keep the contents! Hope it helps.

**Comment by thelapisfox** [comment]
This also happens with Refined Storage crafters. I'm afraid to try it with my diamond crafter. Good thing I tested it first lol.

**Comment by pupnewfster** [comment]
Either blacklist it yourself or report it to refined storage so that they add to one of the forge domain blacklist tags anything they don't want mods picking up/moving... Tags are a wonderful thing and we aren't going to special case tons of mods for no reason just to have another mod break with said mod instead of letting the mod tell both mods at the same time it won't work.
