### ISSUE TITLE
Having trouble with Anchor upgrades not loading machines.

### ISSUE THREAD

**Issue by Ane5577** [mekanism/Mekanism#6520]
**Description:** 
I have a Digital Miner and Quantum Entangloporter in the same chunk, both with an anchor upgrade, and another Entangloporter back at my base to send power and receive the mined ores. While in the Miner chunk the system works properly, but when back at my base the Miner runs and receives power, but doesn't auto-eject.

**Steps to Reproduce:**
Miner Config - oreDict = *ore* ; eject = on ; pull = off ; silk = on ; 8 Energy Upgrades
Entangoloporter set only to move energy to the Miner and items back to the base and vice versa for the base-side

**Version:**
Minecraft: 1.15.2
Forge: 31.2.31
Mekanism: 9.10.9.422

I have, so far, been unable to find any logs pertinent to the issue.

**Comment by pupnewfster** [comment]
I am going to assume you mean a tag filter given the oredictionary doesn't exist in 1.15.2. My best guess is that 1.15 might have also had this issue: #6406 and the digital miner would load the wrong chunks so then it would be unable to mine due to the chunks not being properly loaded. Unfortunately there isn't much you can do except use another mod to chunk load the area as we are no longer developing for 1.15
