### ISSUE TITLE
[1.15.2] Push a chest connected with a transporter causes Crash

### ISSUE THREAD

**Issue by SampsonnZ** [mekanism/Mekanism#6533]
1. Place a Logistical Transporter beside a chest.
2. Use a Sticky Piston with Slime Block to push the chest.
3. Game crash

[crash-2020-09-07_21.53.36-server.txt](https://github.com/mekanism/Mekanism/files/5183447/crash-2020-09-07_21.53.36-server.txt)
![Screenshot](https://user-images.githubusercontent.com/9107855/92395890-acfd8a00-f156-11ea-8f2e-9834270ca8b9.jpg)

**Comment by ToMe25** [comment]
In vanilla you can't move tile entities(like chests) and mods adding that(like quark) are known to cause issues with alot of mods.
Not sure whether its possible to fix this on mekanisms end, but while it probably is it might not be worth the effort since moving tile entities will always cause alot of problems as long as its not vanilla.

**Comment by pupnewfster** [comment]
I don't think this has anything to do with Mekanism's end. My best guess is that quark is not properly invalidating the chest's capabilities when it moves it or it isn't properly getting rid of the tile.

**Comment by SampsonnZ** [comment]
The problem solved. I set the function which is called "Pistons Move Tile Entities" to false.
