### ISSUE TITLE
R.condensentrator energy upgrade

### ISSUE THREAD

**Issue by Way2Close2** [mekanism/Mekanism#6560]
Rotary condensentrator increases energy with each energy upgrade added.

#### Steps to reproduce:
1.Put 8/8 speed upgrades in a r.c
2.See "using" - 8 kfe/t
3.Add energy upgrades each adds more energy used per tick up to 51.2 kfe/t

Forge: 32.0.108
Mekanism:10.0.9.432

**Comment by pupnewfster** [comment]
I believe the rotary condensentrator is one of the machines that has an operation time of 1 tick, so what speed upgrades do is make it so that it can perform more operations in one tick. This has the side effect that if you don't have enough energy to run it at max speed it will just run at however fast your energy supply can support.

**Comment by Way2Close2** [comment]
Even with 2 creative energy cubes it doesn't pump out gas any faster or slower with the energy upgrades in and or out. It just uses nearly 6 times more power for no benefit.

**Comment by pupnewfster** [comment]
Ah so then there might be a bug in that it is basically operating for "free" when the energy upgrades are not installed.
