### ISSUE TITLE
Heat Generator wastes a massive amount of fuel.

### ISSUE THREAD

**Issue by ultranine** [mekanism/Mekanism#6593]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Earlier today, I was testing a modpack, and built a heat generator to replace another that was underperforming. I casually placed about half a stack of coal inside and left. Only a few seconds later, I heard every machine run out of power. I checked on the generator, and all of the coal was gone. Thinking I might of just had less coal than I realized, I decided to run a test in a creative world. After placing the generator and letting it process an entire stack of coal, it generated a measly 22,000 FE. That's not even enough to run a basic ore-processing setup for a minute. I'm not sure if this was intentional, but if not, could you fix it?
![2020-10-05_22 15 43](https://user-images.githubusercontent.com/72111292/95151386-90a23c80-0758-11eb-9689-9cb79efcd563.png)
Heat Generator after burning through 64 coal.

#### Steps to reproduce:
1. Attempt to power a heat generator using furnace fuel.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.0 
**Mekanism:** 1.16.3-10.0.9
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
The ratio that coal gets converted to lava is based on the burn time and how many items a piece of coal can smelt and how many items a bucket of lava can smelt in a furnace. It is intended to use lava inside the heat generator, though you have the option of using other solid fuels at ratios equivalent to what they are to lava.

**Comment by RadHazard** [comment]
I've run into the same issue, and I think there's more to the problem here than just the coal -> lava conversion.  It seems like the heat generator's active generation (even using lava directly) just massively underperforms other energy sources in general.

Some numbers (Tested just now using Mekanism 10.0.17 with the default config file):
- One full bucket of lava in a heat generator produces ~9860 Joules of energy
- In an energized smelter, that's not enough to finish smelting even 1 item.  If you add 8 efficiency upgrades, it can only smelt ~9.9 items per lava bucket (compared to the vanilla furnace's 100 items/lava bucket).
- A small solar generator produces ~40 J/t, which means it can generate a full lava-bucket's worth in 12.35 seconds
- Using that single lava bucket to heat the generator up passively instead of actively, it can generate ~73.68 J/t if you cover all sides with flowing lava.  That takes only 6.7 seconds to surpass the amount of energy you'd get from burning that lava directly in the generator.

As a side note, it seems there's no way to change how fast the generator consumes lava in the config file.  That means bumping up the energy content of lava to a more reasonable amount also has the side effect of making the generator produce a *lot* more energy per tick (with all the additional efficiency and heat dissipation changes that implies).  That probably needs looking at as well.
