### ISSUE TITLE
1.16.3 - Heat Generator and The One Probe crash

### ISSUE THREAD

**Issue by InverseRain** [mekanism/Mekanism#6603]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

I'm not sure this is really the right place to post this issue, since it involves another mod, but since it involves this one, too, I'm reporting it here as well. I've already reported it to the The One Probe devs.

#### Issue description:

Crouching and looking at a Heat Generator immediately crashes the game with The One Probe.

#### Steps to reproduce:
1. Look at Heat Generator
2. Crouch
3. Crash

or

1. Crouch
2. Look at Heat Generator
3. Crash 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.12
**Mekanism:** 10.0.10.434
**The One Probe:** 3.0.4-beta

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

**Crash Log:**
https://paste.ee/p/YjDZq

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
My suspicion is that this is not on our end (if McJtY thinks otherwise feel free to comment and I will reopen this), but I am not able to reproduce this crash and the log doesn't show any of our custom render stuff and seems to be entirely contained to TOPs code. (Though maybe some other mod that is installed is doing something weird in their custom handlers)
