### ISSUE TITLE
java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

### ISSUE THREAD

**Issue by Erdnussflip007** [mekanism/Mekanism#6619]
The game crashes while I am trying to start up minecraft.

If I remove mekanism, it just finds another "Registry Objekt not present", so mayby not a problem with mekanism, but am not sure.

[This](https://pastebin.ubuntu.com/p/MpXTKk3fyX/) is my log.

Sorry if I am missing something obvious.

**Comment by pupnewfster** [comment]
This isn't actually caused by mekanism (there was a forge bug that caused the wrong mod to get blamed for crashes), but thank you for providing your latest log instead of just a crash report as the crash report doesn't contain useful information and the latest log does. It seems that the crash is actually being caused by this:

```
[14Okt2020 17:31:29.181] [modloading-worker-8/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: randomenchants, class com.tfar.randomenchants.RandomEnchants
java.lang.NoClassDefFoundError: com/tfar/additionalevents/event/DropLootEvent
```

**Comment by Erdnussflip007** [comment]
Thank you very much for helping even though it's not an issue with your mod!
