### ISSUE TITLE
Multi-Tool Confusion

### ISSUE THREAD

**Issue by Malus-Lupo** [mekanism/Mekanism#6655]
I am confused, why does the multitool cost an atomic disassembler and configurator but has the functions of nether? Or am I missing something, I have tried every way to change mods for items I can find, and it seems to start off doing nothing but very slowly digging a single block.

**Comment by Oct0bass** [comment]
Press `\`.  Yeah the Meka Tool starts off pretty slow but it can get seriously powerful if you install more modules.

**Comment by Malus-Lupo** [comment]
I would suggest removing the atomic atomic disassembler and configurator, seems like a waist, you spend a lot of mats to make the tool, only to gain nothing and loss everything the ingredients can already do, only to then spend way way more mats to make it do those same things you just spent and more with even more mats.

**Comment by Oct0bass** [comment]
Did you try pressing the module config key?  Yeah the meka tools slow
without upgrades but its default setting are also very far from its highest
possible settings with what you've installed (in this case nothing).

**Comment by Malus-Lupo** [comment]
I did, there was no settings to be set by default.

**Comment by pupnewfster** [comment]
No. It is planned to probably eventually have the meka tool be able to be used as a configurator once we have a better system for multiple easy on the fly type changes. If you don't like the recipe feel free to change it (data packs and mods like crafttweaker exist). Just because a recipe contains something doesn't mean that it needs to be able to do everything the various components can/do... There are plenty of screws in a car but I hope you don't expect to be able to use a screwdriver to put a car in a wall. I also hope you are glad that water doesn't end up exploding on you just because it is made up of hydrogen/oxygen...

**Comment by Malus-Lupo** [comment]
I am sorry but your logic is very flawed, if you build a car out of 4 wheels and a engine, you expect it to drive, and while I do not disagree with the lesser components of the recipe, to make players waist there disassembler and configurator, and yes as it stands it is a complete waist tell much later in the game, you spend a LOT of effort to get your first polonium, to then make the tool do  pretty much what a set of iron tools can do, is silly to the point of absurdity after your car statement.
