### ISSUE TITLE
Possible power bug?

### ISSUE THREAD

**Issue by wagnerwj** [mekanism/Mekanism#6658]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Smelter and other ore processing machines do not seem to be pulling the correct amount of FE power.
I have an Elite Smelting Factory with one Energy upgrade- and it seems to be pulling the Same amount of power as a Basic Enrichment factory with one upgrade- both are reading needing 47.42 FE/t

Also, the factory tier increase doesn't seem to increase the power consumption- it has done so in the past.
#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: ** 1.16.1-32.0.108
**Mekanism: ** 1.16.1-10.0.9.432
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I am a bit confused what you are trying to report as the bug here. Is it *strictly* just that the different tier factories require the same amount of energy and are supposed to require different or is there something more going on here?

If that is all this bug report is about, as far as I know the different tiers never used more energy (just tested to confirm in 1.12), the only reason they might have seemed like they are doing so is because they can do more operations at once thus causing it to use a greater total amount of energy. The part where the tooltip shows the accurate total though is broken (and I will fix).
