### ISSUE TITLE
Nutritional Liquifier & Culinary Construct

### ISSUE THREAD

**Issue by Abexis** [mekanism/Mekanism#6659]
#### Issue description:
Sandwiches & Soups creates using the mod Culinary Constructs can be fed into the Nutritional Liquifier, but produce no nutritional paste.

Link to Culinary Constructs:
https://www.curseforge.com/minecraft/mc-mods/culinary-construct

#### Steps to reproduce:
1. Create any sandwich/soup in Culinary Constructs
2. Put said food item in the nutritional liquifier
3. No paste is produced

#### Version (make sure you are on the latest version before reporting):
**Forge:**  34.1.25
**Mekanism:** 10.0.15
**Culinary Constructs:** 4.0.0.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I fixed a couple things so now the nutritional liquifier shouldn't turn food items into paste if they provide no "healing" (hunger bars) which *should* fix the fact that it could consume sandwiches without producing any paste. Unfortunately because of how the food system is in MC for being tied to items there is no way for us to lookup the proper values as culinary construct uses NBT. I think to have it work they would need to submit a PR to forge to allow for stack sensitive food return and then we could add support and pass the stack to it, but for now there is nothing we can do on our end beyond just making it so that we don't consume them as they don't provide any stats.

**Comment by Abexis** [comment]
Thanks, Pup. That works for me :)
