### ISSUE TITLE
Upgrading logistical transporters can permanently break connections

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6660]
#### Issue description:
upgrading logistical transporters with items inside can result in weird behavior. 

#### Steps to reproduce:
too many steps. Made a video: https://gfycat.com/DentalSoulfulFlounder

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.25
**Mekanism:** 10.0.15

Nothing in the logs/debug logs.

**Comment by LionZ29** [comment]
I recommend playing in version 1.16.3, because in 1.16.1 I had many problems with the mod but in that version they are all corrected at least in my opinion

**Comment by pupnewfster** [comment]
The bug report is for 1.16.3....

**Comment by pupnewfster** [comment]
So there are actually a few bugs going on here, I fixed some of them including the one causing this issue (that the object references got lost so the transmitters still thought they had things in them). I still need to look some more into fixing the remaining bug which is that because the block is the same destination and it can't insert the iron into the extra slot it isn't sending any enriched redstone until the iron is no longer in the transporter because it thinks the slot is full. What should happen is ideally it would be able to send both at once instead of having to wait for the iron to finish reaching the destination to start sending the redstone.
