### ISSUE TITLE
Quantum Entangloporter do not work

### ISSUE THREAD

**Issue by xRaW2014** [mekanism/Mekanism#6665]
Despite all the correct input/output settings the quantum entangloporter randomly doesn’t input or output energy. I have 10+ currently setup on a network with them all working and now if I break and replace one of these they stop working and do not send/receive power.
I have a number of them setup on this network already so it definitely works just randomly stopped working for all new entangloporters.

I can only assume it could be an AE2 crafting issue as they were auto crafted and then since placing an auto crafted unit the rest no longer work when placed - NBT bug?

Mod pack is “Enigmatica 2”

**Comment by pupnewfster** [comment]
My best guess is if you have them on the same frequency that breaking one then changes the tick order of the blocks and another destination is using all the power you are providing. I also vaguely recall people mentioning quantum entangloporters don't properly transfer energy in 1.12 but no idea as none of those claims were made until after we stopped developing for 1.12 so I never looked into them as the system used has been rewritten since then.

**Comment by xRaW2014** [comment]
Hi There,

I do not have any Entangloporters within a different dimension. I've used
them for energy with no issues for a long time however after the first time
I used one autocrafted from an ME system it stopped working and every
place since then has not worked. Do you think it could be something to do
with the NBT data changing since autocrafting one? If i use ONLY ones
autocrafted from an ME will it mean that mean they have the same NBT data
and can connect once again or is there a way to clear it and start fresh so
to speak?

Kind regards,

Bertie

**Comment by pupnewfster** [comment]
The dimension shouldn't have anything to do with it frequencies are the thing you set in the GUI.
