### ISSUE TITLE
Solar neutron activator inserts into disconnected pipe

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6708]
#### Issue description:
In this image the polonium produced by the solar neutron activator is still flowing into the pipe. Despite me disconnecting it with the configurator. 
![image](https://user-images.githubusercontent.com/4283717/99152883-edbcd680-26a4-11eb-8198-38b751e4acbb.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.0.15
**Mekanism:** Mekanism-1.16.4-10.0.17.444

**Comment by pupnewfster** [comment]
Turns out this is a bigger issue than I initially thought, and has to do with it being based more on how we used to do capabilities/handlers in general. As it turns out, currently our transmitters (not just tubes, but pipes and probably others as well), even when set to none allow for force insertion, as they aren't currently looking at what side they are actually for (as we have one capability for all sides, but are calling it via a sideless method)
