### ISSUE TITLE
Mekanism Fusion Reactor

### ISSUE THREAD

**Issue by G4mer0815** [mekanism/Mekanism#6722]
I play in single player, and whenever I leave the world and enter it again.
The Fusion Reactor is no longer a multi block. Is it a bug?

**Comment by pupnewfster** [comment]
How about you actually provide useful information that we ask for like the version..?

**Comment by Seniorendi** [comment]
I do not have this issue with my 5x5 fission reactor :P

**Comment by G4mer0815** [comment]
So I play the modpack ATM 6 on version 1.16.3, Forge 34.1.25, and all
Mekanism Mods Version 10.0.15.441, I just don't know what else you need to know.
Single player World.

**Comment by pupnewfster** [comment]
By no longer a multiblock do you mean it is not formed at all or do you just mean that it deactivates? If it is just that it deactivates is it in one or multiple chunks or is the fuel supply in another chunk and potentially what happens is the reactor loads but then runs out of fuel and stops because the fuel supply isn't loaded/

**Comment by Zenodorus** [comment]
I have also been experiencing some instability with the formation of the fusion reactor multiblock in my single player survival world.  Specifically, two issues:

1. A correctly built reactor does not form and sparkle.  This seems to be dependent on which block was the last block to be placed.  I can build a reactor, and then go around to different random blocks, destroy and replace one at a time, and sometimes the reactor will form and sometimes not, roughly half the time.  One thing to note is that the use of Reactor Glass has some effect on this.  In a reactor that never uses glass, I can destroy and replace any block and it will always sparkle.  And I only use Reactor Glass on any of the five middle blocks of a non-bottom face.

2. If a reactor was successfully formed and sparkled, quitting and rejoining the world causes the game to have to decide again if it's a correctly built reactor.  If it decides that it is correct, then it will sparkle immediately upon rejoining the world.  Otherwise, it may decide it is not correct; the controller block won't light up and right clicking on it does nothing, even if you were just there with a formed reactor.  I don't know if these sparkles in this case is merely a visual bug or if this would have an impact on its operation (I haven't set up up the fuel lines and ignited it yet).  But I have sat here and quit and rejoined the world repeatedly to watch it turn on and off randomly.

I've tried to replicate this issue in a brand new creative world, but while I have seen the first issue rarely pop up, I have never seen the second issue happen.  Both issues happen all the time in my survival world.

Forge: 35.0.15
Mekanism: 10.0.17.444
Minecraft: 1.16.4

**Comment by G4mer0815** [comment]
Yes, I have exactly the same problem.

**Comment by C4J3** [comment]
Also confirming. Using Valhelsia 3 (pre5 on 1.16.3) with Mek 10.0.15.441 (all the modules).

Reactor will seemingly, at random, decide that it is no longer a valid configuration and deactivate the multiblock entity, I'm still setting them up in world so not sure if they'll do this while running but I can't see why they wouldn't. Right-clicking with a configurator doesn't say anything at all. Replacing random blocks sometimes fixes it, others I seem to need to break everything and rebuild it. Quite by chance both of mine are just within the same chunk (outer wall of one is in the last block space of said chunk) so that doesn't seem to be the issue.

As for the sparkle on joining, in my experience in 1.12 it seems that when a world is loaded any controller looks for valid blocks to form a reactor and does so if it finds them. This is done before it does anything else so it will stay running between world loads. 

I can try and get the server logs if that will help?

**Comment by m0V1NGt4RG3T** [comment]
Similar issue Direwolf20 1.16 pack update 1.8.0 Mekanism 1.16.5-10.0.21.488
successfully built fission multiblock it formed and was working for an extended period of time.
I removed one of the input ports to re-reroute fueling, (removed 1 glass and 1 input) swapped the two blocks and now it wont reform. 
I have tried swapping the 2 moved blocks back, as well as removing/replacing other blocks, restarting the server. 
I have not tried  rebuilding the entire structure. though i can build new, break, reform other mek multiblocks.
