### ISSUE TITLE
Ignition of the fusion reactor in creative

### ISSUE THREAD

**Issue by SimplisticGH** [mekanism/Mekanism#6725]
**Describe the feature you'd like**

I like to test fusion reactor designs in creative, but waiting 30 minutes each time for the lasers to refill the amplifier is annoying.
Could you add a creative amplifier to instantly ignite the reactor?*

**Comment by pupnewfster** [comment]
I believe aidan actually implemented this in V10 because he was getting annoyed at testing. Right clicking a laser focus matrix that is part of a formed fusion reactor should ignite it (I forget if you still need to have filled hohlraum in the controller or not, but you can get that from creative easily)
