### ISSUE TITLE
Superheating element

### ISSUE THREAD

**Issue by MushuPlatypus** [mekanism/Mekanism#6726]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Superheating element doesn't work with the fired crucible from ExNihiloSequentia

#### Steps to reproduce:
1. Place a superheating element with a fired curicble on top
2. Put cobblestone into the crucible
3. Heat says 0

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.41
**Mekanism:** Mekanism-1.16.4-10.0.17.444
**Other relevant version:** exnihilosequentia-1.16-1.3.0.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This has nothing to do with Mekanism, the superheating element is part of the boiler multiblock and outside of the boiler would do next to nothing as it basically would just be a coil of metal (which isn't going to produce any substantial amount of heat just by existing, it would be around room temperature. https://en.wikipedia.org/wiki/Superheater

Now, while googling to briefly validate how super heaters work... because google did have an auto fill for "crucible", I searched it and my best guess for why you think this is a bug is due to this [site](https://ex-nihilo-minecraft.fandom.com/wiki/Crucible). My best guess is that for some reason (even though it is very illogical) the original ex nihilo might have added a heat value to our super heating elements as compat, as far as I am aware that compat was never on Mekanism's end (as it makes no sense) for the superheating element to give off heat when it is by itself... If you want this absurd compat back I suggest you take it up with whoever is maintaining ExNihiloSequentia, but we are not going to be adding this to Mekanism.

**Comment by MushuPlatypus** [comment]
Ahh sorry,  I've just come from playing Stoneblock 2 where that worked.  Sorry to bother you.
