### ISSUE TITLE
Universal Cable doesn't connected with machines

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#6728]
#### Issue description:
When I connectting the universal cable (`in my case is BASIC TIER`) it doesn't connected with Electrical Pump. It also happend with some machines from `Immersive Engineering`. Even more I am also try using Immersive Engineering wire, the pump still can not connect with the pump.

But it can still connect with AE2 inscriber

#### Steps to reproduce:
Follow the description

#### Version (make sure you are on the latest version before reporting):
**Forge:** `34.1.42`
**Mekanism:** `10.0.17`
**Other relevant version:** 
  _Immersive Engineering :_ `1.16.3 - 4.1.1 - 127` 
 _Immersive Petroleum_ : `3.0.0`
_Applied Energistics 2_ : `8.1.0`

#### Images
![2020-11-21_15 58 36](https://user-images.githubusercontent.com/68932626/99872400-249a6b80-2c14-11eb-9028-81491da3f8dc.png)
![2020-11-21_16 04 17](https://user-images.githubusercontent.com/68932626/99872405-29f7b600-2c14-11eb-841d-5da1b4f495fb.png)

**Comment by Robball14** [comment]
the port above is the water output of the elctric pump
the side port is the energy input

**Comment by KhanhPham05** [comment]
but the problem is it NOT connect with the IE's Metal Press

**Comment by pupnewfster** [comment]
I am confused what is going on here? IS the issue you can't figure out how to power your electric pump? If so do what robball said and connect it to the green port you currently have the logistical transporters connected to. If the issue is you can't connect our energy cables to IE's metal press why are you including pictures of trying to connect to the electric pump?
