### ISSUE TITLE
teleportal not bring me to the other one

### ISSUE THREAD

**Issue by Noahfrechette** [mekanism/Mekanism#6732]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
when i go through the portal and i go through again it does not bring me to the other one and they are linked

#### Steps to reproduce:
1. join world
2. go through in the portal
3. go in the protal and does not let me go to the other portal

#### Version (make sure you are on the latest version before reporting):
**Forge:** newest version that sky factory 4 is using
**Mekanism:** newest one on sky factory 4
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Noahfrechette** [comment]
fixed it i have to leave the portal 5 times

**Comment by pupnewfster** [comment]
My best guess is that the issue is either:
a. you don't have enough power in the teleporter to teleport
b. the destination teleporter is not chunk loaded.

If neither of these is the case and it still happens in 1.16 feel free to comment and I can try to look into it further, but we are no longer actively developing for 1.12
