### ISSUE TITLE
Question: converting liquids to gasses using an ER Reactor

### ISSUE THREAD

**Issue by ZeroNoRyouki** [mekanism/Mekanism#6741]
Hi there, a question for you guys.

I was asked today why you could not extract Stream in gas form from an Extreme Reactors Reactor to pump it in a Mekanism Turbine and my answer was basically something like "because I don't know how much that would piss the Mek guys off" 

While coding ER for 1.16.3 I had made plans to do so and code it's already in place to do so but then I realized that you have 3 or 4 way in your mod to produce gaseous steam an so I've put it on hold. There is also the fact that an ER Reactor can produce any kind of liquid a mod register using my API so I would also need to add a conversion layer from liquid to gas to the API too, with it's own batch of balancing problems.

So, would this piss you guys off? :)

**Comment by pupnewfster** [comment]
I don't really have a problem with devs if they want to do some sort of implicit conversion type of thing, though you probably should include a config option for pack devs to be able to turn the feature off.

Personally if I was you or trying to make a system like this I would try to somehow hook into the rotary condensentrator's recipes (not sure how easy that is to do from an external mod tbh so may not be worth it, though you can probably get a list of [rotary recipes](https://github.com/mekanism/Mekanism/blob/1.16.x/src/api/java/mekanism/api/recipes/RotaryRecipe.java) from MC's recipe manager by the registry name of the rotary recipe type), just because then if a pack dev decides to change conversion ratios from the fluid and gas variants they are able to easily. For example our steam conversion recipe: https://github.com/mekanism/Mekanism/blob/1.16.x/src/datagen/generated/mekanism/data/mekanism/recipes/rotary/steam.json

Granted I have no idea how much steam you guys produce compared to us so balance wise things may be entirely off, but personally my take on balance between mods is that it is up to the pack dev to balance it how they want, and all the mod devs need to do is provide a way for the pack devs to do so.

**Comment by ZeroNoRyouki** [comment]
Got it, and thank you for the suggestion, I'll look into it

**Comment by ZeroNoRyouki** [comment]
Hi, just to let you guys know that I've implemented the fluid->gas conversion in my last release and that's it's tied to your rotary recipes so we should have any bad surprises
