### ISSUE TITLE
Mekanism-1.15.2-9.10.9.422, lycanitesmobs-1.15.2-2.2.3.2 and minecolonies-0.13.469-ALPHA-universal issue

### ISSUE THREAD

**Issue by FractalizeR** [mekanism/Mekanism#6752]
I'm using a custom modpack, which uses mekanism, lycanites and Minecolonies of mentioned versions. Until I built a colony, everything went fine - digital miner extracted ores without any problem. But as soon as I claimed a colony at the place, where my miner was, it stopped gathering ore and many mobs begain spawning under the ground instead (`/kill` showed around 3 thousand entities). I think this problem was caused by lycanites setting to spawn a mob when breaking ore.

I moved miner away and all went fine.

**Comment by pupnewfster** [comment]
A few things are going on here:
1. In 1.15 (we have improved compat since in 1.16), because the miner respects minecolonies land protection, you either need to add the `[Mekanism]` player to your colony or disable colony protection in the minecolonies config.
2. That sounds like a bug in lycanites that it doesn't check if the ore was actually broken given we *try* to break the block, but minecolonies cancels it so the block never gets broken.

**Comment by FractalizeR** [comment]
Thanks for an answer!

But is it a bug, that ore breaking not by player, but by the machine spawns lycanites? Spawned as such, they can not be easily located and killed, clutter chunks, slow down and then kill server. Should I file lycanites bug?

**Comment by pupnewfster** [comment]
You probably should file a bug with lycanites because at the very least they should be checking if the event is canceled, even if they want to allow them to spawn when broken by a fakeplayer.
