### ISSUE TITLE
Fission Reactor stops being recognized as a valid multiblock if Structural Glass is placed at certain points outside it

### ISSUE THREAD

**Issue by kkjdroid** [mekanism/Mekanism#6759]
#### Issue description:
Video of the issue: https://www.youtube.com/watch?v=OrO_rUZxbrg

#### Steps to reproduce:
1. Build a reactor multiblock
2. Place Structural Glass (e.g. for a turbine) adjacent to the reactor in certain positions
3. Reactor is no longer recognized as a valid multiblock

Note that Turbine Casing does not cause this problem.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.23
**Mekanism:** 1.16.3-10.0.12.437
**Other relevant version:**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

I don't think it's relevant, because I don't have debug logging on and there's no crash, but just in case:

[paste.ee](https://paste.ee/p/3q2vE)

**Comment by pupnewfster** [comment]
I am interested to see if you are able to reproduce this in 10.0.18 as it seemed very inconsistent for me in 10.0.17 (though I was able to reproduce it sometimes), and I think it might be fixed in 10.0.18 but it also could just be pure chance I didn't run into it anymore, or it could be related to the changes/fixes I did to the multiblock system.
