### ISSUE TITLE
Extremely fast fluid pipe for reactor?

### ISSUE THREAD

**Issue by Azruine** [mekanism/Mekanism#6773]
Fusion reactor running at full injection ratio can emit 14.7MmB/t, and ult mechanical pipe can only pump 64KmB/t AFAIK

It means 230 ult mechanical pipes required for full speed fusion reactor only for pumping. What a mess...

And transport limitation is 512KmB/t so 28 input port required.

Pipes using energy to enhance pulling/transport ratio would be very good.

Maybe consuming 1RF for additional 1000mB ratio?

**Comment by pupnewfster** [comment]
Just auto eject into the pipe network... https://wiki.aidancbrady.com/wiki/Throughput

**Comment by Azruine** [comment]
Throughput of ult mechanical pipe is 512000mB/t, right? This is still insufficient for 14.7MmB/t...

If I'm wrong, please let me know. I'm short english, so there might be something I missed

**Comment by pupnewfster** [comment]
Not fully sure, given a few things:
1. Assuming you are talking about steam, I believe fusion can't get that high without using a boiler in between just because of the size of the tank, but even so, steam can be transferred in pressurized tubes which has a higher rate.
2. If you mean for the water return, it might be high though you could also always put the structures right next to each other so that the ports output directly into the other ports removing the limit of the pipes from the equation.
3. If you need even higher you can go ahead and change the config values to make them go at higher rates.
