### ISSUE TITLE
Meka-Tool: the power consumption of excavation speed mods and vein mining mods are multiplied together, draining the tool instantly at max setting of both

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [mekanism/Mekanism#6786]
#### Issue description:
If you install 4 vein mining units and 4 excavation escalation units and use them both together at the same time, the power usage of both will be multiplied, as if each block broken by vein mining was broken with 128 efficiency.

#### Steps to reproduce:
1. Obtain a meka-tool
2. Upgrade with vein mining and excavation escalation units
3. Set both to max values
4. Break stone
5. Observe how Meka-Tool is drained of charge instantly

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.3 - 34.1.42 ** 
**Mekanism: 10.0.17.444 ** 
**Other relevant version: Valhesia 3 modpack** 

It doesn't appear like there have been any relevant pull requests addressing this issue so even though it's not the latest version, I will assume this issue is also present in current version.

**Comment by pupnewfster** [comment]
I can confirm this is the case, but putting this on hold for now until I have a chance to talk further with aidan as I am unsure from a balance perspective how we want to handle the energy usage. I agree that it may not make sense to use the full speed's increased cost but I am not sure if something in between may make more sense.

**Comment by szikra** [comment]
I guess lower energy consumption is always nice, but I don't see a problem with maxed out (speed, vein mining) Meka-tool being a late game item which should be equipped with 8 Energy Unit (and backed up with a good power generator back home).

I tested it out with max settings and after ore mining a while I still had 3 GJ in it.

At least I can drain some of the 11.35 TJ sitting in my induction matrix that is hooked up to a fusion reactor. :)
(Though after writing these lines the reactor - even on the lowest injection rate - generated more power than I used and now I have 11.37 TJ, so draining it with meka-tool might not work out ;)

It only took a couple of seconds to charge it up in the induction port, so balance wise it seems fine to me.
...although, I tried to charge up my Meka-tool in an Ultimate Energy Cube attached to a Quantum Entangloporter and it was really slow. I tried to use the Chargepad, but it didn't seem any faster.
This is not a problem for me, because I can use Waypoints to tp back and fast charge it, but I can see this maybe being an issue for some.
Not sure what is the proper mobile charging method, or if it is intentionally slow. Am I missing a portable charging option?

Did some more testing, it took around 5 minute desert mining (10k sand+20k sandstone) to empty out 4GJ, so there is some room for efficiency improvement (especially if it takes as much or more time to charge it than it takes to use it).

If higher efficiency is desired maybe there is an opportunity here to make a new Energy Efficiency Unit instead of just changing the energy usage/speed formula. (And maybe adding speed/energy upgrade to the charge pad.)
