### ISSUE TITLE
Documentation for build process

### ISSUE THREAD

**Issue by sirati97** [mekanism/Mekanism#6790]
I tried [building ](https://github.com/mekanism/Mekanism/commit/32f627309851a9d08f06f9552043911d5cf2764e#commitcomment-45224879)the 1.15.x branch. I used fullBuild task (also tried many other sensible sounding tasks) but i did not end up with jars being spit out that work without manual patching of some stuff.  I got it working for me now, but this should be documented, even if its just one line.

**Comment by pupnewfster** [comment]
It is the same as the vast majority of other mods running the gradle `build` task should work fine. I will leave this open *for* now, given I can add a line to https://github.com/mekanism/Mekanism/blob/1.16.x/docs/Development.md that says this, but my best guess for why the 1.15 branch didn't build is that cursemaven changed the syntax it uses (due to curseforge's API changing) since we last updated the 1.15 branch (as we are no longer developing for it), so you probably couldn't find the dependencies that you need to compile it.

**Comment by sirati97** [comment]
cursemaven task did not throw any exceptions for me either tho
