### ISSUE TITLE
HUD isnt showing up for the mekasuit

### ISSUE THREAD

**Issue by zachyaboyy** [mekanism/Mekanism#6800]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
no matter what I press, the HUD isn't showing up. all that appears is a flat player model in the top left, but I don't think that's the HUD as I can't toggle it and it only appears in survival. this could be on my side, or I'm doing something wrong. if I'm doing something wrong, what am I supposed to do? i have a lot of other mods, but even if I turned all other HUDs or similar it still didn't appear. i can send a list of mods if needed. 

#### Steps to reproduce:
1. I am unsure, as it may be only on my side, or something else. I had all the mekasuit pieces with all upgrades
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.16.4-35.1.13
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I am not able to reproduce this with just Mekanism, my best guess is it is because another mod you have installed is also listening to the `RenderGameOverlayEvent` and just straight up cancelling it regardless of if their HUD is active or not. Personally I don't see many cases when the event should be cancelled in general instead of just used to *add* extra things to it, but as it stands there is nothing we can do on our end to fix or work around another mod cancelling the event.
