### ISSUE TITLE
solar neutron activator doesnt work in AllTheModium mining dimension 

### ISSUE THREAD

**Issue by D3s0l4ti0n** [mekanism/Mekanism#6801]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
placed solar neutron activator down doesn't register sunlight even thou its always day 

#### Steps to reproduce:
1.place activator
2.doesnt process gasses accepts them thou
3.its always day in AllTheModium mining dimension 

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.16.4-35.1.13
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Take it up with them: https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/tile/machine/TileEntitySolarNeutronActivator.java#L154 is how we check if a dimension has daylight, my best guess is that they don't define the dimension as having skylight.

**Comment by thevortex** [comment]
so here is the json file that we are using to create the dimension via datapack

++++++++++++++++++++++

{

  "name": "allthemodium:mining",
  "type": "allthemodium:mining",
  "ultrawarm": false,
  "natural": false,
  "fixed_time": 9000,
  "shrunk": false,
  "piglin_safe": true,
  "respawn_anchor_works": false,
  "bed_works": true,
  "has_raids": false,
  "has_skylight": true,
  "has_ceiling": false,
  "ambient_light": 0.75,
  "logical_height": 256,
  "infiniburn": "minecraft:infiniburn_overworld",
  "coordinate_scale": 1
}


what can we do to make sure your code is able to see that we have daylight, no ceiling, and a skylight?

**Comment by pupnewfster** [comment]
Hmm looking at it a bit closer I think it may have to do with isDaytime checking to make sure the time is *not* fixed, though I am not sure why. I will re-open this for now so that I can remember to look into it more if there is some other way I can do it now or if I will have to add special compat code for fixed time dimensions.

**Comment by FinnKr** [comment]
It's the same thing for the 'Void'-Dimension from 'Just Another Void Dim'.

**Comment by Kippenhof** [comment]
Hey There, I have the Same Issue. Is there some Resolution in sight, or some work around?

**Comment by pupnewfster** [comment]
Currently no, but I also haven't looked into this at all yet, I have been focusing on finishing up porting another mod that I neglected for 6-7 months because of focusing on Mekanism. Though on the bright side I am almost done with that, just a couple more things I want to look into/potentially rewrite for it, and then I am going to be switching back to focusing on Mekanism, though initially it likely will be me more focusing on some forge PRs I need to write/update for a few different things related to Mekanism.

**Comment by NeonWizard** [comment]
What's the latest on this? I built out an entire nuclear reactor setup in the Compact Machines dimension before realizing I have no way of pumping out the nuclear waste and no way to process it with a solar neutron activator on-site.

**Comment by astra1323** [comment]
> What's the latest on this? I built out an entire nuclear reactor setup in the Compact Machines dimension before realizing I have no way of pumping out the nuclear waste and no way to process it with a solar neutron activator on-site.

Assuming you're using ATM 10 or another pack with AE2 and Mega Cells, you could use a MEGA Radioactive Chemical Storage Cell in an ME system with a quantum ring linked to a quantum ring in the overworld that exports the waste to process it.
