### ISSUE TITLE
why am i able to get "liquid steam" when im condensing steam, isnt that just water? (question)

### ISSUE THREAD

**Issue by zachyaboyy** [mekanism/Mekanism#6810]
**Describe the the feature you'd like**
A clear and concise description of what you want.
its in the title, there's prob a reason for it, id just like to know it
**Describe alternatives you've considered**

**Additional context**

**Comment by zachyaboyy** [comment]
wait huh how did i add a label did i misclick something somewhere

**Comment by pupnewfster** [comment]
The issue format you chose is for enhancements so it auto added the label. And liquid steam is just a forge fluid variant of steam for cross compat with other mods. It is named liquid steam because of the annoyance that is how no mods really care about the gaseous tag in forge's fluid system so for all extents and purposes it is a liquid system more than a fluid one in my opinion.

**Comment by zachyaboyy** [comment]
ahh ok. how do i turn steam or liquid steam into water then?

**Comment by pupnewfster** [comment]
You turn steam into water by putting saturating condensers in your turbine and connecting pipes to the vents after putting steam in through the valves
