### ISSUE TITLE
Basic mechanical pipe pulling from blood altar crashes game

### ISSUE THREAD

**Issue by danbalarin** [mekanism/Mekanism#6826]
#### Issue description:

When mechanical pipe is set to pull from [blood magic altar](https://ftb.gamepedia.com/Blood_Altar) the game instantly crashes (singleplayer and multiplayer server) and then crashes every time the chunk is loaded.

#### Steps to reproduce:
1. Place mechanical pipe next to blood altar
2. Set the pipe to suck from altar
3. Watch game crash

#### Version (make sure you are on the latest version before reporting):
**Forge: 35.1.13** 
**Mekanism: 10.0.18.445** 
**Other relevant version: Enigmatica 6 Modpack** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Crash report:
https://pastebin.com/Ha8YEpL0

**Comment by pupnewfster** [comment]
Not mekanism, blood magic isn't implementing capabilities properly: https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/tile/TileAltar.java#L229

**Comment by danbalarin** [comment]
As far as I can see, the problem is caused by Mekanism. Blood magic may not implement something like they are supposed to, but every external facing interface should be at-least null checked. Blood magic may fix it, but then some other mod creator may do the same mistake and the _world destroying_ bug will be back...

**Comment by pupnewfster** [comment]
That isn't what the issue is at all, my first thought was that it is because the capability is not implemented properly and is thus erroring because it is invalid and doesn't say it is no longer valid. Upon closer inspection it is because Blood magic is still using the 1.12 way of handling fluids and returning [null](https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/altar/BloodAltar.java#L714) from a NONNULL method. I am not going to add null checks in every possible spot just because a mod *might* return null from a nonnull method.
