### ISSUE TITLE
Can't build some machines.

### ISSUE THREAD

**Issue by Bergtorp** [mekanism/Mekanism#6833]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Trying to build some ore processing tier 4 machines. I put in all the materials according to the official wiki, but I don't get a machine to create. Tried to make Chemical Washer and Chemical Crystalizer. This is on survival mode, and in creative mode I can take out an allready made machine of these, but I can't make it from scratch with a workbench.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.18
**Mekanism:** 10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are you using JEI or the recipes on the wiki, given if memory serves some of the recipes changed and I don't believe the wiki reflects those changes currently.

**Comment by Bergtorp** [comment]
I don't have the JEI mod. Saw another recipe for on a wiki the replaced the bucket with a bucket filled with water, didn't work. Even seen a couple of Youtube vids which showed the same recipe that doesn't work for me.

The recipes I've tried for Chemical Washer:
Basic Control Circuit - Bucket (with/without water) - Basic Control Circuit
Enriched Alloy - Steel Casing - Enriched Alloy
Basic Control Circuit - Basic Gas Tank - Basic Control Circuit

And for Chemical Crystalizer:
Basic Control Circuit - Basic Gas Tank - Basic Control Circuit
Atomic Alloy - Steel Casing - Atomic Alloy
Basic Control Circuit - Basic Gas Tank - Basic Control Circuit

**Comment by pupnewfster** [comment]
As I said some of the recipes changed in V10, I highly recommend you install [JEI](https://www.curseforge.com/minecraft/mc-mods/jei), given even while Mekanism doesn't *require* it, personally I consider JEI essential in a modded environment just due to how many recipes exist.

Chemical washer:
![image](https://user-images.githubusercontent.com/1203288/103420052-8929de00-4b63-11eb-906b-ad1504a8d17e.png)

Chemical Crystallizer:
![image](https://user-images.githubusercontent.com/1203288/103420063-92b34600-4b63-11eb-9ffa-c699e9077827.png)

**Comment by Bergtorp** [comment]
Great! Thanks! Super quick and good help. 5 stars.
