### ISSUE TITLE
Digital Miner - Itemstack drag and drop from JEI

### ISSUE THREAD

**Issue by koalalord9999** [mekanism/Mekanism#6882]
**Describe the the feature you'd like**
I would like to be able to drag and drop a specific block from JEI to the Itemstack slot, without having to obtain the item before I tell my digital miner I want it to mine this item.

**Describe alternatives you've considered**
Obviously collecting the item fixes this issue, but that is why this is a feature request.

**Additional context**
![image](https://user-images.githubusercontent.com/9123026/104559444-02b4d800-560a-11eb-81d6-130286ee2551.png)

**Comment by Robball14** [comment]
You can already do this, the feature only got disabled for the digital miner on purpose so people will do a little of exploration

**Comment by pupnewfster** [comment]
This is intended that it doesn't work for that slot.

**Comment by Seniorendi** [comment]
Or just use the tag.

**Comment by Mooncat25** [comment]
May I make a comment to disagree the decision of closing this issue?

In my humble opinion, and as Seniorendi said, with the Tag option we can already find 99% of the things (ores) we need in order to make progress. It already defeats the purpose of encouraging people to explore. But of course we can't remove such option or setting the configs will be too troublesome.

Most of the time we need to mine a specific block because we want to use it as build material. And building blocks mostly don't have tag. So, adding JEI drag-and-drop support to that slot will mostly benefit builders. It has nearly no effect to the actual game progression, and therefore, I sincerely hope that you can reconsider this decision.
