### ISSUE TITLE
Energy upgrade not working

### ISSUE THREAD

**Issue by Mirutus** [mekanism/Mekanism#6885]
#### Issue description:
The energy upgrades don't decrease the energy usage, they increase it.
I have mentioned this issue while producing D-T Fuel.
The machines where this happens:

- Rotary Condensentrator (for Lithium-Gas, uses 51.2 kFE/t)
- Electrolytic Separator (for Deuterium)
- Chemical Infuser (for D-T Fuel, uses 256 kFE/t, without energy upgrades: 32 kFE/t)

#### Version:
**Forge:** 1.16.4  35.1.13
**Mekanism:** 10.0.18.445

**Comment by pupnewfster** [comment]
Copying this QA from our FAQ on discord:
> **Q:** *Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?*
**A:** Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the *exception* that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.

Expanding on that for the electrolytic separator in particular, neither speed upgrades or energy upgrades actually change how much energy is required ***per operation***, though speed upgrades will seem to increase it because of more operations taking place per tick.

**Comment by Mig979** [comment]
@pupnewfster does this mean that energy upgrades on electrolytic separator only increase the energy capacity of the machine? I'm a bit confused as these are used to make every other machine more power efficient.

**Comment by pupnewfster** [comment]
That is correct, but speed upgrades also make almost every other machine consume more power as well... In the electrolytic separator they don't. Upgrades behave slightly differently from machine to machine, yes some types of machines have the upgrades applied in the same way, but there are a decent number where it is subtly different.

**Comment by Mig979** [comment]
Cool, thanks for the clarification.
