### ISSUE TITLE
Crash when interacting with a personal chest.

### ISSUE THREAD

**Issue by Eztex** [mekanism/Mekanism#6913]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash on interaction

#### Steps to reproduce:
1.Right Click Personal chest
2.
3.

**Forge:** 35.1.16
**Mekanism:** 445
**Other relevant version:** 

https://mcpaste.io/5a579ec2df8ce494

**Comment by pupnewfster** [comment]
As best as I can tell based on @sunshinehunter's debugging https://github.com/mekanism/Mekanism/issues/6926#issuecomment-768794067 the bug is due to optifine, I adjusted things a bit for 10.0.20 that should in theory at least let it fallback to the default colors in the GUI instead of crashing because optifine somehow broke us being able to read the resource pack. Not quite sure when 10.0.20 will be released yet though as there are still a good number of other things I want to work on fixing.
