### ISSUE TITLE
Crash when opening a machine GUI

### ISSUE THREAD

**Issue by sunshinehunter** [mekanism/Mekanism#6926]
[Link to crash log](https://paste.ee/p/Sgkke)
[Exception thrown before this crash report gets created](https://pastebin.com/XNFzsaY0)

This happens when opening the GUI of an Enrichment Chamber or Crusher, but it might happen with more or all of Mekanism's machines. For some reason it also doesn't happen every time I start Minecraft, so it kinda becomes a dice roll whether I can use a machine that session. Note that I use Optifine, which could be an issue; I will try it tomorrow without Optifine enabled.

**Comment by pupnewfster** [comment]
Going to merge this with issue with #6913 as the stack trace seems to be rather similar so I think it is the same issue in both cases, though I am still interested to hear if it happens without optifine as I wouldn't be surprised if optifine is somehow breaking the events we use to load data from the resource pack, in which case I probably can at the very least add fallback code so that it doesn't crash and instead resource packs just won't be able to change some aspects of our GUIs.

**Comment by sunshinehunter** [comment]
I started the game a few times without Optifine so far, and I didn't experience any crashes so far.

Me and the other person with the similar crash report both have an AMD GPU and don't use Windows, maybe it's connected with that? A fallback for this would still be appreciated, Optifine helps me a bunch on ATM6 for higher frame rates and render distances.
