### ISSUE TITLE
Personal Chest disappearing

### ISSUE THREAD

**Issue by robschmok** [mekanism/Mekanism#6959]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Personal Chest disappeared two times while in inventory (wasn't placed in world).

#### Steps to reproduce:
1. Use Personal Chest (couldn't find specific causality)
2. 
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 35.1.36
**Mekanism: 10.0.18
**Other relevant version: Direwolf20 Modpack version 1.5.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This isn't really enough information to go on especially given while it is just in your inventory it is just like any other item so if I had to guess some mod is screwing with the player inventory and causing items to randomly disappear from it or something. I think you are better off reporting this to the pack devs (https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues) and seeing if they can track down what the issue/cause is as I highly believe it is probably due to another mod in the pack.
