### ISSUE TITLE
Chemical Injection salt efficiency

### ISSUE THREAD

**Issue by Vinlaell** [mekanism/Mekanism#6962]
Hello i'm on 1.16.4-forge-35.1.15 and using a chemical infuser with gas upgrades and speed upgrades uses a whole stack of salt to complete one shard but when i remove the speed upgrades it uses about 20 mb hydrogen chloride and the info says that using speed upgrades should increase efficiency of gases but im seeing the opposite

**Comment by pupnewfster** [comment]
Gas upgrades increase efficiency, speed upgrades just increase the speed of machinery and in the cases of gas using machines especially where the gas is a secondary input for the most part they increase the cost of usage. In general you are probably better off setting up a system to create the chemicals rather than using direct item to chemical conversions as often the item to chemical conversions can't keep up/aren't as easily expandable.
