### ISSUE TITLE
Cannot use personal chest whilst looking at a non-interactable block

### ISSUE THREAD

**Issue by ChloeDawn** [mekanism/Mekanism#6992]
#### Issue description:
Personal chests cannot be bound or opened in-hand whilst the user is looking at a non-interactable block.

#### Steps to reproduce:
1. Hold a personal chest in the main or off-hand
2. Use it whilst looking at a grass block or other non-interactable block
3. Nothing happens (does not set owner if unowned, does not open menu if owned)

#### Version:
**Forge:** 1.16.5-36.0.31
**Mekanism:** 1.16.5-10.0.20.447

**Comment by pupnewfster** [comment]
This is sort of intended in that we changed it so that you have to sneak to place the personal chest, but I will look into if it is possible to make it so that you can open it when right clicking something other than air if it doesn't have anything happen. Not sure if I will be able to as I don't remember if items or blocks get used first, so might need more thought on if I want non sneak right clicking to just always open the GUI.
