### ISSUE TITLE
Bronze is bugged

### ISSUE THREAD

**Issue by Jordan231111** [mekanism/Mekanism#7010]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. download forge and install latest version of mekanism 
2. Make a metallurgic infuser and put tin in and at least 3 copper ingots
3. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
What version are you on/using?

**Comment by Robball14** [comment]
went to test myself

- Forge: 36.0.21 Meka: 10.0.20. Still possible to make bronze
- Forge: 36.0.39 Meka: 10.0.21. Still possible to make bronze
- Forge: 36.0.41 Meka: 10.0.21. Still possible to make bronze
- Forge: 36.0.42 Meka: 10.0.20. Still possible to make bronze

Whatever is blocking him from making bronze, i doubt it is because of Mekanism or Forge
