### ISSUE TITLE
Gliched gui and none soud in the supercritical phase shifter

### ISSUE THREAD

**Issue by Appdato** [mekanism/Mekanism#7016]
#### Issue description:
If you use SPS casing in the borthers of one corner of the supercritical phase shifter the build won't make any sound and the gui will show double the storage it can store

#### Steps to reproduce:
1.Build a supercritical phase shifter
2.Place 3 blocks in one corner

#### Version :
Forge-36.0.42
Mekanism-1.16.5-10.0.21.448
![bugv2-1](https://user-images.githubusercontent.com/78976559/108732956-5500e700-752e-11eb-90dc-b0d8cb824015.png)
![bugv2-2](https://user-images.githubusercontent.com/78976559/108732965-57634100-752e-11eb-9d9f-043c21784507.png)
![bugv2-3](https://user-images.githubusercontent.com/78976559/108732975-592d0480-752e-11eb-8218-3862283e7e7b.png)
![bugv2-4](https://user-images.githubusercontent.com/78976559/108732978-59c59b00-752e-11eb-9f37-cdaa4e2d8b99.png)
![bugv2-5](https://user-images.githubusercontent.com/78976559/108732988-5b8f5e80-752e-11eb-9cf8-de7579fffa65.png)

**Comment by pupnewfster** [comment]
I am able to reproduce the fact that when placing an extra block the sound seems to just stop, but I am not able to reproduce the issue that you mention for the GUI (and I think your GUI may be correct in that it should be 2,000 mB input, which given your process rate is at 1.0 mB/t seems like you have 1,000 mB stored/constantly being used which is why it shows it is half full because of the order in which things happen.
