### ISSUE TITLE
Energy Upgrades makes Chemical Infuser consume more energy with energy upgrades

### ISSUE THREAD

**Issue by BastouP411** [mekanism/Mekanism#7018]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When the chemical infuser has 8 speed upgrades the bug happens.
The machine consumes 32 kFE/tick without energy upgrades and 204 kFE/tick with 8 energy upgrades.
However it behaves normally with no speed upgrades installed.

#### Steps to reproduce:
1. Put 8 speed upgrades in the infuser
2. Verify machine consumption
3. Put 8 energy upgrades.
4. Verify machine consumption again

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.42
**Mekanism:** 10.0.21.448
**Minecraft:** 1.16.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash happened.

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

Without energy upgrades:
https://media.discordapp.net/attachments/813079351888445480/813758217007398932/unknown.png

With energy upgrades:
https://media.discordapp.net/attachments/813079351888445480/813758247764885504/unknown.png

**Comment by Robball14** [comment]
is intended

**Comment by pupnewfster** [comment]
Copy pasted from our FAQ on discord, I believe this is what you are running into:

**Q:** *Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?*
**A:** Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the exception that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.

**Comment by BastouP411** [comment]
Sorry I was referring to the wiki:

> The energy upgrade upgrade allows you to increase the power storage capacity of a Mekanism machine which has an upgrade slot, as well as reduce its power consumption.

It was written here so I thought it was how it did behave.

**Comment by thiakil** [comment]
You appear to have not understood the explanation.

**Comment by SteelBlue8** [comment]
> Sorry I was referring to the wiki:
> 
> > The energy upgrade upgrade allows you to increase the power storage capacity of a Mekanism machine which has an upgrade slot, as well as reduce its power consumption.
> 
> It was written here so I thought it was how it did behave.

That is talking about the ENERGY upgrade. Uses gold dust instead of osmium, and makes it use less power. Speed upgrades make it run faster, but also use more power.
