### ISSUE TITLE
Fission Reactor Preserves Heat After Blowing Up

### ISSUE THREAD

**Issue by EnderLord0042** [mekanism/Mekanism#7031]
#### Issue description:
If you set the fission reactor to burn fuel very fast, and its temperature climbs to an insane level, then it will melt down. However, if you rebuild another fission reactor in the same exact spot, it will be considered the same fission reactor. This will preserve the amount of Fissile Fuel it contains, but it will also preserve the temperature. This can cause a second reactor to melt down without even being turned on.

#### Steps to reproduce:
1.Build a fission reactor with a decent number of fuel rods, Infinite Water, infinite fissile fuel, and infinite waste disposal.
2.Set the fuel to burn at the maximum speed for your reactor (depends on the number of fuel rods)
3.Let it melt down
4.Rebuild the same reactor, and watch it melt down without being turned on, as temperature is preserved.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5-forge-36.0.46
**Mekanism:** Mekanism-1.16.5-10.0.21.448

**Comment by pupnewfster** [comment]
I don't think this is a bug, but I will put it on the list of things to discuss with aidan if we want to just reset the temperature + damage when it enters a meltdown or not.

**Comment by orchidalloy** [comment]
Definitely an oversight.

**Comment by dtromb** [comment]
I just hit this one too, it's glaring nasty / surprise behavior!    It doesn't really work to just reset the temp - the meltdown happens over a fixed number of ticks, isn't always catastrophic, and will not always result in an explosion / breaking bricks.  (Tho, for most reasonable config settings it probably will!)

It is absolutely the case that from the user perspective (and mine, before I read code), the interpretation @orchidalloy gives is totally reasonable.

In my case there were only one or two pieces of casing left....

Something like the following logic may be in order:   if, at the end of the Meltdown object lifecycle, some number of blocks (perhaps one, perhaps more?) have been removed, suspending the multiblock - the reactor is considered "destroyed".   At this point the multiblock state could be deleted, and/or the reactor switched to the "off" or "SCRAM" state, and/or the damage and heat capacity state reset to nominal/ambient.   

The fuel should also be lost - that's what a meltdown is, by definition.  Right now it keeps on burning after "melting down".

This should certainly happen at least in the case that all logic controllers are destroyed - in that case there is literally no way to rebuild the reactor without some chance of it immediately melting down again.  

Alternatively, give users some warning or indication that this is about to happen (perhaps by always rendering the damage state of the reactor somehow?)  It can take a long time to rebuild after a meltdown - the parts are expensive - and to have them all vanish again rudely to a nonsensical and unexpected second blast without even fueling or turning on the "new" reactor seems capriciously and drastically unfair.

If any of these fixes seem sensible, I'm happy to implement them, btw.

**Comment by orchidalloy** [comment]
This is why it's not even fun to have reactor explosions turned on in the mod. Radiation is good enough of a punishment, but then you also have to rebuild your base, make a brand new reactor and it can't even be in the same spot because it will explode again instantly.

**Comment by dtromb** [comment]
It was totally fun the first time it exploded!  (due to some power switching logic for coolant pumps failing with a faulty/undertested auto-off redstone circuit).   I also liked seeing how much quicker I could build it the second time, after a bit of progress.  

The "reactor is suspended in the about-to-explode state in a pocket dimension after it exploded and reappears in place of the new reactor you just build making it explode again within a moment of placing the last block, which would otherwise be a fine moment of redemption" - not so much fun.

**Comment by xenoflot** [comment]
Just to add to this, it not only preserves the heat but the damage state. I'm currently testing with MekanismGenerators-1.16.5-10.0.21.448 in creative, made a relatively simple setup, pushed it to explode and rebuilt exactly. The newly formed reactor has a 230%+ damage value.

**Comment by pupnewfster** [comment]
Brief summary of the above commit that got linked to this of the behavior/changes I made that will be included in 10.1 for a fission reactor's meltdown:
- Release the correct amount of radiation instead of at least double the amount, and even more if you have "bad" RNG
- Not persist the waste in the reactor if you rebuild it (as it was released during meltdown)
- Disable itself so it doesn't automatically reactivate if you rebuilt it
- Reset the temperature of the reactor to ambient
- Lower the reactor's damage to 75% (this percentage is configurable)
