### ISSUE TITLE
1.16.5 Fabric

### ISSUE THREAD

**Issue by K4dj1t** [mekanism/Mekanism#7063]
Please, update for 1.16 fabric <3
Its a very perspective modloader with good optimization and graphics (For example, on forge fps=50, on fabric its 750) (Really) 
I think, many developers will soon switch to it

(I really need a version under fabric, cause im creating a modpack at the ftb level :D)

**Comment by pupnewfster** [comment]
From our FAQ:

**Q:** *Will you port to Fabric or is there already a Fabric Version?*
**A:** At this time we have no plans of porting to or supporting Fabric. Mekanism is MIT licensed, if you want to go ahead and try and port it yourself feel free. Just keep in mind it is a massive mod that makes use of a lot of Forge features and in no way will be an easy port. If you do end up porting Mekanism to Fabric, let us know so that we can direct the people who ask to you.
