### ISSUE TITLE
Electrolytic Separator Energy Usage

### ISSUE THREAD

**Issue by R3tr0PAG** [mekanism/Mekanism#7068]
#### Issue description:
After inserting Energy Upgrade's in the Electrolytic Separator the Energy Usage doesn't decrease.

#### Steps to reproduce:
1.Insert Energy Upgrade's (any amount) into Electrolytic Separator.
2.Energy Usage doesn't decrease.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.16.5-forge-36.0.54
**Mekanism:1.16.5-10.0.21.488

**Comment by Seniorendi** [comment]
Please use the search function before creating an issue report.
Here is a quote of the FAQ:

> Q: Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?
A: Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the exception that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.
