### ISSUE TITLE
boiler max boil rate seems off

### ISSUE THREAD

**Issue by alexshore** [mekanism/Mekanism#7121]
#### Issue description:

disclaimer: not on the latest version  but dont know if its a bug or not 

have an almost maximum size boiler 17x18x17 with 675 super coolers in at the bottom, and a layer of pressure dispersers on the 16th level of the boiler, feeding it heat from a resistive heater that is being fed up to 8.7MRF/t (i have 3 fusion reactors powering it) and if i put in say a 2MRF/t input to the resistive heater it goes up to ~78.5kK but the boiler stays at 100°C (373.15K) and only has a max boil rate of 49617mb/t which seems incredibly low having seen the maximum boil rate of the boiler in [this video](https://www.youtube.com/watch?v=Zv7XrmVfKN4) so I'm just wondering if im not exactly understanding how it works or if somethings changed in the config that i didnt see or what?

also just noticed that when i disconnect the conductive heat thing and reconnect it the max boil rate seems to start very high and then settle to the value in the screenshot

edit: also this doesn't really make any sense to me as i feel like a boiler powered by 3 fusion reactors all on 98 injection rate should give enough steam to allow the turbine its feeding to produce more than the reactors are producing, even if i put the resistive heater at 8.7MRF/t its still only a 213629mb/t max boil rate which isnt that much and only lets my turbine produce 6.1MRF/t

![image](https://user-images.githubusercontent.com/40403410/115318925-a916f900-a176-11eb-9057-13ffdf019658.png)
![image](https://user-images.githubusercontent.com/40403410/115318952-b502bb00-a176-11eb-81ad-6833074ce727.png)

![image](https://user-images.githubusercontent.com/40403410/115319113-feeba100-a176-11eb-903a-61605b8dd9ef.png)

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2854
**Mekanism: 9.8.3.390
**Other relevant version: Minecraft version 1.12.2

**Comment by thiakil** [comment]
You'd likely be better off using the reactor itself to produce steam (feed it water).

As for the Boiler's steam production:

- That video is from 1.7.10 so numbers may have changed since then
- You need to have enough Boiler steam tank capacity to handle large volumes of steam 
- Thermodynamic conductors are **_extremely_** lossy, and not worth it when you've just got the one heater
- I'm not intimately familiar with the internal calculations, but heating water _transfers_ the energy to the water, so it's feasible that at the point of measurement it is only 100c
- You could just pipe the heat straight from the reactors via a reactor port

Also, even if it is a bug, we no longer support 1.12 so it won't be fixed, and the Boiler has changed drastically in later versions.
