### ISSUE TITLE
Crafting doesnt work

### ISSUE THREAD

**Issue by DoArt001** [mekanism/Mekanism#7135]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I can take the mekanism items from the creative inventory but I cant craft them in survival.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Seniorendi** [comment]
We can't help you if you do not provide us the needed information like the versions and logs.

**Comment by pupnewfster** [comment]
What specifically doesn't craft? Are the recipes loaded (do they show up in JEI)? Are you playing a modpack that might have changed recipes? What version are you on? You don't provide your latest log... how are we to help you if you don't provide any information that can help us figure out what the issue is that you are running into.
