### ISSUE TITLE
Oxygen Into PRC

### ISSUE THREAD

**Issue by 249k** [mekanism/Mekanism#7179]
Issue description: Attempting to make HDPE, PRC will accept liquid ethylene, will not accept oxygen from a tank, any pipe / machine. You can set the tank to output on any side, the oxygen disappears as soon as it goes in, like the tank was never full. PRC also says "Air" versus "Oxygen"? Gauge dropper also does not work.

Forge: forge-36.1.2
Mekanism: 1.16.5-10.0.21.448
Modpack: All the Mods 6 - To the Sky

**Comment by pupnewfster** [comment]
Could you provide some pictures of your setup

**Comment by 249k** [comment]
> Could you provide some pictures of your setup

![2021-05-13_14 38 08](https://user-images.githubusercontent.com/84127209/118172285-2e9a6b80-b3fa-11eb-9087-b1e9afeacb21.png)

From left to right, Electrolytic Separator to PRC with biofuel to made ethylene. PRC to rotary condensentrator to make liquid ethylene. RC to PRC. To the right is another Electrolytic Separator to get oxygen into the PRC, does not work.

**Comment by pupnewfster** [comment]
Have you tried both output sides of the separator? (There is an "output 1" and "output 2" on the side config for gases) And is it set to auto eject with the PRC setup to access gases from that side. Also I am still not quite sure what you mean by it showing "air". (Joining our [discord](https://discord.gg/nmSjMGc) may help get quicker responses/suggestions on what the issue is)
