### ISSUE TITLE
Digital Miner Draws Power when Missing Replacement Blocks

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism#7185]
#### Issue description:
I have my digital miner setup to replace all ores picked up with cobblestone. When it runs out, I've noticed that it still draws power despite not doing anything. I would think that if it was to still draw power, it would draw significantly less power if it wasn't actively teleporting any ores since it's just idle.

#### Steps to reproduce:
1. Setup a digital miner to mine ores and require replacement with some block such as cobblestone.
2. Allow it to run out of the required replacement block.
3. Monitor its power consumption when it's running and missing replacement blocks.

#### Version :
Minecraft v1.16.5
Forge v36.1.0
Mekanism v10.0.21

**Comment by pupnewfster** [comment]
So I finally got a chance to look at this (and think about it more) and while I sort of agree with you that it seems weird for it to be using energy if it fails to mine... The reason that it *should* be using energy is that while it is active (even between "mining operations", as long as there are more things to mine the miner draws power constantly. Which means that to have it randomly not use energy just because it tried to mine and fail wouldn't make much sense.

**Comment by Peekofwar** [comment]
> So I finally got a chance to look at this (and think about it more) and while I sort of agree with you that it seems weird for it to be using energy if it fails to mine... The reason that it _should_ be using energy is that while it is active (even between "mining operations", as long as there are more things to mine the miner draws power constantly. Which means that to have it randomly not use energy just because it tried to mine and fail wouldn't make much sense.

Theoretically, it would first check that it has a replacement material, and if it doesn't, it shouldn't attempt to mine... Perhaps, it could at least have a reduced energy usage, or maybe it could optionally automatically shut itself down?
