### ISSUE TITLE
Oredictionificator only excepts ingots and Dusts

### ISSUE THREAD

**Issue by P3chv0gel** [mekanism/Mekanism#7207]
#### Issue description:
The Oredictionificator seems to not except filters for any item-tags "forge:gems/??" or "forge:??", while "forge:ingots/??" or "forge:dusts/??" works just fine. Tried every possible key shown by the forge tooltips and the dictionary item, always get an "Incompatible Tag" error. Tried with Items from vanilla Minecraft as well as from mods like: gravel (forge:gravel), diamonds (forge:gems/diamond), sulfur (forge:gems/sulfur), niter (forge:gems/niter) and more and the only types, that get accepted are the aforementioned.

#### Steps to reproduce:
1. Open Ordictionificator
2. New Filter
3. Try adding any forge:gems Tag

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.0
**Mekanism:** 10.0.21
**Other relevant version:** Minecraft 1.16.5

#### If a (crash)log is relevant for this issue, link it here: 
Never experienced a crash with Mekanism installed :)

**Comment by pupnewfster** [comment]
This is due to how equivalent things actually are for gems being less set in stone than things like ingots and the like. It is planned for 10.1 to make this list configurable: https://github.com/mekanism/Mekanism-Feature-Requests/issues/145 (The current hardcoded supported types are `forge:ingots/`, `forge:ores/`, `forge:dusts/`, `forge:nuggets/`, and `forge:storage_blocks/`)
