### ISSUE TITLE
Itemstack Filtering in the digital miner is broken with JEI due to the replace tool

### ISSUE THREAD

**Issue by GandhiChan** [mekanism/Mekanism#7211]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In the Digital Miner, when setting an itemstack filter, you would expect dragging an item from JEI into a slot to set it to work like other filters - but it does not. Instead, you can only drag onto the "replace" area in the filter selector.

#### Steps to reproduce:
1. Open the Itemstack Filter interface in the Digital Miner
2. Attempt to drag an item from JEI to set the filter

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.9
**Mekanism:** 10.0.0.21
**Other relevant version:** Minecraft 1.16.5 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This is fully intended.

Also see: https://github.com/mekanism/Mekanism-Feature-Requests/issues/244

**Comment by GandhiChan** [comment]
Does this mean that the current ability to do so on things like the Logistical Sorter will also be changed on future versions?

**Comment by pupnewfster** [comment]
No. The reason the item filter on the miner requires the item is so that you actually have to get the item first before you can just mine it. Yes tags exist but there isn't a great way to require getting the items first. 10.1 is adding a server side config that changes the balance to allow for dragging from JEI into the miner. The reason sorters and the like can just be dragged into is that you still need the actual item for the filter to really do anything given it sorts items, that is also why the replace stack on the miner can be dragged into regardless as you need to supply the block for it to actually use it.
