### ISSUE TITLE
incompatible with Idealland

### ISSUE THREAD

**Issue by xlhyjx8** [mekanism/Mekanism#7230]
Idealland URL:https://www.curseforge.com/minecraft/mc-mods/idealland
[incompatible with Idealland.txt](https://github.com/mekanism/Mekanism/files/6630831/incompatible.with.Idealland.txt)

**Comment by pupnewfster** [comment]
No idea what is going on there but we are no longer developing for 1.12 so if the issue is actually on our end there is nothing that will be done for it. Seems to have something to do with rendering items in the logistical transporter. And them thinking it is some sort of living birth? (Not sure why items would be living)
