### ISSUE TITLE
[Possible mod conflicts] Pipez forgetting connection to mekanism multi-structure tanks

### ISSUE THREAD

**Issue by jarquafelmu** [mekanism/Mekanism#7233]
Issue is reported here:
https://github.com/henkelmax/pipez/issues/50

**Comment by pupnewfster** [comment]
Pretty sure this is on their end. No idea how pipez works (so if you are supposed to have to manually reconfigure a pipe connection if a side becomes invalid and then valid again there is nothing that can be done as everything on both ends would be functioning as intended), but as far as I am aware the general/common handling of when a tile goes from not exposing a capability to exposing it now is by firing a neighbor update notification to the blocks so that it can recheck it (as unfortunately unlike when going from a valid connection to no valid connection there is no lazy optional for us to invalidate as when there is no capability initially we return an empty lazy optional). For good measure we call both `onNeighborChange` and `neighborChanged` in case a mod is listening to only one of the two things. From the sounds of it they may not be listening to either?
