### ISSUE TITLE
Isotopic Centrifuge uses more power with energy upgrade

### ISSUE THREAD

**Issue by LonnonjamesD** [mekanism/Mekanism#7235]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Isotopic Centrifuge uses more power with energy upgrade

#### Steps to reproduce:
1. put energy upgrade in
2. compare past energy and new energy usage
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.23
**Mekanism:** Mekanism-1.16.5-10.0.21.448.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Copied from our FAQ on discord:

**Q:** *Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?*
**A:** Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the exception that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.
