### ISSUE TITLE
[minor issue] remove personal chest from recipes with chests

### ISSUE THREAD

**Issue by vichug** [mekanism/Mekanism#7276]
### Issue description

Hey, when crafting something with shortcut (like from JEI or from a RFTools Storage or even vanilla crafting recipe shortcuts tab), if the recipe requires any chest (like a hopper, any storage upgrade and so on) and you have a Personal Chest in your inventory ; the recipe will always prioritize this personal chest to be used in that recipe, even if you have more generic wooden chests in your inventory. I actually lost a full Personal Chest content by unwillingly using it in such a recipe, and gave up altogether on using Personal Chest, because it was always used by default in that kind of recipe and i was afraid i'd end up losing another full chest and its content. Maybe something could be improved from JEI side or something, but i'm under the impression it would be better to ditch altogether the possibility to use the Personal Chest as a generic chest in any recipe.

### Steps to reproduce

Have a personal chest in your inventory and also any other generic chest, look for any recipe including a chest (mainly through the JEI interface), make sure you have all the other required ingredients and press the '+' button that appears in JEI interface. You should see the personal chest included in the recipe/

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.13

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Honestly I am sort of the opinion of the fact that mods *shouldn't* for the most part be using the generic `forge:chests` tag in chests in the first place (as that also matches other potentially expensive chests such as an enderchest, though yes that is less expensive than a personal chest with many items) and should instead be using `forge:chests/wooden` (which I mentioned some in #6803 as well).

Looking at it hoppers only accept `forge:chests/wooden` so if there is some other recipe that accepts other types of chests then some other mod or the modpack is overriding it which I would say is heavily questionable and on them.

In regards to RFTools storage I would say they really should be using `forge:chests/wooden` as otherwise the recipe is a bit meaningless as then I wouldn't be surprised if currently it allows both a diamond chest and dirt chest which are drastically different in costs (and potentially should be opened as a suggestion that they change to only using wooden chests).

I will leave this issue open for now though so as to discuss it internally a bit more if we want to just remove the personal chest from the `forge:chests` tag, though personally I am against it as for things like sorting it is very logical for it to be in the chests tag as it is a chest.
