### ISSUE TITLE
 mekanism.common.tile.transmitter.TileEntityMechanicalPipe  cause ClassCastException

### ISSUE THREAD

**Issue by ternsip** [mekanism/Mekanism#7285]
### Issue description

https://gist.github.com/ternsip/bcb55a26b7815692032dc3b8258da12c

### Steps to reproduce

1. Open Diamond barrel from IronBarrels with mechanical pipe

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ternsip/bcb55a26b7815692032dc3b8258da12c

**Comment by pupnewfster** [comment]
This looks like some mod or something corrupted your world or given the crash is client side something is causing it to send the wrong information about tiles/blocks to the client. Not really sure what to suggest as I don't think this has anything to do with Mekanism beyond the fact that it thinks one of our tiles is where a metal barrel is.

**Comment by ternsip** [comment]
That was server side. All the clients who tried to open that barrel with mechanichal pipe had such crash. After destroying that barrel items poped out and the bug has gone. Looks like something is really wrong on server side. Perhaps it's on mechanism side because author of iron barrels responded nagative.

**Comment by thiakil** [comment]
The crash happened ON the client side, doesn't matter that you were _connected_ to a server.

The bug _could_ have been caused by a vanilla or Forge issue, but there's not enough info to go on. It is certainly unlikely to be anything Mek or Iron Barrels did

The end result is that SOMETHING caused the normal association between block and TileEntity/BlockEntity to break down.

There is nothing either mod can do. You could check with mowziesmobs since it's happened inside their event handler

**Comment by ternsip** [comment]
Thanks
Yes crash happened on client side. I mean that barrel with something corrupted stored on server-side world and any client that has come to that barrel and opened it falls into that kind of crash.
Maybe you are right about mowzie mobs. I just can't leave that bug without proper solution. 
I sent it to bobmowzie mob

**Comment by pupnewfster** [comment]
I mean there is also a fair chance if you have a bunch of mods it may just be mojang's bug of the fact that SMultiBlockChangePacket doesn't encode things properly from what some people have mentioned to me at one point which then just makes it so that there is a different block there. If I had to guess that may just be it given the crash is client side and not server side (though maybe the server has the mismatch as well and it just isn't calling the problematic method)
