### ISSUE TITLE
[Bug] Magnetic attraction unit picks up infinite multishot arrows

### ISSUE THREAD

**Issue by sharkck** [mekanism/Mekanism#7287]
### Issue description

Forge 36.2.2 Dedicated server + clients
Mekanism 10.0.21

Have someone shoot a bow with infinity + multishot and you can pickup all the arrows you can dream of.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Were you in creative when testing this? As I cannot reproduce outside of creative mode, but when in creative mode I can pickup them up anyways with the magnet off and just walking over them.

**Comment by pupnewfster** [comment]
Finally got around to testing in 10.0.24 instead of the 10.1 branch to see if I could reproduce this and I still couldn't.
- Crossbows with infinity still have main arrow be an actual arrow that can be picked up (infinity doesn't work)
- Bows with multishot only fire one arrow (multishot doesn't work)
My best guess if you actually did mean bow and not crossbow is that some mod you have/had installed is modifying the bows to have the multishot enchantment work on them and that mod isn't applying the proper flags to the extra arrows in regards to if they can be picked up or not.
