### ISSUE TITLE
Seting particles / light updates on the machines to off does nothing

### ISSUE THREAD

**Issue by 7eggert** [mekanism/Mekanism#7296]
### Issue description

I've got a mod (light Levels Overlay) that needs a lot of processing time each time one of the machines causes an update. (Also it seems to update the light all the time?).

Thus 

### Steps to reproduce

I set the machines to neither change the light level nor to emit particles.

It didn't change anything.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

light-overlay-5.8.1.jar

**Comment by pupnewfster** [comment]
How the light level is done and things has changed for V10 (given the config doesn't really work properly due to it also updating things server side), the light level is not toggleable uses the vanilla way of doing it and is a lower default value so it updates less blocks which should help some, and should only be updating when the machine changes from on to off or off to on (which there may have been a slight bug in how it was done in 10.0.21 causing it to update more often than that though I don't remember).

In regards to the setting particles to off not doing anything I will look at that for 10.1 (though I think I may have already fixed that as I did adjust how the particle config is handled, but I will make sure to confirm just to be sure).

**Comment by 7eggert** [comment]
The updates do cause really severe lag spikes (you can see the point time time when I switched on the overlay):

![2021-08-23_00 50 02](https://user-images.githubusercontent.com/924567/130372544-4daa3de7-fa3f-4852-a007-017562becf51.png)

Away from mekanism machines:

![2021-08-23_00 50 28](https://user-images.githubusercontent.com/924567/130372542-74b3ee7b-3263-488f-b6ed-e5dbb87d2d2a.png)
