### ISSUE TITLE
[1.12] dummy world provider's world is never set, causing crash on World#getSeed

### ISSUE THREAD

**Issue by Drillgon200** [mekanism/Mekanism#7313]
### Issue description

One of the recipes in HBM's Nuclear Tech mod requires the world seed to generate itself.
Mekanism's OreDictManager, line 450
Crash report isn't mine, but it shows the issue.

### Steps to reproduce

Install NTM
Install Mekanism
Start game

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

1.12.2

### Mekanism version

Older

### Other relevant versions

hbm-1.6.0a-1.12.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/qyezSDmR

**Comment by pupnewfster** [comment]
Unfortunately as we are no longer developing for 1.12 I think you may be out of luck on this one. You might be able to remove the logs from that mod from the oredict with something like crafttweaker but I am not sure if that would even fix it and it would have other side effects as well.

**Comment by Drillgon200** [comment]
I'm the dev for it, and it's easily fixable from my end as well (and has been fixed since). But, as it's technically a mekanism bug, I just figured I'd put it here as well.

**Comment by pupnewfster** [comment]
Ah, ya thanks for that it is nice when modders report issues rather than just adding a patch and not doing so. I do agree it definitely is a Mekanism bug, but given the fact that we aren't developing for 1.12 anymore (and that code no longer exists in the currently developed version of Mekanism), there isn't much to do on our end about it. I am glad however you were able to just add a patch on your end, I didn't look into who the dev was so had assumed you were just a user, so was giving some suggestions to potentially work around it without risking a user going to harass another mod dev who maybe also is no longer supporting 1.12, about adding a patch/workaround on their end for a bug that isn't even in their mod.
