### ISSUE TITLE
Mekanism and Reliquary Interaction Dupe

### ISSUE THREAD

**Issue by Wlnfr** [mekanism/Mekanism#7316]
### Issue description

Hero's Medallion(Portable XP Storage) placed in any of Mekanism's fluid tanks will output 19 MB per tick of reliquary's fluid xp infinitely.

Same issue has been made on Reliquary's Github: https://github.com/P3pp3rF1y/Reliquary/issues/532

### Steps to reproduce

1. Place a fluid tank.
2. Put Hero's Medallion that has some XP in a tank.
3. Watch it infinitely produce liquid XP at 19 MB per tick(?) rate.
Video demonstration:
https://user-images.githubusercontent.com/8050905/135632253-5b819d6f-f19a-4f03-8dbe-60d5a9e82766.mp4

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

Reliquary -1.16.5-1.3.5.1100
JEI - 1.16.5-7.7.1.118

**Comment by pupnewfster** [comment]
If I had to guess this is related to how small an amount it is and Reliquary seeming to have some rounding issues that happen with [this](https://github.com/P3pp3rF1y/Reliquary/blob/1.16.x/src/main/java/xreliquary/util/XpHelper.java#L12) and [where it actually reduces it](https://github.com/P3pp3rF1y/Reliquary/blob/1.16.x/src/main/java/xreliquary/items/util/fluid/FluidHandlerHeroMedallion.java#L94) so that if it is < 20 it will reduce it by zero.
