### ISSUE TITLE
Mekanism Jetpack Sound Disappears after changing sound level on servers

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism#7349]
### Issue description

> It appears when you change any sound level (master. music, players, etc) the Mekanism jetpack stops making noise. I found this issue on a server, and I have tested on singleplayer with this issue never happening.

### Steps to reproduce

1. Wear a jetpack on a server
2. Change the sound level of anything through the Options menu
3. See issue

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.9

### Mekanism version

10.0.24 (Latest)

**Comment by pupnewfster** [comment]
As I commented on https://github.com/NillerMedDild/Enigmatica6/issues/3804 I can't reproduce this but I did run into an issue where player sounds wouldn't "restart" until relogging if either the master or player slider was set to muted and then unmuted; so I am repurposing this issue to track that as it is relatively similar in reproduction steps except that it is specific sliders and setting them to muted instead of any and adjusting them partially. As stated on the linked issue I think it is being caused by some other mod and/or related to #7204 breaking some other mod and it being caused from that.

**Comment by rreilly-edr** [comment]
I have the same issue, both in enigmatica6 and FTB Ocean Block, use the muting menu and jet pack no longer sounds, fixes with restart of game.
