### ISSUE TITLE
Chemical Washer reduces washing speed with more than 5 Speed Upgrades

### ISSUE THREAD

**Issue by jonasKoehler** [mekanism/Mekanism#7383]
### Issue description

I set up a 5x ore pipeline in a creative test world and wondered why my 5 washers per 1 dissolution chamber were so slow (with 8 Speed Uprades).
I discovered that, by hovering over the output tank, the machine speed per upgrade goes as following:
0: 1
1: 2
2: 4
3: 8
4: 16
5: 22
6: 12
7: 7
8: 4

So basically with 8 Speed Upgrades you get the production as if you had 2. This cant be intended. I dont know if it has been fixed in the latest version, i did not find a past issue posted.

### Steps to reproduce

1. Build Dissolution Chamber to Chemical Washer Setup
2. Insert 8 Speed Upgrades in Upgrade view
3. Look at the production rate by hovering over the output tank in the washer (build a tube so the tank doesnt fill up)
4. Observe the rate change with each speed upgrade as it is applied

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.24

**Comment by toddlersizedsharkcage** [comment]
Do you have all 8 energy upgrades as well?

**Comment by pupnewfster** [comment]
From our FAQ (same concept)

Q: Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?
A: Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the exception that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.
