### ISSUE TITLE
SpongeForge Incompatibility

### ISSUE THREAD

**Issue by DocterDum** [mekanism/Mekanism#7411]
### Issue description

When using Mekanism and SpongeForge the game crashes on launch

Tested with only Mek and SF installed.

[latest.log](https://github.com/mekanism/Mekanism/files/8066821/latest.log)
[debug.log](https://github.com/mekanism/Mekanism/files/8066822/debug.log)
[crash-2022-02-15_18.35.43-fml.txt](https://github.com/mekanism/Mekanism/files/8066824/crash-2022-02-15_18.35.43-fml.txt)

### Steps to reproduce

Install Mekanism, SpongeForge
Run game
Crash

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.26

### Mekanism version

10.1.1 (Latest)

### Other relevant versions

spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

Included in description

**Comment by thiakil** [comment]
That's crashing in Sponge's mixin, we only support vanilla

**Comment by pupnewfster** [comment]
I will try to look into this *briefly* as part of the final 1.16 version as I believe it is due to us passing a null level to the item entity just given it doesn't crash and then we set it before it actually gets used, though sponge is mixing in and trying to use the field (as it is usually non null) before it is being used or even has been added to a world, so I guess we could try and lazily initialize the field.

**Comment by DocterDum** [comment]
Awesome, thank you!

I'd offer more help but this one's way over my head.

**Comment by DocterDum** [comment]
@pupnewfster Just so you know SpongeForge's devs just sent through a test build with this issue fixed

**Comment by pupnewfster** [comment]
I didn't test with spongeforge but I believe 10.1.2 should fix this from our end as well.
