### ISSUE TITLE
Power does not come back after breaking a long universal cable

### ISSUE THREAD

**Issue by FayeDE** [mekanism/Mekanism#7428]
### Issue description

See below how to reproduce.
Here's a Youtube video describing the issue: https://www.youtube.com/watch?v=-Ot2v0vIoBc

### Steps to reproduce

1. Build Ultimate Energy Cube
2. Build a 210 blocks long elite universal cable onto the ultimate energy cube
3. Fly back and break cable directly after the ultimate energy cube
4. Rebuild broken cable
5. Fly to the end of the elite universal cable
6. Observe broken energy at cable length 200
7. Rebuild cable at length 200 -> Other cables after it won't be fixed, it is necessary to rebuild all cables from block 200-210

### Minecraft version

1.16.5 (Latest)

### Forge version

forge-1.16.5-36.2.31

### Mekanism version

10.1.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://paste.fayedev.de/akolaqejec.md

**Comment by JanDevDE** [comment]
Maybe related to https://github.com/mekanism/Mekanism/issues/6356

**Comment by pupnewfster** [comment]
Thank you for this detailed reproduction scenario. I believe you are right that it likely is the same thing as has been plaguing #6356 (or at least one of the last remaining and more reproduceable causes). I am sorry I was not able to look into this earlier due to a variety of things going on in life but the report did lead me to tracking down the issue and fixing it for 10.3.1 (MC 1.19.1 and 1.19.2). Unfortunately it is not practical/feasible to backport to 1.16 or 1.18 due to the changes required to fix it.

**Comment by FayeDE** [comment]
> Thank you for this detailed reproduction scenario. I believe you are right that it likely is the same thing as has been plaguing #6356 (or at least one of the last remaining and more reproduceable causes). I am sorry I was not able to look into this earlier due to a variety of things going on in life but the report did lead me to tracking down the issue and fixing it for 10.3.1 (MC 1.19.1 and 1.19.2). Unfortunately it is not practical/feasible to backport to 1.16 or 1.18 due to the changes required to fix it.

Thanks a lot!
