### ISSUE TITLE
Config files being ignored and overwritten

### ISSUE THREAD

**Issue by Boolyman** [mekanism/Mekanism#7442]
### Issue description

When I change the amount of "energyPerInput" for the SPS Settings, the amount is immediately overwritten once the pack is loaded.  

### Steps to reproduce

Change the amount of energyPerInput
Load the pack
Cry in disbelief as your config changes are overwritten

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.29

### Mekanism version

10.1.2 (Latest)

**Comment by pupnewfster** [comment]
What exactly are you trying to set it to? Like what does the line look like

**Comment by AlexHgC** [comment]
1 ) What do you mean by " the pack" ?
2 ) Do you change config when the game is **closed** or when it's running ?
3 ) Do you play on solo or on server ?

**Comment by Boolyman** [comment]
```
		#Energy needed to process 1 mB of input (inputPerAntimatter * energyPerInput = energy to produce 1 mB of antimatter).
		energyPerInput = "700000"
```

A 30% reduction.
I found it odd that the value, by default, had quotations around it.  I tried it with and without quotations.  But it reverted the value back to the default number of "1000000" no matter which one I tried.

**Comment by pupnewfster** [comment]
It needs quotes around it just because of the range that the max allowed value is greater than the max long. Are you editing the file while the game is closed or when it is open? And if it is open are you using notepad++ (as how it saves files causes issues with the config's file watch system) in which case I would recommend using another editor or having the game closed before making the changes.

**Comment by Boolyman** [comment]
I'm using sublime text editor.  And it seems to have stuck if I make all changes when the pack isnt loaded, and then relaunch it.  Ill let you know if it doesnt stick.
