### ISSUE TITLE
Items not going into Metallurgic Infuser

### ISSUE THREAD

**Issue by Epicpoop21** [mekanism/Mekanism#7449]
### Issue description

I can put redstone into the power slot, but I cannot put items into the infuse material slot or infuse slot of the metallurgic infuser. I am running a server with the attached mod list 
![image](https://user-images.githubusercontent.com/73061192/163177947-e97211d5-d682-438f-8576-deb206569536.png)
and can put items into the other machines such as the enrichment chamber.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.46

### Mekanism version

10.2.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/6DFeQcWp

**Comment by Epicpoop21** [comment]
Which channel can I use on discord? If it would be a ticket/in DMs, Correct Speling#5118 is my user

**Comment by zhizhang47** [comment]
I had the same problem Can't pipe in redstone from the side, which keeps me from automating my version is 1.16.5

**Comment by zhizhang47** [comment]
> 我可以在 discord 上使用哪个频道？如果它是一张票/在 DM 中，正确拼写#5118 是我的用户
I found the right way, open the metallurgical infusion machine - side configuration {only show the energy configuration and infusion type configuration, click on any one of the configurations, then the item configuration button will appear, and set the color of the side to be input redstone to Yellow} This problem is solved like this

**Comment by zhizhang47** [comment]
> 我可以在 discord 上使用哪个频道？如果它是一张票/在 DM 中，拼写正确#5118 是我的用户
我找到了正确的方法，打开冶金灌注机-侧面配置｛只显示 能量配置和灌注类型配置、点击其中任意一个配置、此时物品配置按钮就会出现，把要输入红石的一侧颜色设置成黄色｝这个问题就这样解决了
