### ISSUE TITLE
Mining certain mods ores with Atomic Disassembler fails to drop the ore chunk

### ISSUE THREAD

**Issue by steven-archer** [mekanism/Mekanism#7461]
### Issue description

I have not been able to do extensive testing, but I have found some ores that will not drop anything when using the disassembler in any mode, even though walia shows it is harvestable. But the same ores will drop their items when using other tools, including the Mechanism Paxels. I don't know if this is something I can fix by adding them to a config/whitelist or something.

Nourished Nether 1.1.3 
- Basalt Redstone Ore
- Glowing Obsidian
- Soul Quartz Ore

Stalwart Dungeons 1.2.2
- Tungsten ore

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.54

### Mekanism version

10.2.0 (Latest)

**Comment by pupnewfster** [comment]
Honestly it sounds like those mods have some weird specific checks in them (which as it seems both are MCreator mods is not that surprising), and are maybe specifically instance checking in their loot table in some way or other for if it is a tool item rather than if the tool marks it as being able to harvest it, being the correct tool for drops, and ignoring the tool actions. I would report the issue to the corresponding mods as there is nothing on our end that we can do.
