### ISSUE TITLE
Placing a wind generator crashes client

### ISSUE THREAD

**Issue by ArnoldVanN** [mekanism/Mekanism#7465]
### Issue description

I'm playing on a modpack called better minecraft for 1.18.2 and have mekanism and mekanism generators installed.
When placing a Wind Generator me and my friend's clients crashed.
Both Mekanism and generators are on version 10.2.0
Other Issues i found with the same problem unfortunately couldn't help me fix this.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.54

### Mekanism version

10.2.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/GWAy8FUQ

**Comment by pupnewfster** [comment]
This looks like a crash in sodium (or more accurately whatever the forge port of it is I think rubidium). Does it happen without it installed?

**Comment by ArnoldVanN** [comment]
Sorry, closed instead of commenting... But yes, that fixed it although now my world's see through. Any recommendations for other  rendering engines i could try instead of rubidium?

**Comment by pupnewfster** [comment]
No idea why your world is see through without rubidium unless you have some other mod installed that assumes rubidium is present and is breaking the rendering when it isn't instead of just not allowing the game to load.

But if it works without rubidium then you should report the crash to them as there is nothing on our end we can do about it.

**Comment by KowalskiXCIX** [comment]
I am currently having this exact same issue, is there any update?

**Comment by pupnewfster** [comment]
Ask rubidium's devs or remove it. There is nothing we can do on our end to fix it.
