### ISSUE TITLE
Crash at create world

### ISSUE THREAD

**Issue by agentwolf88** [mekanism/Mekanism#7490]
### Issue description

Crash at create world

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.25

### Mekanism version

10.2.1 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/LMw4CCSV

**Comment by pupnewfster** [comment]
Looks like it is due to an interaction with: https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob which is calling `getCapability` on the robit before it is even done constructing the entity or capabilities have been gathered. I am not quite sure if this is a bug on our end or their end. My suspicion is it is on their end, but I don't think there is anything they can easily do about it so I will make our `getCapability` code slightly safer for purposes of if it gets called before the entity is done constructing then it just no-ops but it still feels somewhat weird
