### ISSUE TITLE
Паровая турбина не выдаёт жидкость

### ISSUE THREAD

**Issue by Kellyen-Craft** [mekanism/Mekanism#7547]
### Issue description

Паровая Турбина не выдаёт жидкость и при установке конденсаторов, полностью их игнорирует
К ней никак нельзя подключить жидкостную трубу
Отсутствует показатель жидкости внутри (вероятно это связано с первым пунктом или вовсе не ошибка)
![2022-07-11_07 51 33](https://user-images.githubusercontent.com/109056200/178191205-c542c67f-2d85-4935-9df0-73bb59c6b152.png)
![2022-07-11_07 51 52](https://user-images.githubusercontent.com/109056200/178191210-0d3851b1-1615-4493-bf8e-cc9476dda080.png)

### Steps to reproduce

1. Создайте Паровую Турбину
2. Попробуйте получить из неё воду
3. Наблюдайте за результатом

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.35

### Mekanism version

Older

**Comment by Seniorendi** [comment]
Please write in english or else we can't help you

**Comment by Oct0bass** [comment]
From Apple translate:

> The steam turbine does not produce liquid and when installing capacitors, it completely ignores them

There is no way to connect a liquid pipe to it

There is no liquid indicator inside (probably due to the first point or not an error at all)

Шагы для воспроизведения

Create A Steam Turbine

Try to get water out of it

Watch the result

No idea what is being translated as “capacitor”, but it seems that the multi block is just not forming.  Did it emit red stone particles?  The configurator can help diagnose multi block issues, and you can do 
`/mek build turbine` in a creative world to see an example.

**Comment by pupnewfster** [comment]
You need saturating condensers in the turbine and vents on the outside to take the water out via.
