### ISSUE TITLE
QIO Redstone Adapter can't detect the stored count of Energy Tablets

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7561]
### Issue description

QIO Redstone Adapter can't detect the store count of Energy Tablets in the QIO.

### Steps to reproduce

1. Place down a QIO Redstone Adapter and set the frequency for it.
2. Set the QIO Redstone Adapter to Energy Tablet. It won't detect the stored number.

### Minecraft version

1.19 (Latest)

### Forge version

41.1.0

### Mekanism version

10.3.0 (Latest)

**Comment by pupnewfster** [comment]
I can't reproduce this which leads me to guess that you might have other mods installed that are adding random NBT to items when you view/hover over them? Which then would make it so that the tablet you set in the filter has NBT and doesn't match the crafted ones without any.

Though I do think I will go ahead and add support for allowing users to set their redstone adapter as fuzzy to ignore nbt.

**Comment by UnknownSerhan** [comment]
I don’t have a mod that changes NBT tags, I have mekanism with its addons, rubidium, a zoom mod and a gun mod
