### ISSUE TITLE
Mekanism 1.18.2 (multiple versions) causing indefinite server hang

### ISSUE THREAD

**Issue by zoe-svg** [mekanism/Mekanism#7565]
### Issue description

    I was making a server with a custom mod-pack and upon startup the server would hang. Writing no new lines to the debug.log, so I went about removing mods until it worked removing Mekanism fixed the hanging and the server started normally with all the other mods.

    I tried downgrading Mekanism to older versions and that failed. I tried taking a known working copy of Mekanism from another pack I have and that failed.

    I'm honestly stumped at this point. The only thing I can think of is a mod conflict or something but that would be printed to the console and debug.log.

### Steps to reproduce

*Not sure if it can be replicated on other machines/modpacks*

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

Forge mod loading, version 40.1.68

### Mekanism version

Older

### Other relevant versions

Mekanism version : 10.2.4.464, and others
Java Runtime: Java 17

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.githubusercontent.com/zoe-svg/d3a29fda1593ec9532067bc63268b2b7/raw/9e3237cc8c04d5873be462b9d4bcce660b8a5628/debug.log

**Comment by pupnewfster** [comment]
I wish I could give some potential solutions/things to try but I am sort of at a loss due to the log not really showing much, beyond a couple errors earlier on, the only one that I think is presumably somewhat related to Mekanism is the ones with `WTHIT` as in 1.18 `WTHIT` and `Jade` had conflicting APIs so we supported the more popular one on forge (`Jade`). Given the fact though that it keeps at least trying to load after `WTHIT` displays the errors I somewhat doubt that is what is causing it to fail to keep loading (though I suppose it is worth a shot to try launching it once without it and see if it can load). Another test that may be worthwhile is make a backup of your world and then try launching the pack on a fresh world and see if that provides any better errors though that is somewhat doubtful as well. (Only reason I am suggesting that is due to the messages about did not get id they expected is that it means mods were added to the world after creation, though in general that shouldn't really be causing any issues... just without having any other ideas might as well test it)
