### ISSUE TITLE
getWaste() Method returns a table 

### ISSUE THREAD

**Issue by JebMadrov** [mekanism/Mekanism#7583]
### Issue description

When using CC:tweaked with Mekanism and using the getWaste method it returns a table when it's supposed to return an int as said in the documentation I could find : https://web.archive.org/web/20220804210538/https://docs.srendi.de/1.16/integrations/mekanism/fission/ 
So either the documentation is wrong/outdated (considering the site is down it wouldn't be surprising) or there is a bug, if anyone has some actual up to date documentation on Mekanism Methods please share. 

### Steps to reproduce

create a program on CC:tweaked : 
react=peripheral.wrap("fissionReactorLogicAdapter_0")
local waste = react.getWaste()
do print(type(waste))
end

Result : 
table

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.68

### Mekanism version

Older

### Other relevant versions

cc-tweaked-1.18.2-1.100.9.jar

**Comment by pupnewfster** [comment]
`getWaste` returns a ChemicalStack in the form of:
```
"name": name as string,
"amount": amount as long
```
This is what it has returned since we added our integration back in 10.1.0... I have no idea what that wiki is or why it has incorrect info the only official source of what methods exists (besides in the code itself) is in [this spreadsheet](https://docs.google.com/spreadsheets/d/1sheh1BIeP_vSto881H6UtgXvxdbyJEfILM_uUW_UD7Q/edit#gid=1674588729).
