### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by Edivad99** [mekanism/Mekanism#7612]
### Issue description

It doesn't always happen (once every 3 saves), as soon as I leave a world this error message comes out

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.25

### Mekanism version

10.3.3 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/raw/xPshPbyW

**Comment by pupnewfster** [comment]
I am not able to reproduce this, and it almost sort of seems like a race condition of some kind given in theory if there is a level the configs should be loaded. My best guess as to why that may not be the case is that the configs then unload on the integrated server's thread, while the render tick method is still running on the client thread because there was a valid state when it started rendering.
