### ISSUE TITLE
Heaters don't emit enough light to melt ice

### ISSUE THREAD

**Issue by jobukkit** [mekanism/Mekanism#7659]
### Issue description

This is kind of a duplicate of #5301, but for heaters in particular it's not just an aesthetical thing. You'd expect heaters to melt ice, and if you use a temperature mod, prevent you from freezing to death. But they do not, ~~because they do not emit light outside of their own texture~~.

![2022-11-08_13 54 16](https://user-images.githubusercontent.com/2750434/200570918-4c106dc8-126e-4619-8196-bd5e942be881.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

31.2.57

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Hmm interesting. Not sure why it isn't visibly giving off any light for you (unless this is something we changed more recently, though I don't think it is). Though it seems the reason that the ice isn't melting is when active the heaters give off a light level of `8` for a bit of ambience (without performance issues from as many light updates if machines are going on and off), but it looks like ice only melts at like a light level of `11`. Definitely will need to think about this more (and maybe make heaters specifically use a light level of `11` instead of just `8`, unsure.

**Comment by jobukkit** [comment]
My apologies, I shouldn't have tested on 1.15. On 1.19 they do indeed emit light. I have changed the title of the issue.
