### ISSUE TITLE
[1.19.2] Ore Generation issues with Terralith

### ISSUE THREAD

**Issue by YOYOK9** [mekanism/Mekanism#7661]
### Issue description

Mekanism ores don't generate in Terralith's custom biomes, only in vanilla biomes. Making ores like osmium rarer then Diamonds. 

### Steps to reproduce

1. Install the latest mekanism & Terralith mods
2. Create a new world
3. Search for mek ores in Terralith biomes

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.47

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

I used worldedit to search areas within the different biomes for deepslate/stone based osmium ores. There was the rare occasion I would find mekanism ores in a Terralith biome chunk, but it would be only 1-5 ores total. 

Terralith: v2.3.5

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/YOYOK9/946adc1972cc726f298b2e476c8b5340

**Comment by pupnewfster** [comment]
Terralith seems to be adding some entries to various biome tags that don't exist and this is cascading up to the top level making it so that the `minecraft:is_overworld` tag is empty. We use this tag for determining which biomes to add our ores to. A user on discord reproduced the terralith tag issue with just vanilla and terralith so I am confident it is on their end and not something we are doing.

**Comment by pupnewfster** [comment]
Should be fixed in latest terralith version
