### ISSUE TITLE
Fusion Reactor generate more power than expected

### ISSUE THREAD

**Issue by StarBeard13** [mekanism/Mekanism#7671]
### Issue description

Hi,

I play with a home made modpack and i found a problem with my Fusion Reactor with abnormal rate.

I start with an injection rate at 8, and i start to generate, i didn't figure out the abnormal rate of [energy and plasma temperature](https://imgur.com/a/YWjsjR4). Then i try to reduce it to 2, then i got this stat https://imgur.com/a/MhIdM5H

### Steps to reproduce

Just lanching the fusion reactor without specific change

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.85

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Finally got more off a chance to start looking into things, and I am a bit confused what the issue is here? Especially as I am guessing what the "problem" here is is that reducing the injection rate instead of say a creating a new reactor/resetting it would still have some heat for a decent while from the previous higher rate (and thus produce higher levels of power)
