### ISSUE TITLE
Pressuried Tubes and Radioactive Waste Barrels Spatial Storage AE2

### ISSUE THREAD

**Issue by DRUNKFuzzyBunny** [mekanism/Mekanism#7683]
### Issue description

Trying to move fission reactor into spatial storage from advanced energetics 2 but pressurized tubes and the radioactive waste barrels will not transfer.  All other pipes, pumps, reactor, boilers, turbines, fissile fuel dynamic tank, etc all move without issue.  Tested with empty tubes and barrels and tested with items in tubes and barrels neither work.

### Steps to reproduce

1: setup spatial storage
2: try to move pressurized tubes and radioactive waster barrels to spatial storage
3: all other items are transfered except the tubes and waste barrels

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

tested with ATM 8 mod pack 1.0.5

**Comment by pupnewfster** [comment]
Guessing AE2 is (properly) respecting the blocks we tag as not being able to be moved/relocated. (As tags are non state specific that is why regardless of stored contents state they are marked as can't be moved). And this is fully intentional as otherwise the radiation stored in them would be released (and depending on how the mod moving the thing works, potentially duped).

**Comment by DRUNKFuzzyBunny** [comment]
Good to know, thank you.
