### ISSUE TITLE
digital miner bypass protect ftbchunk

### ISSUE THREAD

**Issue by joaoespanhol** [mekanism/Mekanism#7697]
### Issue description

When player A protects the chunk and places blocks
If player B does not have access to that protected chunk, use the digital miner filter, you can steal the player's base.

![image](https://user-images.githubusercontent.com/22871432/211146378-d288de95-c9a1-4e70-91af-8a4cac2fbf14.png)

### Steps to reproduce

Mod
FTB chunk

Mod version
ftb-chunks-forge-1902.3.14-build.218.jar

Forge / Fabric version
1.19.2-43.2.1

Modpack & version
No response

What issue are you having?
When player A protects the chunk and places blocks
If player B does not have access to that protected chunk, use the digital miner filter, you can steal the player's base.

image

Crashlogs
No response

Steps to reproduce
protect chunk
![image](https://user-images.githubusercontent.com/22871432/211146396-4ecc6975-94be-42ca-a8cc-e7f13876beeb.png)
other player use filter mekanism digital miner
start

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Mekanism version

10.3.5 (Latest)

**Comment by joaoespanhol** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/605
[desht](https://github.com/desht) commented [3 days ago](https://github.com/FTBTeam/FTB-Mods-Issues/issues/605#issuecomment-1369837469)
Looking at the code for the Digital Miner, it doesn't fire any block-break events, so FTB Chunks has no way of knowing that it's breaking blocks. This is something you would need to take up with the Mekanism team, as to whether they want to start firing block-break events.

**Comment by pupnewfster** [comment]
We have been firing block break events since 1.12 if not earlier (wasn't part of the team before 1.12 and don't feel like confirming how far back it goes). https://github.com/mekanism/Mekanism/blob/25459b3d3ef8f25d32c9ec4c8f214a4885e221e1/src/main/java/mekanism/common/tile/machine/TileEntityDigitalMiner.java#L529

So going to go with an fab chunks bug unless they can explain why it is on our end, as it seems like they just aren't listening to the event.
