### ISSUE TITLE
Quantum Entangloporter transfer rate is too slow

### ISSUE THREAD

**Issue by starskyC** [mekanism/Mekanism#7723]
### Issue description

The Quantum Entangloporter is just too slow for its price. I'm using it for my digital miner and hoping that I won't need to set up power plants each time I change spot mining. This is when I found out Quantum Entangloporter is incredibly slow in transfer rate and incredibly huge in storage, which is very counterintuitive.

In addition, is there a way for any mekanism storage block to output amount of energy storage in form of redstone signal? Or is it a feature that might come out in future?

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.57

### Mekanism version

Older

### Other relevant versions

Mekanism 10.2.5

**Comment by pupnewfster** [comment]
The quantum entangloporter already has very high limits and transfer rates for everything, if they are still too low for you you can up the buffers of them in `config/Mekanism/general.toml`. As of (I believe 10.1.0) QEs try to eject their entire buffer (split between all QEs that are ejecting on that frequency) instead of being limited to a lower number.

Both Energy cubes and Induction ports (when part of formed induction matrices) support attaching a comparator to them to get a signal based on the percentage filled.
