### ISSUE TITLE
[Griefing Bug] Flan Claim Bypass with Fluid Tanks & Configurator in Wrench Mode

### ISSUE THREAD

**Issue by JustAnotherGhostName** [mekanism/Mekanism#7730]
### Issue description

When using the Flan claim protection mod, you can bypass a claims protection by using a fluid tanks fluid placing feature in the claim, or by using the configurator on a mechanism block that is in the claim, allowing players to grief. 

### Steps to reproduce

1. Create a claim with flan, and transfer it to another player so you dont own it (or have another player make the claim)
2. Place some mekanism energy pipes and machines down in the claim
3. Use any tier fluid tank and place fluids down in the claim, resulting in a grief.
4. Use a configurator in wrench mode on the pipes and machines to break them
5. Successfully grief a base.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant versions

flan-1.19.2-1.8.3-forge.jar

**Comment by pupnewfster** [comment]
Sorry this took so long, but I finally got a chance to look into this, and I believe it is because they use [this list](https://github.com/Flemmli97/Flan/blob/fd7672bf7191a960567913cbf5fbcfbce8fea3cc/common/src/main/java/io/github/flemmli97/flan/api/permission/ObjectToPermissionMap.java#L150-L178) of items for what they actually [try to prevent](https://github.com/Flemmli97/Flan/blob/671e07a5f78590418b1b9fae4a35f5a1e2175644/common/src/main/java/io/github/flemmli97/flan/event/ItemInteractEvents.java#L76-L77) usage for. Which leads me to believe it is sort of intended (or more accurately a bug on their end) that they only stop vanilla items and blocks from interacting with things.
