### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by starixed** [mekanism/Mekanism#7733]
### Issue description

my log is getting spammed by this:
[10Feb2023 00:02:53.277] [Server thread/ERROR] [mekanism.common.Mekanism/]: Different orphan transmitter was already registered at location! [Coord4D: -267, 34, 19, dim=minecraft:overworld]

could it be a entangled block?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.4

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
When is it spammed by that? If it is on shutdown from what users in discord have tracked it down to it seems to be due to FTB Chunks doing weird things.

**Comment by starixed** [comment]
yes when i hit save and quit, unfortunately minecraft gets stuck on saving the world and looking over the logs its just spamming that

**Comment by starixed** [comment]
i have to force quit minecraft through the task manager in order for it to close

**Comment by pupnewfster** [comment]
From what people on mek's discord have tracked it down to it is a bug with FTB Chunks that causes it to not exit gracefully.

**Comment by SigmaFlame** [comment]
We removed FTB Chunks from our server and still have this spam from the console at the server shutdown.
Mekanism-1.19.2-10.3.8.477

**Comment by pupnewfster** [comment]
No idea, my best guess it is due to some mod causing something weird to happen during shutdown which causes our transmitters to basically get load calls happening without any unload call/processing, which some user did say removing FTB Chunks seemed to fix (but no idea if something else might also cause it). I will re-open this issue for now, mainly as a reminder to look into it a bit further because it could also be that there is some path that causes things to not fully flush invalid stuff on our end

**Comment by natryl** [comment]
Our server ended up with too many chunks loaded so I edited the ftbworld config to unload chunks from players inactive for more then 1 day. Now on shut down we have a very similar amount of mekanism errors from one base in particular that got unloaded. 
![image](https://user-images.githubusercontent.com/48296812/230968477-65ec2ff7-304a-4fd0-9230-1284c37ab595.png)

**Comment by zyxkad** [comment]
We have this problem too, and we never used FTBChunks

**Comment by zyxkad** [comment]
It's annoying since it will block server to stop, anyway to disable this log at least?

**Comment by Zonk1987** [comment]
I have the same Error on my server. I can't use the autorestart function anymore because of this because it is looping all the time.

https://mclo.gs/mtAHkhD

**Comment by Razorxd1993** [comment]
Have the same error and an autorestart of the server is no longer possible.

**Comment by pupnewfster** [comment]
Not able to reproduce this in any of the ways I tried, could someone who can easily reproduce this issue run `/mek debug` (which enables a bit of extra logging relating to our transmitter networks) and then provide the latest log for it. Hopefully it might provide some insight into what sequence of events are happening.

**Comment by voteforcats** [comment]
This issue happened when I used /reload to reload CraftTweaker.

**Comment by voteforcats** [comment]
When the issue happened with debug mode enabled, it did not seem to show anything different in the logs when the issue happened, but here is that latest.log anyway.

[latest.log](https://github.com/mekanism/Mekanism/files/13747232/latest.log)

**Comment by knzai** [comment]
Same issue suddenly on an FTB Genesis (SP) install. I'm happy to zip up my save/world and put it somewhere if that helps.

**Comment by Vany** [comment]
another case. ATM9. All pipes had disconnected each other in chunkloaded [hyperbox](https://github.com/Commoble/hyperbox) space.
i have no idea what happened during this, but everything disconnects after i leaved and entered again to hyperbox.
there is full set of muriatic acid and hdpe production and three entangloporters.
ont the server console lots of this log lines, i used it to find this issue =)

**Comment by MadSciSlack** [comment]
I've got this happening in my custom modpack as well. I've only noted this happening server-side when I stop / restart.  All of the pipes causing issues are mechanical (fluid) pipes.  Some notes I've made from around when it started:
- Installed Create: Connected which when updated causes MixIn Extras conflicts (Uses MixIn Extras 3.0, clashes with other mods using 2.x)
- Version locked Create: Connected so that it doesn't use MixIn Extras 3.0.  
- Installed Capable Cauldrons
- Tested and removed Create New Age (with Botarium)
- Removed Botarium
- Updated Canary
- Updated Saturn
- Updated Smooth Boot Reloaded
- Updated Connectivity and Cupboard
- NOT using FTBChunks, using Claim Chunks instead
- Using Hyperbox, but have never placed one in this world
- Server just had a wipe & restart, and there are **zero claims and zero force loaded chunks.**  None have ever been made.

- Previous world started having missing items due to saving issues very likely from this, hence why the wipe & restart.  Sadly, it didn't fix the issue.  I haven't noticed any missing blocks yet, but the server has only been running a couple of days since reset.

- Only affects Mekanism pipes.  Most others don't have a holding capacity, but other than this I cannot guess why.

I'll try some experimenting to see if I can isolate what is causing this in my pack to see if I can isolate what change started this.  It's tricky, because it only acts up server-side.  I've been working on this pack for 15 months, so I'm really hoping your team can help investigate this further.

**Comment by MadSciSlack** [comment]
Update to previous:
-Tested with Capable Cauldrons disabled with no change.
-Tested with Create: Connected disabled with no change.

**Comment by TheBerleyman** [comment]
I'm hitting this issue on a server with a custom modpack most of the time when shutting-down the server.

Notably, we're using Hyperbox, as well. I've got a Fission Reactor in one box and Steam Turbine in another, as well as a few other boxes, but the chunk the boxes are in is chunkloaded (using an Anchor upgrade in a machine in the main dimension).

The possibility of an issue with Mekanism pipes interacting with the hyperboxes certainly seems worth looking into.

**Comment by darthvader45** [comment]
Happening with my modded instance, using version 10.4.6.20 for 1.20.1.  I literally cannot save my world with this error.  I was only experimenting with the laser and laser tractor beam for the lulz.

**Comment by darthvader45** [comment]
Happened again with ultimate logistical transporters, using 10.4.8.43 for 1.20.1.  This is not good, if any Mekanism blocks can cause this.  https://paste.ee/p/LmeoR  Here's my recent latest.log to provide any necessary information.

**Comment by iCantComeUpWithAnything** [comment]
this happend to me on 1.20.1 NeoForge 47.1.106 after updating GTCEu to 1.5.4, LDLib to 1.0.33.b, JEI to 15.20.0.105 & 
EMI to 1.1.18 so these might be related in some way

**Comment by frogwallet** [comment]
ATM9 here - i've confirmed we're using the version Mekanism-1.20.1-10.4.13.69 and it looks like we're getting the new error message spam from this commit:
https://github.com/mekanism/Mekanism/commit/a1ea0e922bc55c89f083923565adc35a14caf3d2
![Image](https://github.com/user-attachments/assets/3c7064dc-3784-4ad4-8407-3b787be035e6)

It does appear to be chunk loading related, it's as players log out and their chunks unload (or they move a distance away). The cables also do appear to stop working, and often need to be re-placed after reloading the chunks.

**Comment by kevin2845** [comment]
I also ran into this issue. I also have reactors in hyperboxes, and pipes connecting them through the hyperbox ports. I think this could be the issue.
