### ISSUE TITLE
Swastikas' visible when using solar panels on a thermal evaporator 

### ISSUE THREAD

**Issue by mathewsasickcunt** [mekanism/Mekanism#7782]
### Issue description

When using the Thermal evaporator multiblock with solar array on top of the multiblock a swastika appears with the way the tops of the advance panels are displayed.
![2023-04-30_16 31 18](https://user-images.githubusercontent.com/17152918/235335840-edb6edde-a4e5-4f61-91df-ca8817202ff8.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.1

### Mekanism version

Older

**Comment by a-droid-boop** [comment]
you know you dont have to arrange it in the pattern of a swatsika, and besides you should be using a resistive heater with a TEP and not 4 adv solar panels...

**Comment by pupnewfster** [comment]
I will think about this more at some point if this is something we want to change models for some rotations to prevent, but unsure what the decision will be given there are plenty of ways to arrange them that this doesn't happen and also there is nothing stopping players from using dirt or any other block to arrange those in a swastika as well.

**Comment by Th3Fanbus** [comment]
When using the advanced solar generators' power output (to power resistive heaters, for instance), having two outputs on one side and the other two outputs on the opposite side allows using the minimum number of cables to connect everything together. There's no practical reason to have the advanced solar generators 90 degrees offset from each other, so... Why do it?

That being said, changing the advanced solar generator's model to have three solar panels (instead of having two separated by a gap) would prevent swastikas from appearing. No idea, but it seems to be a relatively straightforward change.

**Comment by craft90** [comment]
That's not technically a Swastika either. A Swastika is turned 45 degrees. What you got here is a symbol that has used to symbolize the sun in many cultures. The solution is simple, just arrange the advanced generators differently. Like someone else said, any block can be used to make offensive symbols in Minecraft. This feels like an user issue, rather than a mod issue.

**Comment by SekhetBR** [comment]
I ran into this while recording a video, and I can't tell you how glad I was that I noticed the issue before posting it.

A potential fix is only allowing the advanced generators to be placed oriented N-S or E-W. 

The fact that other blocks can be used to make offensive symbols should not prevent a fix to this block. Just because somebody can do something offensive intentionally doesn't mean that there should be an easy way for someone unsuspecting to do so unintentionally.

**Comment by LukeOnuke** [comment]
Dont get me wrong, i am not a nazi (infact almost my entire family got killed by them).

But this is just intentionaly making that, that would be like reporting a bug to mojang that you can make a swastika

**Comment by imetators** [comment]
You can pretty much just place them differently if this symbol is something you prefer not to see. Problem solved. 
Additionally, as someone mentioned, you can just place resistive heater to heatup evaporation plant and remove solar panels entirely.

**Comment by thiakil** [comment]
If someone PRs a new model that has a different panel arrangement I'll be happy to accept it (based on its own merit), but I don't think it's worth the effort to prevent accidental placement given these panels have existed for multiple years at this point.
