### ISSUE TITLE
1.19.2 10.3.8.477 Electrolytic Separator does not accept heavy water

### ISSUE THREAD

**Issue by bentwire** [mekanism/Mekanism#7790]
### Issue description

The Electrolytic Separator won't accept heavy water.  It seems to accept any of the others like water and brine, but not heavy water.

### Steps to reproduce

Start game
Place electrolytic Separator
Try to place bucket of heavy water in input window.
It won't take it.  Or any other source of heavy water where other liquids work.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

Tried removing all other mods to make sure it was not some interaction.

**Comment by bentwire** [comment]
This only seems to happen if you don't include the other mods in addition to the base mod...  This might not be an issue?

**Comment by pupnewfster** [comment]
For clarification do you mean this happens when you have Mekanism but not Mekanism: Generators? Or do you mean it happens if you have other non Mekanism mods in addition to Mekanism and Mekanism: Generators?

Given if it is the prior, that would make sense as the recipe for separating heavy water is part of Mekanism: Generators as it is used to create deuterium.

**Comment by bentwire** [comment]
AH!  That explains it!  Closing!
