### ISSUE TITLE
1.20.1 Seismic Vibrator Causes Server Crash due to Null Pointer Exception

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7820]
### Issue description

During the gameplay on a server running Minecraft 1.20.1, the server crashed due to a Null Pointer Exception. The issue seems to be related to the "Seismic Vibrator" block from the Mekanism mod. The expected outcome should have been the normal operation of the Seismic Vibrator without causing a server crash.

### Steps to reproduce

1.Place a Seismic Vibrator block in the world.
2.Power it and set it to operate.
3.After a period of operation, the server crashes with a Null Pointer Exception related to the Seismic Vibrator.

### Minecraft version

1.20.1

### Forge version

47.1.3

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

There are no other mods that appear to be directly involved in the crash.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/suiheng/547ab78b2bb3ee2cef2204a40b6ecd6b

**Comment by pupnewfster** [comment]
First off using hybrid server software is never recommended for forge mods as it tends to break a bunch of things. But other than that: report this issue to arclight as they are [making assumptions](https://github.com/IzzelAliz/Arclight/blob/Trials/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/level/gameevent/GameEventDispatcherMixin.java#L35) that the game event is going to be vanilla... when given it is a modded environment that is not even a remotely safe assumption.

On another note why they are even mixing in there instead of listening to the `VanillaGameEvent` that forge adds and proxying that to plugins I have no idea.
