### ISSUE TITLE
hydrofluoric acid

### ISSUE THREAD

**Issue by icywhisker-official** [mekanism/Mekanism#7834]
### Issue description

auto crafting hydrofluoric acid returns an uneven amount than what the recipe calls for. the recipe is set to .1mb of sulfuric acid but even after manually adjusting the recipe to .3mb of sulfuric acid, I'm still left with 3 fluorite in the dissolution chamber and about 95% completed on the 4th conversion

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.8

**Comment by Burkino** [comment]
I'm playing AllTheMods8 and I noticed this as well. It seems to be using between 930 and 1051 mB of sulfuric acid, but it also doesn't use the last few remaining mB.
The machine accepts gas upgrades so the little bit of randomness is probably intentional.

**Comment by pupnewfster** [comment]
This is intentional. A lot of the recipe processes that have a secondary chemical that gets used in the machine (especially in machines that accept gas upgrades) use statistical calculations for calculating how much will be used each tick. For JEI I try to show a rough estimate that roughly represents what the amount converges to (as there is such a wide range that there might be it would be difficult to fully convey what the range is).

I am closing this, but if you have any better ideas of how to convey that concept in JEI I am open to making changes to how it is represented there.
