### ISSUE TITLE
Gravitational Modulation Unit not working

### ISSUE THREAD

**Issue by xcleaner902** [mekanism/Mekanism#8008]
### Issue description

When pressing double Space it gives the speed boost for about 1 Tick but does not allow me to fly. There is no gamerule hindering flight as the ProjectE armor works just fine. I've tried using only the Gravitational unit in my Suit but it does not work as well.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.2.18

### Mekanism version

Older

**Comment by xcleaner902** [comment]
Seems to conflict with the Inventory pets Mod dont know why

**Comment by pupnewfster** [comment]
Why ProjectE works and Mekanism doesn't I am unsure as the code is handled effectively the same in both of them, though maybe the events are being received in a different order so it just happens to work. But if there is a conflict with Inventory Pets please report it to them. My best guess is they may be always disabling flight if their flying pet condition isn't met, instead of only disabling it if they had previously enabled it.
