### ISSUE TITLE
Rendering related crash when placing balloon with shaders

### ISSUE THREAD

**Issue by Aprilxoxo** [mekanism/Mekanism#8050]
### Issue description

full game crash upon placing balloon

### Steps to reproduce

have shaders (iris)
place balloon
crash

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

40.2.18

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/ZKhx95kF

**Comment by embeddedt** [comment]
This is probably caused by the way Iris wraps render buffers. Applying the change in https://github.com/mekanism/Mekanism/commit/a961bcbf0cc641b08dd594e3c72c7be3dfbd85d6#diff-9c48c6b6f28c3db0d157cd351e480e9cd229b1282de43da3379b150cc629fa6c will almost certainly fix the issue, but I doubt this will get backported to 1.18, so someone would have to make a patch mod that does it.

**Comment by pupnewfster** [comment]
Yeah, we are not currently developing for old versions, and unfortunately the issue wasn't discovered until after we had moved on past 1.18
