### ISSUE TITLE
In the creative menu, the "Solar Generator" has only 9 components, but when placed, it has 10 components.

### ISSUE THREAD

**Issue by Lolothepro** [mekanism/Mekanism#8111]
### Issue description

In the creative menu, the "Solar Generator" has only 9 components, but when placed, it has 10 components.
This causes issues with the "Pick up" action

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.6-beta

### Mekanism version

10.6.0 (Latest)

**Comment by UnknownSerhan** [comment]
Placing it makes it own to you which adds another component probably.

**Comment by pupnewfster** [comment]
This is intentional as it is adding the owner component. But as discussed on discord I am fine with adding a config to allow users to skip copying of any components from just doing a middle click. (This config option will end up in the common config, given while I believe the method is only called on the client side, there may be mods calling it server side and I don't want the lack of the config option to error out)
