### ISSUE TITLE
Light Update For Machines Etc Doesn't Always Sync

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8115]
### Issue description

When a machine toggles its light a few times in a row, the light turns off with a bit of delay. Turning on has no issues. An example with fluid tanks:

https://github.com/mekanism/Mekanism/assets/69000972/3b3562a5-fcf6-4745-8bce-2922cfb69245

### Steps to reproduce

1. Make the light of machines toggle a few times.
2. See that the light turns off with a bit of delay.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.8-beta

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

**Comment by UnknownSerhan** [comment]
Update: This happens with the sound effects too.

**Comment by pupnewfster** [comment]
Sound and stuff is known for machines. Though for things like the fluid tank that are manual toggles by the player, this is a bug. If you want other things to not have a delay turning off adjust the `blockDeactivationDelay` config in the general config file.  This is a feature so that machines that are rapidly toggling do not cause lag from having the chunk toggle back and forth a bunch.
