### ISSUE TITLE
Mekanism 1.20.1 crashing when opening UI

### ISSUE THREAD

**Issue by JerseyVT** [mekanism/Mekanism#8135]
### Issue description

When in creative mode on a modded server with other mods,  if you open your inventory in creative mod, mekanism will crash your game

### Steps to reproduce

1. Load into modded MC multiplayer server
2. Set game mode to creative
3. Open UI
4. Should open Inventory/UI instead crashes

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

1.20.1 - 47.3.1

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/B7pi9sgd

**Comment by pupnewfster** [comment]
Can you please provide your latest log file. It seems like some mod broke something with modloading and then when it got to mekanism it was in an invalid state. At least in the past when this has happened, the full log has shown the culprits.

**Comment by Fidulus** [comment]
Maybe mine can help shed some light on it. I provide my crashlog below.
It´s running fine without mekanism (but i love the mod too much to play without it).
I guess it´s something between "architectury" and "mekanism" but ofc i am not sure...

NeoForge: 21.0.39 (because 21.0.40 breaks architectury)

[https://pastebin.com/DQs8iU1Q](url)

**Comment by Fidulus** [comment]
> Can you please provide your latest log file. It seems like some mod broke something with modloading and then when it got to mekanism it was in an invalid state. At least in the past when this has happened, the full log has shown the culprits.

Maybe mine can help shed some light on it. I provide my crashlog below.
It´s running fine without mekanism (but i love the mod too much to play without it).
I guess it´s something between "architectury" and "mekanism" but ofc i am not sure...

NeoForge: 21.0.39 (because 21.0.40 breaks architectury)

[https://pastebin.com/DQs8iU1Q](url)

**Comment by JerseyVT** [comment]
I'm unable to find my specific log file since I had deleted the curse forge profile.

But file Fidulus provided [File](https://pastebin.com/DQs8iU1Q) is similar to what I had going on and could be utilized most likely.

**Comment by pupnewfster** [comment]
> Mod 'architectury' is not available!
