### ISSUE TITLE
Crash when placing quantum entangloporter under Soph storage chest with hopper upgrade

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#8275]
### Issue description

Relaying from atm10 discord
User placed quantum entangloporter under a sophisticated storage chest with hopper upgrade, server immediately crashes.

Sophisticated storage dev commented that this should likely be fixed on mekanisms side.

### Steps to reproduce

User provided video of them replicating the issue
https://github.com/user-attachments/assets/bfa78565-c5da-4ffb-bcbe-833dea58c2e5

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.90

### Mekanism version

10.7.7 (Latest)

### Other relevant versions

sophisticatedstorage-1.21.1-1.0.2.984

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/43w6KkY

**Comment by thiakil** [comment]
Can this be reproduced with just Mekanism and Sophisticated Storage?
That looks to be caused by an invalidations listener hanging around from the previous QE, and it is being triggered recursively by SS trying to get an updated block entity during the cache invalidation _while the new block entity is being constructed_

This is not something Mekanism causes, the invalidation is all Neoforge

**Comment by ghost** [comment]
While i can reproduce the crash with the full mod list, happened immediately when i set a channel in the QE while replicating the setup, i have been unable to reproduce it in an instance with only the required mods for the setup (Mekanism, Iron Furnaces and Sophisticated Storage)
Log (probably not helpful) https://mclo.gs/tptHX9r
I will continue to add and remove mods to my test instance

**Comment by ghost** [comment]
Issue can be replicated by using sophisticated storage hopper upgrade with other 3rd party mods, without anything from Mekanism involved, my apologies for bringing this here
