### ISSUE TITLE
Digital Miner being OP

### ISSUE THREAD

**Issue by ReFleXisGod** [mekanism/Mekanism#989]
I do think that the Digital Miner is too OP and is not as end game as many think. Could balance it by simply upping the power needed.

**Comment by Badcholo** [comment]
With Mekanism there is endless infinite power. Why do you think that increasing the power level will matter? I would just make more machines as the ores come in until i had enough for it to run non stop. It doesn't take that long to begin to receive endless ores with endless power. 
All i need is a config option to force players to mine everything. Mining just diamonds in a 32x32 is wickedly OP and is so much worse than letting players use X-ray.
Again, a config option to force players to mine everything instead of being able to select what ores they wish to mine. The speed and energy with the upgrades is perfect. Also increasing the power consumption too much causes the miner to just work like crud.

**Comment by laz2727** [comment]
You understand that "everything" means "Every block ever in these 4 chunks"?

2015-04-23 13:31 GMT+06:00 Badcholo <notifications@github.com>:

**Comment by Badcholo** [comment]
Yes i do understand that. I have played voltz for years and i have created my own server and custom modpack with the voltz theme. The Digital miner is always banned. No server ever allows the Digital miner because it is too op, but it is an awsome and very useful machine. I used to use MFFS disintigration module to mine because there was no better option and that removes every block. Antimatter Explosives already ruin the world. The Digital miner can have the power balanced and will still require you to setup a base for it. I think i'm just asking for a config that will remove being able to filter the ores. It would be nice to have them mine everything below the set level or below the miner.
